// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"upgradelink-admin-upgrade/server/ent/predicate"
	"upgradelink-admin-upgrade/server/ent/upgradelnxupgradestrategyflowlimitstrategy"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery is the builder for querying UpgradeLnxUpgradeStrategyFlowLimitStrategy entities.
type UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery struct {
	config
	ctx        *QueryContext
	order      []upgradelnxupgradestrategyflowlimitstrategy.OrderOption
	inters     []Interceptor
	predicates []predicate.UpgradeLnxUpgradeStrategyFlowLimitStrategy
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery builder.
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) Where(ps ...predicate.UpgradeLnxUpgradeStrategyFlowLimitStrategy) *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery {
	ulusflsq.predicates = append(ulusflsq.predicates, ps...)
	return ulusflsq
}

// Limit the number of records to be returned by this query.
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) Limit(limit int) *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery {
	ulusflsq.ctx.Limit = &limit
	return ulusflsq
}

// Offset to start from.
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) Offset(offset int) *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery {
	ulusflsq.ctx.Offset = &offset
	return ulusflsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) Unique(unique bool) *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery {
	ulusflsq.ctx.Unique = &unique
	return ulusflsq
}

// Order specifies how the records should be ordered.
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) Order(o ...upgradelnxupgradestrategyflowlimitstrategy.OrderOption) *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery {
	ulusflsq.order = append(ulusflsq.order, o...)
	return ulusflsq
}

// First returns the first UpgradeLnxUpgradeStrategyFlowLimitStrategy entity from the query.
// Returns a *NotFoundError when no UpgradeLnxUpgradeStrategyFlowLimitStrategy was found.
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) First(ctx context.Context) (*UpgradeLnxUpgradeStrategyFlowLimitStrategy, error) {
	nodes, err := ulusflsq.Limit(1).All(setContextOp(ctx, ulusflsq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{upgradelnxupgradestrategyflowlimitstrategy.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) FirstX(ctx context.Context) *UpgradeLnxUpgradeStrategyFlowLimitStrategy {
	node, err := ulusflsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UpgradeLnxUpgradeStrategyFlowLimitStrategy ID from the query.
// Returns a *NotFoundError when no UpgradeLnxUpgradeStrategyFlowLimitStrategy ID was found.
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ulusflsq.Limit(1).IDs(setContextOp(ctx, ulusflsq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{upgradelnxupgradestrategyflowlimitstrategy.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) FirstIDX(ctx context.Context) int {
	id, err := ulusflsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UpgradeLnxUpgradeStrategyFlowLimitStrategy entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UpgradeLnxUpgradeStrategyFlowLimitStrategy entity is found.
// Returns a *NotFoundError when no UpgradeLnxUpgradeStrategyFlowLimitStrategy entities are found.
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) Only(ctx context.Context) (*UpgradeLnxUpgradeStrategyFlowLimitStrategy, error) {
	nodes, err := ulusflsq.Limit(2).All(setContextOp(ctx, ulusflsq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{upgradelnxupgradestrategyflowlimitstrategy.Label}
	default:
		return nil, &NotSingularError{upgradelnxupgradestrategyflowlimitstrategy.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) OnlyX(ctx context.Context) *UpgradeLnxUpgradeStrategyFlowLimitStrategy {
	node, err := ulusflsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UpgradeLnxUpgradeStrategyFlowLimitStrategy ID in the query.
// Returns a *NotSingularError when more than one UpgradeLnxUpgradeStrategyFlowLimitStrategy ID is found.
// Returns a *NotFoundError when no entities are found.
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ulusflsq.Limit(2).IDs(setContextOp(ctx, ulusflsq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{upgradelnxupgradestrategyflowlimitstrategy.Label}
	default:
		err = &NotSingularError{upgradelnxupgradestrategyflowlimitstrategy.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) OnlyIDX(ctx context.Context) int {
	id, err := ulusflsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UpgradeLnxUpgradeStrategyFlowLimitStrategies.
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) All(ctx context.Context) ([]*UpgradeLnxUpgradeStrategyFlowLimitStrategy, error) {
	ctx = setContextOp(ctx, ulusflsq.ctx, ent.OpQueryAll)
	if err := ulusflsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UpgradeLnxUpgradeStrategyFlowLimitStrategy, *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery]()
	return withInterceptors[[]*UpgradeLnxUpgradeStrategyFlowLimitStrategy](ctx, ulusflsq, qr, ulusflsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) AllX(ctx context.Context) []*UpgradeLnxUpgradeStrategyFlowLimitStrategy {
	nodes, err := ulusflsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UpgradeLnxUpgradeStrategyFlowLimitStrategy IDs.
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ulusflsq.ctx.Unique == nil && ulusflsq.path != nil {
		ulusflsq.Unique(true)
	}
	ctx = setContextOp(ctx, ulusflsq.ctx, ent.OpQueryIDs)
	if err = ulusflsq.Select(upgradelnxupgradestrategyflowlimitstrategy.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) IDsX(ctx context.Context) []int {
	ids, err := ulusflsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ulusflsq.ctx, ent.OpQueryCount)
	if err := ulusflsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ulusflsq, querierCount[*UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery](), ulusflsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) CountX(ctx context.Context) int {
	count, err := ulusflsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ulusflsq.ctx, ent.OpQueryExist)
	switch _, err := ulusflsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) ExistX(ctx context.Context) bool {
	exist, err := ulusflsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) Clone() *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery {
	if ulusflsq == nil {
		return nil
	}
	return &UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery{
		config:     ulusflsq.config,
		ctx:        ulusflsq.ctx.Clone(),
		order:      append([]upgradelnxupgradestrategyflowlimitstrategy.OrderOption{}, ulusflsq.order...),
		inters:     append([]Interceptor{}, ulusflsq.inters...),
		predicates: append([]predicate.UpgradeLnxUpgradeStrategyFlowLimitStrategy{}, ulusflsq.predicates...),
		// clone intermediate query.
		sql:  ulusflsq.sql.Clone(),
		path: ulusflsq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Enable int32 `json:"enable,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UpgradeLnxUpgradeStrategyFlowLimitStrategy.Query().
//		GroupBy(upgradelnxupgradestrategyflowlimitstrategy.FieldEnable).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) GroupBy(field string, fields ...string) *UpgradeLnxUpgradeStrategyFlowLimitStrategyGroupBy {
	ulusflsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UpgradeLnxUpgradeStrategyFlowLimitStrategyGroupBy{build: ulusflsq}
	grbuild.flds = &ulusflsq.ctx.Fields
	grbuild.label = upgradelnxupgradestrategyflowlimitstrategy.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Enable int32 `json:"enable,omitempty"`
//	}
//
//	client.UpgradeLnxUpgradeStrategyFlowLimitStrategy.Query().
//		Select(upgradelnxupgradestrategyflowlimitstrategy.FieldEnable).
//		Scan(ctx, &v)
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) Select(fields ...string) *UpgradeLnxUpgradeStrategyFlowLimitStrategySelect {
	ulusflsq.ctx.Fields = append(ulusflsq.ctx.Fields, fields...)
	sbuild := &UpgradeLnxUpgradeStrategyFlowLimitStrategySelect{UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery: ulusflsq}
	sbuild.label = upgradelnxupgradestrategyflowlimitstrategy.Label
	sbuild.flds, sbuild.scan = &ulusflsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UpgradeLnxUpgradeStrategyFlowLimitStrategySelect configured with the given aggregations.
func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) Aggregate(fns ...AggregateFunc) *UpgradeLnxUpgradeStrategyFlowLimitStrategySelect {
	return ulusflsq.Select().Aggregate(fns...)
}

func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ulusflsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ulusflsq); err != nil {
				return err
			}
		}
	}
	for _, f := range ulusflsq.ctx.Fields {
		if !upgradelnxupgradestrategyflowlimitstrategy.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ulusflsq.path != nil {
		prev, err := ulusflsq.path(ctx)
		if err != nil {
			return err
		}
		ulusflsq.sql = prev
	}
	return nil
}

func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UpgradeLnxUpgradeStrategyFlowLimitStrategy, error) {
	var (
		nodes = []*UpgradeLnxUpgradeStrategyFlowLimitStrategy{}
		_spec = ulusflsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UpgradeLnxUpgradeStrategyFlowLimitStrategy).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UpgradeLnxUpgradeStrategyFlowLimitStrategy{config: ulusflsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ulusflsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ulusflsq.querySpec()
	_spec.Node.Columns = ulusflsq.ctx.Fields
	if len(ulusflsq.ctx.Fields) > 0 {
		_spec.Unique = ulusflsq.ctx.Unique != nil && *ulusflsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ulusflsq.driver, _spec)
}

func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(upgradelnxupgradestrategyflowlimitstrategy.Table, upgradelnxupgradestrategyflowlimitstrategy.Columns, sqlgraph.NewFieldSpec(upgradelnxupgradestrategyflowlimitstrategy.FieldID, field.TypeInt))
	_spec.From = ulusflsq.sql
	if unique := ulusflsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ulusflsq.path != nil {
		_spec.Unique = true
	}
	if fields := ulusflsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upgradelnxupgradestrategyflowlimitstrategy.FieldID)
		for i := range fields {
			if fields[i] != upgradelnxupgradestrategyflowlimitstrategy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ulusflsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ulusflsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ulusflsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ulusflsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ulusflsq *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ulusflsq.driver.Dialect())
	t1 := builder.Table(upgradelnxupgradestrategyflowlimitstrategy.Table)
	columns := ulusflsq.ctx.Fields
	if len(columns) == 0 {
		columns = upgradelnxupgradestrategyflowlimitstrategy.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ulusflsq.sql != nil {
		selector = ulusflsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ulusflsq.ctx.Unique != nil && *ulusflsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ulusflsq.predicates {
		p(selector)
	}
	for _, p := range ulusflsq.order {
		p(selector)
	}
	if offset := ulusflsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ulusflsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UpgradeLnxUpgradeStrategyFlowLimitStrategyGroupBy is the group-by builder for UpgradeLnxUpgradeStrategyFlowLimitStrategy entities.
type UpgradeLnxUpgradeStrategyFlowLimitStrategyGroupBy struct {
	selector
	build *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ulusflsgb *UpgradeLnxUpgradeStrategyFlowLimitStrategyGroupBy) Aggregate(fns ...AggregateFunc) *UpgradeLnxUpgradeStrategyFlowLimitStrategyGroupBy {
	ulusflsgb.fns = append(ulusflsgb.fns, fns...)
	return ulusflsgb
}

// Scan applies the selector query and scans the result into the given value.
func (ulusflsgb *UpgradeLnxUpgradeStrategyFlowLimitStrategyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ulusflsgb.build.ctx, ent.OpQueryGroupBy)
	if err := ulusflsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery, *UpgradeLnxUpgradeStrategyFlowLimitStrategyGroupBy](ctx, ulusflsgb.build, ulusflsgb, ulusflsgb.build.inters, v)
}

func (ulusflsgb *UpgradeLnxUpgradeStrategyFlowLimitStrategyGroupBy) sqlScan(ctx context.Context, root *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ulusflsgb.fns))
	for _, fn := range ulusflsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ulusflsgb.flds)+len(ulusflsgb.fns))
		for _, f := range *ulusflsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ulusflsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ulusflsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UpgradeLnxUpgradeStrategyFlowLimitStrategySelect is the builder for selecting fields of UpgradeLnxUpgradeStrategyFlowLimitStrategy entities.
type UpgradeLnxUpgradeStrategyFlowLimitStrategySelect struct {
	*UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ulusflss *UpgradeLnxUpgradeStrategyFlowLimitStrategySelect) Aggregate(fns ...AggregateFunc) *UpgradeLnxUpgradeStrategyFlowLimitStrategySelect {
	ulusflss.fns = append(ulusflss.fns, fns...)
	return ulusflss
}

// Scan applies the selector query and scans the result into the given value.
func (ulusflss *UpgradeLnxUpgradeStrategyFlowLimitStrategySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ulusflss.ctx, ent.OpQuerySelect)
	if err := ulusflss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery, *UpgradeLnxUpgradeStrategyFlowLimitStrategySelect](ctx, ulusflss.UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery, ulusflss, ulusflss.inters, v)
}

func (ulusflss *UpgradeLnxUpgradeStrategyFlowLimitStrategySelect) sqlScan(ctx context.Context, root *UpgradeLnxUpgradeStrategyFlowLimitStrategyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ulusflss.fns))
	for _, fn := range ulusflss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ulusflss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ulusflss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
