// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"upgradelink-admin-upgrade/server/ent/upgrademacupgradestrategy"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UpgradeMacUpgradeStrategy is the model entity for the UpgradeMacUpgradeStrategy schema.
type UpgradeMacUpgradeStrategy struct {
	config `json:"-"`
	// ID of the ent.
	// ID
	ID int `json:"id,omitempty"`
	// 公司ID
	CompanyID int `json:"company_id,omitempty"`
	// 是否生效；可通过此控制策略是否生效0：失效；1：生效
	Enable int32 `json:"enable,omitempty"`
	// 任务名称
	Name string `json:"name,omitempty"`
	// 任务描述信息
	Description string `json:"description,omitempty"`
	// mac应用ID
	MACID int `json:"mac_id,omitempty"`
	// mac_version_id; 外键mac_version.id
	MACVersionID int `json:"mac_version_id,omitempty"`
	// 升级任务开始时间
	BeginDatetime time.Time `json:"begin_datetime,omitempty"`
	// 升级任务结束时间
	EndDatetime time.Time `json:"end_datetime,omitempty"`
	// 升级方式：0：未知方式；1：提示升级；2：静默升级；3: 强制升级
	UpgradeType int32 `json:"upgrade_type,omitempty"`
	// 提示升级描述内容
	PromptUpgradeContent string `json:"prompt_upgrade_content,omitempty"`
	// 指定升级的设备范围：0：全部设备；1：指定设备分组；2：指定机型
	UpgradeDevType int32 `json:"upgrade_dev_type,omitempty"`
	// 升级设备数据：0.当为全部设备时，此字段为空；；1.当指定设备分组时，此字段存储设备分组id；2.当指定设备机型时，此字段存储选中的设备机型id;
	UpgradeDevData string `json:"upgrade_dev_data,omitempty"`
	// 指定升级的应用版本：0：全部版本；1：指定版本
	UpgradeVersionType int32 `json:"upgrade_version_type,omitempty"`
	// 升级设备数据：0.当为全部版本时，此字段为空；；1.当指定应用版本时，此字段存储应用版本id;
	UpgradeVersionData string `json:"upgrade_version_data,omitempty"`
	// 是否开启灰度 0：不开启；1：开启
	IsGray int32 `json:"is_gray,omitempty"`
	// 灰度策略id数据
	GrayData string `json:"gray_data,omitempty"`
	// 是否开启频控 0：不开启；1：开启
	IsFlowLimit int32 `json:"is_flow_limit,omitempty"`
	// 频控策略id数据
	FlowLimitData string `json:"flow_limit_data,omitempty"`
	// 是否删除 0：正常；1：已删除
	IsDel int32 `json:"is_del,omitempty"`
	// 创建时间
	CreateAt time.Time `json:"create_at,omitempty"`
	// 修改时间
	UpdateAt     time.Time `json:"update_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpgradeMacUpgradeStrategy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upgrademacupgradestrategy.FieldID, upgrademacupgradestrategy.FieldCompanyID, upgrademacupgradestrategy.FieldEnable, upgrademacupgradestrategy.FieldMACID, upgrademacupgradestrategy.FieldMACVersionID, upgrademacupgradestrategy.FieldUpgradeType, upgrademacupgradestrategy.FieldUpgradeDevType, upgrademacupgradestrategy.FieldUpgradeVersionType, upgrademacupgradestrategy.FieldIsGray, upgrademacupgradestrategy.FieldIsFlowLimit, upgrademacupgradestrategy.FieldIsDel:
			values[i] = new(sql.NullInt64)
		case upgrademacupgradestrategy.FieldName, upgrademacupgradestrategy.FieldDescription, upgrademacupgradestrategy.FieldPromptUpgradeContent, upgrademacupgradestrategy.FieldUpgradeDevData, upgrademacupgradestrategy.FieldUpgradeVersionData, upgrademacupgradestrategy.FieldGrayData, upgrademacupgradestrategy.FieldFlowLimitData:
			values[i] = new(sql.NullString)
		case upgrademacupgradestrategy.FieldBeginDatetime, upgrademacupgradestrategy.FieldEndDatetime, upgrademacupgradestrategy.FieldCreateAt, upgrademacupgradestrategy.FieldUpdateAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpgradeMacUpgradeStrategy fields.
func (umus *UpgradeMacUpgradeStrategy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upgrademacupgradestrategy.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			umus.ID = int(value.Int64)
		case upgrademacupgradestrategy.FieldCompanyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field company_id", values[i])
			} else if value.Valid {
				umus.CompanyID = int(value.Int64)
			}
		case upgrademacupgradestrategy.FieldEnable:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field enable", values[i])
			} else if value.Valid {
				umus.Enable = int32(value.Int64)
			}
		case upgrademacupgradestrategy.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				umus.Name = value.String
			}
		case upgrademacupgradestrategy.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				umus.Description = value.String
			}
		case upgrademacupgradestrategy.FieldMACID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field mac_id", values[i])
			} else if value.Valid {
				umus.MACID = int(value.Int64)
			}
		case upgrademacupgradestrategy.FieldMACVersionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field mac_version_id", values[i])
			} else if value.Valid {
				umus.MACVersionID = int(value.Int64)
			}
		case upgrademacupgradestrategy.FieldBeginDatetime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field begin_datetime", values[i])
			} else if value.Valid {
				umus.BeginDatetime = value.Time
			}
		case upgrademacupgradestrategy.FieldEndDatetime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_datetime", values[i])
			} else if value.Valid {
				umus.EndDatetime = value.Time
			}
		case upgrademacupgradestrategy.FieldUpgradeType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upgrade_type", values[i])
			} else if value.Valid {
				umus.UpgradeType = int32(value.Int64)
			}
		case upgrademacupgradestrategy.FieldPromptUpgradeContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_upgrade_content", values[i])
			} else if value.Valid {
				umus.PromptUpgradeContent = value.String
			}
		case upgrademacupgradestrategy.FieldUpgradeDevType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upgrade_dev_type", values[i])
			} else if value.Valid {
				umus.UpgradeDevType = int32(value.Int64)
			}
		case upgrademacupgradestrategy.FieldUpgradeDevData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upgrade_dev_data", values[i])
			} else if value.Valid {
				umus.UpgradeDevData = value.String
			}
		case upgrademacupgradestrategy.FieldUpgradeVersionType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upgrade_version_type", values[i])
			} else if value.Valid {
				umus.UpgradeVersionType = int32(value.Int64)
			}
		case upgrademacupgradestrategy.FieldUpgradeVersionData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upgrade_version_data", values[i])
			} else if value.Valid {
				umus.UpgradeVersionData = value.String
			}
		case upgrademacupgradestrategy.FieldIsGray:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field is_gray", values[i])
			} else if value.Valid {
				umus.IsGray = int32(value.Int64)
			}
		case upgrademacupgradestrategy.FieldGrayData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gray_data", values[i])
			} else if value.Valid {
				umus.GrayData = value.String
			}
		case upgrademacupgradestrategy.FieldIsFlowLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field is_flow_limit", values[i])
			} else if value.Valid {
				umus.IsFlowLimit = int32(value.Int64)
			}
		case upgrademacupgradestrategy.FieldFlowLimitData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field flow_limit_data", values[i])
			} else if value.Valid {
				umus.FlowLimitData = value.String
			}
		case upgrademacupgradestrategy.FieldIsDel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field is_del", values[i])
			} else if value.Valid {
				umus.IsDel = int32(value.Int64)
			}
		case upgrademacupgradestrategy.FieldCreateAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_at", values[i])
			} else if value.Valid {
				umus.CreateAt = value.Time
			}
		case upgrademacupgradestrategy.FieldUpdateAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_at", values[i])
			} else if value.Valid {
				umus.UpdateAt = value.Time
			}
		default:
			umus.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpgradeMacUpgradeStrategy.
// This includes values selected through modifiers, order, etc.
func (umus *UpgradeMacUpgradeStrategy) Value(name string) (ent.Value, error) {
	return umus.selectValues.Get(name)
}

// Update returns a builder for updating this UpgradeMacUpgradeStrategy.
// Note that you need to call UpgradeMacUpgradeStrategy.Unwrap() before calling this method if this UpgradeMacUpgradeStrategy
// was returned from a transaction, and the transaction was committed or rolled back.
func (umus *UpgradeMacUpgradeStrategy) Update() *UpgradeMacUpgradeStrategyUpdateOne {
	return NewUpgradeMacUpgradeStrategyClient(umus.config).UpdateOne(umus)
}

// Unwrap unwraps the UpgradeMacUpgradeStrategy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (umus *UpgradeMacUpgradeStrategy) Unwrap() *UpgradeMacUpgradeStrategy {
	_tx, ok := umus.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpgradeMacUpgradeStrategy is not a transactional entity")
	}
	umus.config.driver = _tx.drv
	return umus
}

// String implements the fmt.Stringer.
func (umus *UpgradeMacUpgradeStrategy) String() string {
	var builder strings.Builder
	builder.WriteString("UpgradeMacUpgradeStrategy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", umus.ID))
	builder.WriteString("company_id=")
	builder.WriteString(fmt.Sprintf("%v", umus.CompanyID))
	builder.WriteString(", ")
	builder.WriteString("enable=")
	builder.WriteString(fmt.Sprintf("%v", umus.Enable))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(umus.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(umus.Description)
	builder.WriteString(", ")
	builder.WriteString("mac_id=")
	builder.WriteString(fmt.Sprintf("%v", umus.MACID))
	builder.WriteString(", ")
	builder.WriteString("mac_version_id=")
	builder.WriteString(fmt.Sprintf("%v", umus.MACVersionID))
	builder.WriteString(", ")
	builder.WriteString("begin_datetime=")
	builder.WriteString(umus.BeginDatetime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("end_datetime=")
	builder.WriteString(umus.EndDatetime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("upgrade_type=")
	builder.WriteString(fmt.Sprintf("%v", umus.UpgradeType))
	builder.WriteString(", ")
	builder.WriteString("prompt_upgrade_content=")
	builder.WriteString(umus.PromptUpgradeContent)
	builder.WriteString(", ")
	builder.WriteString("upgrade_dev_type=")
	builder.WriteString(fmt.Sprintf("%v", umus.UpgradeDevType))
	builder.WriteString(", ")
	builder.WriteString("upgrade_dev_data=")
	builder.WriteString(umus.UpgradeDevData)
	builder.WriteString(", ")
	builder.WriteString("upgrade_version_type=")
	builder.WriteString(fmt.Sprintf("%v", umus.UpgradeVersionType))
	builder.WriteString(", ")
	builder.WriteString("upgrade_version_data=")
	builder.WriteString(umus.UpgradeVersionData)
	builder.WriteString(", ")
	builder.WriteString("is_gray=")
	builder.WriteString(fmt.Sprintf("%v", umus.IsGray))
	builder.WriteString(", ")
	builder.WriteString("gray_data=")
	builder.WriteString(umus.GrayData)
	builder.WriteString(", ")
	builder.WriteString("is_flow_limit=")
	builder.WriteString(fmt.Sprintf("%v", umus.IsFlowLimit))
	builder.WriteString(", ")
	builder.WriteString("flow_limit_data=")
	builder.WriteString(umus.FlowLimitData)
	builder.WriteString(", ")
	builder.WriteString("is_del=")
	builder.WriteString(fmt.Sprintf("%v", umus.IsDel))
	builder.WriteString(", ")
	builder.WriteString("create_at=")
	builder.WriteString(umus.CreateAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_at=")
	builder.WriteString(umus.UpdateAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UpgradeMacUpgradeStrategies is a parsable slice of UpgradeMacUpgradeStrategy.
type UpgradeMacUpgradeStrategies []*UpgradeMacUpgradeStrategy
