// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"upgradelink-admin-upgrade/server/ent/upgrademacupgradestrategygraystrategy"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeMacUpgradeStrategyGrayStrategyCreate is the builder for creating a UpgradeMacUpgradeStrategyGrayStrategy entity.
type UpgradeMacUpgradeStrategyGrayStrategyCreate struct {
	config
	mutation *UpgradeMacUpgradeStrategyGrayStrategyMutation
	hooks    []Hook
}

// SetEnable sets the "enable" field.
func (umusgsc *UpgradeMacUpgradeStrategyGrayStrategyCreate) SetEnable(i int32) *UpgradeMacUpgradeStrategyGrayStrategyCreate {
	umusgsc.mutation.SetEnable(i)
	return umusgsc
}

// SetBeginDatetime sets the "begin_datetime" field.
func (umusgsc *UpgradeMacUpgradeStrategyGrayStrategyCreate) SetBeginDatetime(t time.Time) *UpgradeMacUpgradeStrategyGrayStrategyCreate {
	umusgsc.mutation.SetBeginDatetime(t)
	return umusgsc
}

// SetEndDatetime sets the "end_datetime" field.
func (umusgsc *UpgradeMacUpgradeStrategyGrayStrategyCreate) SetEndDatetime(t time.Time) *UpgradeMacUpgradeStrategyGrayStrategyCreate {
	umusgsc.mutation.SetEndDatetime(t)
	return umusgsc
}

// SetLimit sets the "limit" field.
func (umusgsc *UpgradeMacUpgradeStrategyGrayStrategyCreate) SetLimit(i int) *UpgradeMacUpgradeStrategyGrayStrategyCreate {
	umusgsc.mutation.SetLimit(i)
	return umusgsc
}

// SetIsDel sets the "is_del" field.
func (umusgsc *UpgradeMacUpgradeStrategyGrayStrategyCreate) SetIsDel(i int32) *UpgradeMacUpgradeStrategyGrayStrategyCreate {
	umusgsc.mutation.SetIsDel(i)
	return umusgsc
}

// SetCreateAt sets the "create_at" field.
func (umusgsc *UpgradeMacUpgradeStrategyGrayStrategyCreate) SetCreateAt(t time.Time) *UpgradeMacUpgradeStrategyGrayStrategyCreate {
	umusgsc.mutation.SetCreateAt(t)
	return umusgsc
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (umusgsc *UpgradeMacUpgradeStrategyGrayStrategyCreate) SetNillableCreateAt(t *time.Time) *UpgradeMacUpgradeStrategyGrayStrategyCreate {
	if t != nil {
		umusgsc.SetCreateAt(*t)
	}
	return umusgsc
}

// SetUpdateAt sets the "update_at" field.
func (umusgsc *UpgradeMacUpgradeStrategyGrayStrategyCreate) SetUpdateAt(t time.Time) *UpgradeMacUpgradeStrategyGrayStrategyCreate {
	umusgsc.mutation.SetUpdateAt(t)
	return umusgsc
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (umusgsc *UpgradeMacUpgradeStrategyGrayStrategyCreate) SetNillableUpdateAt(t *time.Time) *UpgradeMacUpgradeStrategyGrayStrategyCreate {
	if t != nil {
		umusgsc.SetUpdateAt(*t)
	}
	return umusgsc
}

// SetID sets the "id" field.
func (umusgsc *UpgradeMacUpgradeStrategyGrayStrategyCreate) SetID(i int) *UpgradeMacUpgradeStrategyGrayStrategyCreate {
	umusgsc.mutation.SetID(i)
	return umusgsc
}

// Mutation returns the UpgradeMacUpgradeStrategyGrayStrategyMutation object of the builder.
func (umusgsc *UpgradeMacUpgradeStrategyGrayStrategyCreate) Mutation() *UpgradeMacUpgradeStrategyGrayStrategyMutation {
	return umusgsc.mutation
}

// Save creates the UpgradeMacUpgradeStrategyGrayStrategy in the database.
func (umusgsc *UpgradeMacUpgradeStrategyGrayStrategyCreate) Save(ctx context.Context) (*UpgradeMacUpgradeStrategyGrayStrategy, error) {
	return withHooks(ctx, umusgsc.sqlSave, umusgsc.mutation, umusgsc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (umusgsc *UpgradeMacUpgradeStrategyGrayStrategyCreate) SaveX(ctx context.Context) *UpgradeMacUpgradeStrategyGrayStrategy {
	v, err := umusgsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (umusgsc *UpgradeMacUpgradeStrategyGrayStrategyCreate) Exec(ctx context.Context) error {
	_, err := umusgsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (umusgsc *UpgradeMacUpgradeStrategyGrayStrategyCreate) ExecX(ctx context.Context) {
	if err := umusgsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (umusgsc *UpgradeMacUpgradeStrategyGrayStrategyCreate) check() error {
	if _, ok := umusgsc.mutation.Enable(); !ok {
		return &ValidationError{Name: "enable", err: errors.New(`ent: missing required field "UpgradeMacUpgradeStrategyGrayStrategy.enable"`)}
	}
	if _, ok := umusgsc.mutation.BeginDatetime(); !ok {
		return &ValidationError{Name: "begin_datetime", err: errors.New(`ent: missing required field "UpgradeMacUpgradeStrategyGrayStrategy.begin_datetime"`)}
	}
	if _, ok := umusgsc.mutation.EndDatetime(); !ok {
		return &ValidationError{Name: "end_datetime", err: errors.New(`ent: missing required field "UpgradeMacUpgradeStrategyGrayStrategy.end_datetime"`)}
	}
	if _, ok := umusgsc.mutation.Limit(); !ok {
		return &ValidationError{Name: "limit", err: errors.New(`ent: missing required field "UpgradeMacUpgradeStrategyGrayStrategy.limit"`)}
	}
	if _, ok := umusgsc.mutation.IsDel(); !ok {
		return &ValidationError{Name: "is_del", err: errors.New(`ent: missing required field "UpgradeMacUpgradeStrategyGrayStrategy.is_del"`)}
	}
	return nil
}

func (umusgsc *UpgradeMacUpgradeStrategyGrayStrategyCreate) sqlSave(ctx context.Context) (*UpgradeMacUpgradeStrategyGrayStrategy, error) {
	if err := umusgsc.check(); err != nil {
		return nil, err
	}
	_node, _spec := umusgsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, umusgsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	umusgsc.mutation.id = &_node.ID
	umusgsc.mutation.done = true
	return _node, nil
}

func (umusgsc *UpgradeMacUpgradeStrategyGrayStrategyCreate) createSpec() (*UpgradeMacUpgradeStrategyGrayStrategy, *sqlgraph.CreateSpec) {
	var (
		_node = &UpgradeMacUpgradeStrategyGrayStrategy{config: umusgsc.config}
		_spec = sqlgraph.NewCreateSpec(upgrademacupgradestrategygraystrategy.Table, sqlgraph.NewFieldSpec(upgrademacupgradestrategygraystrategy.FieldID, field.TypeInt))
	)
	if id, ok := umusgsc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := umusgsc.mutation.Enable(); ok {
		_spec.SetField(upgrademacupgradestrategygraystrategy.FieldEnable, field.TypeInt32, value)
		_node.Enable = value
	}
	if value, ok := umusgsc.mutation.BeginDatetime(); ok {
		_spec.SetField(upgrademacupgradestrategygraystrategy.FieldBeginDatetime, field.TypeTime, value)
		_node.BeginDatetime = value
	}
	if value, ok := umusgsc.mutation.EndDatetime(); ok {
		_spec.SetField(upgrademacupgradestrategygraystrategy.FieldEndDatetime, field.TypeTime, value)
		_node.EndDatetime = value
	}
	if value, ok := umusgsc.mutation.Limit(); ok {
		_spec.SetField(upgrademacupgradestrategygraystrategy.FieldLimit, field.TypeInt, value)
		_node.Limit = value
	}
	if value, ok := umusgsc.mutation.IsDel(); ok {
		_spec.SetField(upgrademacupgradestrategygraystrategy.FieldIsDel, field.TypeInt32, value)
		_node.IsDel = value
	}
	if value, ok := umusgsc.mutation.CreateAt(); ok {
		_spec.SetField(upgrademacupgradestrategygraystrategy.FieldCreateAt, field.TypeTime, value)
		_node.CreateAt = value
	}
	if value, ok := umusgsc.mutation.UpdateAt(); ok {
		_spec.SetField(upgrademacupgradestrategygraystrategy.FieldUpdateAt, field.TypeTime, value)
		_node.UpdateAt = value
	}
	return _node, _spec
}

// UpgradeMacUpgradeStrategyGrayStrategyCreateBulk is the builder for creating many UpgradeMacUpgradeStrategyGrayStrategy entities in bulk.
type UpgradeMacUpgradeStrategyGrayStrategyCreateBulk struct {
	config
	err      error
	builders []*UpgradeMacUpgradeStrategyGrayStrategyCreate
}

// Save creates the UpgradeMacUpgradeStrategyGrayStrategy entities in the database.
func (umusgscb *UpgradeMacUpgradeStrategyGrayStrategyCreateBulk) Save(ctx context.Context) ([]*UpgradeMacUpgradeStrategyGrayStrategy, error) {
	if umusgscb.err != nil {
		return nil, umusgscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(umusgscb.builders))
	nodes := make([]*UpgradeMacUpgradeStrategyGrayStrategy, len(umusgscb.builders))
	mutators := make([]Mutator, len(umusgscb.builders))
	for i := range umusgscb.builders {
		func(i int, root context.Context) {
			builder := umusgscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpgradeMacUpgradeStrategyGrayStrategyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, umusgscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, umusgscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, umusgscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (umusgscb *UpgradeMacUpgradeStrategyGrayStrategyCreateBulk) SaveX(ctx context.Context) []*UpgradeMacUpgradeStrategyGrayStrategy {
	v, err := umusgscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (umusgscb *UpgradeMacUpgradeStrategyGrayStrategyCreateBulk) Exec(ctx context.Context) error {
	_, err := umusgscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (umusgscb *UpgradeMacUpgradeStrategyGrayStrategyCreateBulk) ExecX(ctx context.Context) {
	if err := umusgscb.Exec(ctx); err != nil {
		panic(err)
	}
}
