// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"upgradelink-admin-upgrade/server/ent/predicate"
	"upgradelink-admin-upgrade/server/ent/upgradewinupgradestrategygraystrategy"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeWinUpgradeStrategyGrayStrategyUpdate is the builder for updating UpgradeWinUpgradeStrategyGrayStrategy entities.
type UpgradeWinUpgradeStrategyGrayStrategyUpdate struct {
	config
	hooks    []Hook
	mutation *UpgradeWinUpgradeStrategyGrayStrategyMutation
}

// Where appends a list predicates to the UpgradeWinUpgradeStrategyGrayStrategyUpdate builder.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) Where(ps ...predicate.UpgradeWinUpgradeStrategyGrayStrategy) *UpgradeWinUpgradeStrategyGrayStrategyUpdate {
	uwusgsu.mutation.Where(ps...)
	return uwusgsu
}

// SetEnable sets the "enable" field.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) SetEnable(i int32) *UpgradeWinUpgradeStrategyGrayStrategyUpdate {
	uwusgsu.mutation.ResetEnable()
	uwusgsu.mutation.SetEnable(i)
	return uwusgsu
}

// SetNillableEnable sets the "enable" field if the given value is not nil.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) SetNillableEnable(i *int32) *UpgradeWinUpgradeStrategyGrayStrategyUpdate {
	if i != nil {
		uwusgsu.SetEnable(*i)
	}
	return uwusgsu
}

// AddEnable adds i to the "enable" field.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) AddEnable(i int32) *UpgradeWinUpgradeStrategyGrayStrategyUpdate {
	uwusgsu.mutation.AddEnable(i)
	return uwusgsu
}

// SetBeginDatetime sets the "begin_datetime" field.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) SetBeginDatetime(t time.Time) *UpgradeWinUpgradeStrategyGrayStrategyUpdate {
	uwusgsu.mutation.SetBeginDatetime(t)
	return uwusgsu
}

// SetNillableBeginDatetime sets the "begin_datetime" field if the given value is not nil.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) SetNillableBeginDatetime(t *time.Time) *UpgradeWinUpgradeStrategyGrayStrategyUpdate {
	if t != nil {
		uwusgsu.SetBeginDatetime(*t)
	}
	return uwusgsu
}

// SetEndDatetime sets the "end_datetime" field.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) SetEndDatetime(t time.Time) *UpgradeWinUpgradeStrategyGrayStrategyUpdate {
	uwusgsu.mutation.SetEndDatetime(t)
	return uwusgsu
}

// SetNillableEndDatetime sets the "end_datetime" field if the given value is not nil.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) SetNillableEndDatetime(t *time.Time) *UpgradeWinUpgradeStrategyGrayStrategyUpdate {
	if t != nil {
		uwusgsu.SetEndDatetime(*t)
	}
	return uwusgsu
}

// SetLimit sets the "limit" field.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) SetLimit(i int) *UpgradeWinUpgradeStrategyGrayStrategyUpdate {
	uwusgsu.mutation.ResetLimit()
	uwusgsu.mutation.SetLimit(i)
	return uwusgsu
}

// SetNillableLimit sets the "limit" field if the given value is not nil.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) SetNillableLimit(i *int) *UpgradeWinUpgradeStrategyGrayStrategyUpdate {
	if i != nil {
		uwusgsu.SetLimit(*i)
	}
	return uwusgsu
}

// AddLimit adds i to the "limit" field.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) AddLimit(i int) *UpgradeWinUpgradeStrategyGrayStrategyUpdate {
	uwusgsu.mutation.AddLimit(i)
	return uwusgsu
}

// SetIsDel sets the "is_del" field.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) SetIsDel(i int32) *UpgradeWinUpgradeStrategyGrayStrategyUpdate {
	uwusgsu.mutation.ResetIsDel()
	uwusgsu.mutation.SetIsDel(i)
	return uwusgsu
}

// SetNillableIsDel sets the "is_del" field if the given value is not nil.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) SetNillableIsDel(i *int32) *UpgradeWinUpgradeStrategyGrayStrategyUpdate {
	if i != nil {
		uwusgsu.SetIsDel(*i)
	}
	return uwusgsu
}

// AddIsDel adds i to the "is_del" field.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) AddIsDel(i int32) *UpgradeWinUpgradeStrategyGrayStrategyUpdate {
	uwusgsu.mutation.AddIsDel(i)
	return uwusgsu
}

// SetCreateAt sets the "create_at" field.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) SetCreateAt(t time.Time) *UpgradeWinUpgradeStrategyGrayStrategyUpdate {
	uwusgsu.mutation.SetCreateAt(t)
	return uwusgsu
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) SetNillableCreateAt(t *time.Time) *UpgradeWinUpgradeStrategyGrayStrategyUpdate {
	if t != nil {
		uwusgsu.SetCreateAt(*t)
	}
	return uwusgsu
}

// ClearCreateAt clears the value of the "create_at" field.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) ClearCreateAt() *UpgradeWinUpgradeStrategyGrayStrategyUpdate {
	uwusgsu.mutation.ClearCreateAt()
	return uwusgsu
}

// SetUpdateAt sets the "update_at" field.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) SetUpdateAt(t time.Time) *UpgradeWinUpgradeStrategyGrayStrategyUpdate {
	uwusgsu.mutation.SetUpdateAt(t)
	return uwusgsu
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) SetNillableUpdateAt(t *time.Time) *UpgradeWinUpgradeStrategyGrayStrategyUpdate {
	if t != nil {
		uwusgsu.SetUpdateAt(*t)
	}
	return uwusgsu
}

// ClearUpdateAt clears the value of the "update_at" field.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) ClearUpdateAt() *UpgradeWinUpgradeStrategyGrayStrategyUpdate {
	uwusgsu.mutation.ClearUpdateAt()
	return uwusgsu
}

// Mutation returns the UpgradeWinUpgradeStrategyGrayStrategyMutation object of the builder.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) Mutation() *UpgradeWinUpgradeStrategyGrayStrategyMutation {
	return uwusgsu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, uwusgsu.sqlSave, uwusgsu.mutation, uwusgsu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) SaveX(ctx context.Context) int {
	affected, err := uwusgsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) Exec(ctx context.Context) error {
	_, err := uwusgsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) ExecX(ctx context.Context) {
	if err := uwusgsu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uwusgsu *UpgradeWinUpgradeStrategyGrayStrategyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(upgradewinupgradestrategygraystrategy.Table, upgradewinupgradestrategygraystrategy.Columns, sqlgraph.NewFieldSpec(upgradewinupgradestrategygraystrategy.FieldID, field.TypeInt))
	if ps := uwusgsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uwusgsu.mutation.Enable(); ok {
		_spec.SetField(upgradewinupgradestrategygraystrategy.FieldEnable, field.TypeInt32, value)
	}
	if value, ok := uwusgsu.mutation.AddedEnable(); ok {
		_spec.AddField(upgradewinupgradestrategygraystrategy.FieldEnable, field.TypeInt32, value)
	}
	if value, ok := uwusgsu.mutation.BeginDatetime(); ok {
		_spec.SetField(upgradewinupgradestrategygraystrategy.FieldBeginDatetime, field.TypeTime, value)
	}
	if value, ok := uwusgsu.mutation.EndDatetime(); ok {
		_spec.SetField(upgradewinupgradestrategygraystrategy.FieldEndDatetime, field.TypeTime, value)
	}
	if value, ok := uwusgsu.mutation.Limit(); ok {
		_spec.SetField(upgradewinupgradestrategygraystrategy.FieldLimit, field.TypeInt, value)
	}
	if value, ok := uwusgsu.mutation.AddedLimit(); ok {
		_spec.AddField(upgradewinupgradestrategygraystrategy.FieldLimit, field.TypeInt, value)
	}
	if value, ok := uwusgsu.mutation.IsDel(); ok {
		_spec.SetField(upgradewinupgradestrategygraystrategy.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := uwusgsu.mutation.AddedIsDel(); ok {
		_spec.AddField(upgradewinupgradestrategygraystrategy.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := uwusgsu.mutation.CreateAt(); ok {
		_spec.SetField(upgradewinupgradestrategygraystrategy.FieldCreateAt, field.TypeTime, value)
	}
	if uwusgsu.mutation.CreateAtCleared() {
		_spec.ClearField(upgradewinupgradestrategygraystrategy.FieldCreateAt, field.TypeTime)
	}
	if value, ok := uwusgsu.mutation.UpdateAt(); ok {
		_spec.SetField(upgradewinupgradestrategygraystrategy.FieldUpdateAt, field.TypeTime, value)
	}
	if uwusgsu.mutation.UpdateAtCleared() {
		_spec.ClearField(upgradewinupgradestrategygraystrategy.FieldUpdateAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uwusgsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upgradewinupgradestrategygraystrategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uwusgsu.mutation.done = true
	return n, nil
}

// UpgradeWinUpgradeStrategyGrayStrategyUpdateOne is the builder for updating a single UpgradeWinUpgradeStrategyGrayStrategy entity.
type UpgradeWinUpgradeStrategyGrayStrategyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpgradeWinUpgradeStrategyGrayStrategyMutation
}

// SetEnable sets the "enable" field.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) SetEnable(i int32) *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne {
	uwusgsuo.mutation.ResetEnable()
	uwusgsuo.mutation.SetEnable(i)
	return uwusgsuo
}

// SetNillableEnable sets the "enable" field if the given value is not nil.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) SetNillableEnable(i *int32) *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne {
	if i != nil {
		uwusgsuo.SetEnable(*i)
	}
	return uwusgsuo
}

// AddEnable adds i to the "enable" field.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) AddEnable(i int32) *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne {
	uwusgsuo.mutation.AddEnable(i)
	return uwusgsuo
}

// SetBeginDatetime sets the "begin_datetime" field.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) SetBeginDatetime(t time.Time) *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne {
	uwusgsuo.mutation.SetBeginDatetime(t)
	return uwusgsuo
}

// SetNillableBeginDatetime sets the "begin_datetime" field if the given value is not nil.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) SetNillableBeginDatetime(t *time.Time) *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne {
	if t != nil {
		uwusgsuo.SetBeginDatetime(*t)
	}
	return uwusgsuo
}

// SetEndDatetime sets the "end_datetime" field.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) SetEndDatetime(t time.Time) *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne {
	uwusgsuo.mutation.SetEndDatetime(t)
	return uwusgsuo
}

// SetNillableEndDatetime sets the "end_datetime" field if the given value is not nil.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) SetNillableEndDatetime(t *time.Time) *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne {
	if t != nil {
		uwusgsuo.SetEndDatetime(*t)
	}
	return uwusgsuo
}

// SetLimit sets the "limit" field.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) SetLimit(i int) *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne {
	uwusgsuo.mutation.ResetLimit()
	uwusgsuo.mutation.SetLimit(i)
	return uwusgsuo
}

// SetNillableLimit sets the "limit" field if the given value is not nil.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) SetNillableLimit(i *int) *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne {
	if i != nil {
		uwusgsuo.SetLimit(*i)
	}
	return uwusgsuo
}

// AddLimit adds i to the "limit" field.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) AddLimit(i int) *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne {
	uwusgsuo.mutation.AddLimit(i)
	return uwusgsuo
}

// SetIsDel sets the "is_del" field.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) SetIsDel(i int32) *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne {
	uwusgsuo.mutation.ResetIsDel()
	uwusgsuo.mutation.SetIsDel(i)
	return uwusgsuo
}

// SetNillableIsDel sets the "is_del" field if the given value is not nil.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) SetNillableIsDel(i *int32) *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne {
	if i != nil {
		uwusgsuo.SetIsDel(*i)
	}
	return uwusgsuo
}

// AddIsDel adds i to the "is_del" field.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) AddIsDel(i int32) *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne {
	uwusgsuo.mutation.AddIsDel(i)
	return uwusgsuo
}

// SetCreateAt sets the "create_at" field.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) SetCreateAt(t time.Time) *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne {
	uwusgsuo.mutation.SetCreateAt(t)
	return uwusgsuo
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) SetNillableCreateAt(t *time.Time) *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne {
	if t != nil {
		uwusgsuo.SetCreateAt(*t)
	}
	return uwusgsuo
}

// ClearCreateAt clears the value of the "create_at" field.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) ClearCreateAt() *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne {
	uwusgsuo.mutation.ClearCreateAt()
	return uwusgsuo
}

// SetUpdateAt sets the "update_at" field.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) SetUpdateAt(t time.Time) *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne {
	uwusgsuo.mutation.SetUpdateAt(t)
	return uwusgsuo
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) SetNillableUpdateAt(t *time.Time) *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne {
	if t != nil {
		uwusgsuo.SetUpdateAt(*t)
	}
	return uwusgsuo
}

// ClearUpdateAt clears the value of the "update_at" field.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) ClearUpdateAt() *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne {
	uwusgsuo.mutation.ClearUpdateAt()
	return uwusgsuo
}

// Mutation returns the UpgradeWinUpgradeStrategyGrayStrategyMutation object of the builder.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) Mutation() *UpgradeWinUpgradeStrategyGrayStrategyMutation {
	return uwusgsuo.mutation
}

// Where appends a list predicates to the UpgradeWinUpgradeStrategyGrayStrategyUpdate builder.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) Where(ps ...predicate.UpgradeWinUpgradeStrategyGrayStrategy) *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne {
	uwusgsuo.mutation.Where(ps...)
	return uwusgsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) Select(field string, fields ...string) *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne {
	uwusgsuo.fields = append([]string{field}, fields...)
	return uwusgsuo
}

// Save executes the query and returns the updated UpgradeWinUpgradeStrategyGrayStrategy entity.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) Save(ctx context.Context) (*UpgradeWinUpgradeStrategyGrayStrategy, error) {
	return withHooks(ctx, uwusgsuo.sqlSave, uwusgsuo.mutation, uwusgsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) SaveX(ctx context.Context) *UpgradeWinUpgradeStrategyGrayStrategy {
	node, err := uwusgsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) Exec(ctx context.Context) error {
	_, err := uwusgsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) ExecX(ctx context.Context) {
	if err := uwusgsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uwusgsuo *UpgradeWinUpgradeStrategyGrayStrategyUpdateOne) sqlSave(ctx context.Context) (_node *UpgradeWinUpgradeStrategyGrayStrategy, err error) {
	_spec := sqlgraph.NewUpdateSpec(upgradewinupgradestrategygraystrategy.Table, upgradewinupgradestrategygraystrategy.Columns, sqlgraph.NewFieldSpec(upgradewinupgradestrategygraystrategy.FieldID, field.TypeInt))
	id, ok := uwusgsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpgradeWinUpgradeStrategyGrayStrategy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uwusgsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upgradewinupgradestrategygraystrategy.FieldID)
		for _, f := range fields {
			if !upgradewinupgradestrategygraystrategy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upgradewinupgradestrategygraystrategy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uwusgsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uwusgsuo.mutation.Enable(); ok {
		_spec.SetField(upgradewinupgradestrategygraystrategy.FieldEnable, field.TypeInt32, value)
	}
	if value, ok := uwusgsuo.mutation.AddedEnable(); ok {
		_spec.AddField(upgradewinupgradestrategygraystrategy.FieldEnable, field.TypeInt32, value)
	}
	if value, ok := uwusgsuo.mutation.BeginDatetime(); ok {
		_spec.SetField(upgradewinupgradestrategygraystrategy.FieldBeginDatetime, field.TypeTime, value)
	}
	if value, ok := uwusgsuo.mutation.EndDatetime(); ok {
		_spec.SetField(upgradewinupgradestrategygraystrategy.FieldEndDatetime, field.TypeTime, value)
	}
	if value, ok := uwusgsuo.mutation.Limit(); ok {
		_spec.SetField(upgradewinupgradestrategygraystrategy.FieldLimit, field.TypeInt, value)
	}
	if value, ok := uwusgsuo.mutation.AddedLimit(); ok {
		_spec.AddField(upgradewinupgradestrategygraystrategy.FieldLimit, field.TypeInt, value)
	}
	if value, ok := uwusgsuo.mutation.IsDel(); ok {
		_spec.SetField(upgradewinupgradestrategygraystrategy.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := uwusgsuo.mutation.AddedIsDel(); ok {
		_spec.AddField(upgradewinupgradestrategygraystrategy.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := uwusgsuo.mutation.CreateAt(); ok {
		_spec.SetField(upgradewinupgradestrategygraystrategy.FieldCreateAt, field.TypeTime, value)
	}
	if uwusgsuo.mutation.CreateAtCleared() {
		_spec.ClearField(upgradewinupgradestrategygraystrategy.FieldCreateAt, field.TypeTime)
	}
	if value, ok := uwusgsuo.mutation.UpdateAt(); ok {
		_spec.SetField(upgradewinupgradestrategygraystrategy.FieldUpdateAt, field.TypeTime, value)
	}
	if uwusgsuo.mutation.UpdateAtCleared() {
		_spec.ClearField(upgradewinupgradestrategygraystrategy.FieldUpdateAt, field.TypeTime)
	}
	_node = &UpgradeWinUpgradeStrategyGrayStrategy{config: uwusgsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uwusgsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upgradewinupgradestrategygraystrategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uwusgsuo.mutation.done = true
	return _node, nil
}
