// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"upgradelink-admin-upgrade/server/ent/predicate"
	"upgradelink-admin-upgrade/server/ent/upgradelnxupgradestrategyflowlimitstrategy"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate is the builder for updating UpgradeLnxUpgradeStrategyFlowLimitStrategy entities.
type UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate struct {
	config
	hooks    []Hook
	mutation *UpgradeLnxUpgradeStrategyFlowLimitStrategyMutation
}

// Where appends a list predicates to the UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate builder.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) Where(ps ...predicate.UpgradeLnxUpgradeStrategyFlowLimitStrategy) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate {
	ulusflsu.mutation.Where(ps...)
	return ulusflsu
}

// SetEnable sets the "enable" field.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) SetEnable(i int32) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate {
	ulusflsu.mutation.ResetEnable()
	ulusflsu.mutation.SetEnable(i)
	return ulusflsu
}

// SetNillableEnable sets the "enable" field if the given value is not nil.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) SetNillableEnable(i *int32) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate {
	if i != nil {
		ulusflsu.SetEnable(*i)
	}
	return ulusflsu
}

// AddEnable adds i to the "enable" field.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) AddEnable(i int32) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate {
	ulusflsu.mutation.AddEnable(i)
	return ulusflsu
}

// SetBeginTime sets the "begin_time" field.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) SetBeginTime(s string) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate {
	ulusflsu.mutation.SetBeginTime(s)
	return ulusflsu
}

// SetNillableBeginTime sets the "begin_time" field if the given value is not nil.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) SetNillableBeginTime(s *string) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate {
	if s != nil {
		ulusflsu.SetBeginTime(*s)
	}
	return ulusflsu
}

// SetEndTime sets the "end_time" field.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) SetEndTime(s string) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate {
	ulusflsu.mutation.SetEndTime(s)
	return ulusflsu
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) SetNillableEndTime(s *string) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate {
	if s != nil {
		ulusflsu.SetEndTime(*s)
	}
	return ulusflsu
}

// SetDimension sets the "dimension" field.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) SetDimension(i int32) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate {
	ulusflsu.mutation.ResetDimension()
	ulusflsu.mutation.SetDimension(i)
	return ulusflsu
}

// SetNillableDimension sets the "dimension" field if the given value is not nil.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) SetNillableDimension(i *int32) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate {
	if i != nil {
		ulusflsu.SetDimension(*i)
	}
	return ulusflsu
}

// AddDimension adds i to the "dimension" field.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) AddDimension(i int32) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate {
	ulusflsu.mutation.AddDimension(i)
	return ulusflsu
}

// SetLimit sets the "limit" field.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) SetLimit(i int) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate {
	ulusflsu.mutation.ResetLimit()
	ulusflsu.mutation.SetLimit(i)
	return ulusflsu
}

// SetNillableLimit sets the "limit" field if the given value is not nil.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) SetNillableLimit(i *int) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate {
	if i != nil {
		ulusflsu.SetLimit(*i)
	}
	return ulusflsu
}

// AddLimit adds i to the "limit" field.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) AddLimit(i int) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate {
	ulusflsu.mutation.AddLimit(i)
	return ulusflsu
}

// SetIsDel sets the "is_del" field.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) SetIsDel(i int32) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate {
	ulusflsu.mutation.ResetIsDel()
	ulusflsu.mutation.SetIsDel(i)
	return ulusflsu
}

// SetNillableIsDel sets the "is_del" field if the given value is not nil.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) SetNillableIsDel(i *int32) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate {
	if i != nil {
		ulusflsu.SetIsDel(*i)
	}
	return ulusflsu
}

// AddIsDel adds i to the "is_del" field.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) AddIsDel(i int32) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate {
	ulusflsu.mutation.AddIsDel(i)
	return ulusflsu
}

// SetCreateAt sets the "create_at" field.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) SetCreateAt(t time.Time) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate {
	ulusflsu.mutation.SetCreateAt(t)
	return ulusflsu
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) SetNillableCreateAt(t *time.Time) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate {
	if t != nil {
		ulusflsu.SetCreateAt(*t)
	}
	return ulusflsu
}

// ClearCreateAt clears the value of the "create_at" field.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) ClearCreateAt() *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate {
	ulusflsu.mutation.ClearCreateAt()
	return ulusflsu
}

// SetUpdateAt sets the "update_at" field.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) SetUpdateAt(t time.Time) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate {
	ulusflsu.mutation.SetUpdateAt(t)
	return ulusflsu
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) SetNillableUpdateAt(t *time.Time) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate {
	if t != nil {
		ulusflsu.SetUpdateAt(*t)
	}
	return ulusflsu
}

// ClearUpdateAt clears the value of the "update_at" field.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) ClearUpdateAt() *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate {
	ulusflsu.mutation.ClearUpdateAt()
	return ulusflsu
}

// Mutation returns the UpgradeLnxUpgradeStrategyFlowLimitStrategyMutation object of the builder.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) Mutation() *UpgradeLnxUpgradeStrategyFlowLimitStrategyMutation {
	return ulusflsu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ulusflsu.sqlSave, ulusflsu.mutation, ulusflsu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) SaveX(ctx context.Context) int {
	affected, err := ulusflsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) Exec(ctx context.Context) error {
	_, err := ulusflsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) ExecX(ctx context.Context) {
	if err := ulusflsu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ulusflsu *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(upgradelnxupgradestrategyflowlimitstrategy.Table, upgradelnxupgradestrategyflowlimitstrategy.Columns, sqlgraph.NewFieldSpec(upgradelnxupgradestrategyflowlimitstrategy.FieldID, field.TypeInt))
	if ps := ulusflsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ulusflsu.mutation.Enable(); ok {
		_spec.SetField(upgradelnxupgradestrategyflowlimitstrategy.FieldEnable, field.TypeInt32, value)
	}
	if value, ok := ulusflsu.mutation.AddedEnable(); ok {
		_spec.AddField(upgradelnxupgradestrategyflowlimitstrategy.FieldEnable, field.TypeInt32, value)
	}
	if value, ok := ulusflsu.mutation.BeginTime(); ok {
		_spec.SetField(upgradelnxupgradestrategyflowlimitstrategy.FieldBeginTime, field.TypeString, value)
	}
	if value, ok := ulusflsu.mutation.EndTime(); ok {
		_spec.SetField(upgradelnxupgradestrategyflowlimitstrategy.FieldEndTime, field.TypeString, value)
	}
	if value, ok := ulusflsu.mutation.Dimension(); ok {
		_spec.SetField(upgradelnxupgradestrategyflowlimitstrategy.FieldDimension, field.TypeInt32, value)
	}
	if value, ok := ulusflsu.mutation.AddedDimension(); ok {
		_spec.AddField(upgradelnxupgradestrategyflowlimitstrategy.FieldDimension, field.TypeInt32, value)
	}
	if value, ok := ulusflsu.mutation.Limit(); ok {
		_spec.SetField(upgradelnxupgradestrategyflowlimitstrategy.FieldLimit, field.TypeInt, value)
	}
	if value, ok := ulusflsu.mutation.AddedLimit(); ok {
		_spec.AddField(upgradelnxupgradestrategyflowlimitstrategy.FieldLimit, field.TypeInt, value)
	}
	if value, ok := ulusflsu.mutation.IsDel(); ok {
		_spec.SetField(upgradelnxupgradestrategyflowlimitstrategy.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := ulusflsu.mutation.AddedIsDel(); ok {
		_spec.AddField(upgradelnxupgradestrategyflowlimitstrategy.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := ulusflsu.mutation.CreateAt(); ok {
		_spec.SetField(upgradelnxupgradestrategyflowlimitstrategy.FieldCreateAt, field.TypeTime, value)
	}
	if ulusflsu.mutation.CreateAtCleared() {
		_spec.ClearField(upgradelnxupgradestrategyflowlimitstrategy.FieldCreateAt, field.TypeTime)
	}
	if value, ok := ulusflsu.mutation.UpdateAt(); ok {
		_spec.SetField(upgradelnxupgradestrategyflowlimitstrategy.FieldUpdateAt, field.TypeTime, value)
	}
	if ulusflsu.mutation.UpdateAtCleared() {
		_spec.ClearField(upgradelnxupgradestrategyflowlimitstrategy.FieldUpdateAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ulusflsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upgradelnxupgradestrategyflowlimitstrategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ulusflsu.mutation.done = true
	return n, nil
}

// UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne is the builder for updating a single UpgradeLnxUpgradeStrategyFlowLimitStrategy entity.
type UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpgradeLnxUpgradeStrategyFlowLimitStrategyMutation
}

// SetEnable sets the "enable" field.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) SetEnable(i int32) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne {
	ulusflsuo.mutation.ResetEnable()
	ulusflsuo.mutation.SetEnable(i)
	return ulusflsuo
}

// SetNillableEnable sets the "enable" field if the given value is not nil.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) SetNillableEnable(i *int32) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne {
	if i != nil {
		ulusflsuo.SetEnable(*i)
	}
	return ulusflsuo
}

// AddEnable adds i to the "enable" field.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) AddEnable(i int32) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne {
	ulusflsuo.mutation.AddEnable(i)
	return ulusflsuo
}

// SetBeginTime sets the "begin_time" field.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) SetBeginTime(s string) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne {
	ulusflsuo.mutation.SetBeginTime(s)
	return ulusflsuo
}

// SetNillableBeginTime sets the "begin_time" field if the given value is not nil.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) SetNillableBeginTime(s *string) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne {
	if s != nil {
		ulusflsuo.SetBeginTime(*s)
	}
	return ulusflsuo
}

// SetEndTime sets the "end_time" field.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) SetEndTime(s string) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne {
	ulusflsuo.mutation.SetEndTime(s)
	return ulusflsuo
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) SetNillableEndTime(s *string) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne {
	if s != nil {
		ulusflsuo.SetEndTime(*s)
	}
	return ulusflsuo
}

// SetDimension sets the "dimension" field.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) SetDimension(i int32) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne {
	ulusflsuo.mutation.ResetDimension()
	ulusflsuo.mutation.SetDimension(i)
	return ulusflsuo
}

// SetNillableDimension sets the "dimension" field if the given value is not nil.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) SetNillableDimension(i *int32) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne {
	if i != nil {
		ulusflsuo.SetDimension(*i)
	}
	return ulusflsuo
}

// AddDimension adds i to the "dimension" field.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) AddDimension(i int32) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne {
	ulusflsuo.mutation.AddDimension(i)
	return ulusflsuo
}

// SetLimit sets the "limit" field.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) SetLimit(i int) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne {
	ulusflsuo.mutation.ResetLimit()
	ulusflsuo.mutation.SetLimit(i)
	return ulusflsuo
}

// SetNillableLimit sets the "limit" field if the given value is not nil.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) SetNillableLimit(i *int) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne {
	if i != nil {
		ulusflsuo.SetLimit(*i)
	}
	return ulusflsuo
}

// AddLimit adds i to the "limit" field.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) AddLimit(i int) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne {
	ulusflsuo.mutation.AddLimit(i)
	return ulusflsuo
}

// SetIsDel sets the "is_del" field.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) SetIsDel(i int32) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne {
	ulusflsuo.mutation.ResetIsDel()
	ulusflsuo.mutation.SetIsDel(i)
	return ulusflsuo
}

// SetNillableIsDel sets the "is_del" field if the given value is not nil.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) SetNillableIsDel(i *int32) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne {
	if i != nil {
		ulusflsuo.SetIsDel(*i)
	}
	return ulusflsuo
}

// AddIsDel adds i to the "is_del" field.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) AddIsDel(i int32) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne {
	ulusflsuo.mutation.AddIsDel(i)
	return ulusflsuo
}

// SetCreateAt sets the "create_at" field.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) SetCreateAt(t time.Time) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne {
	ulusflsuo.mutation.SetCreateAt(t)
	return ulusflsuo
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) SetNillableCreateAt(t *time.Time) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne {
	if t != nil {
		ulusflsuo.SetCreateAt(*t)
	}
	return ulusflsuo
}

// ClearCreateAt clears the value of the "create_at" field.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) ClearCreateAt() *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne {
	ulusflsuo.mutation.ClearCreateAt()
	return ulusflsuo
}

// SetUpdateAt sets the "update_at" field.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) SetUpdateAt(t time.Time) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne {
	ulusflsuo.mutation.SetUpdateAt(t)
	return ulusflsuo
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) SetNillableUpdateAt(t *time.Time) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne {
	if t != nil {
		ulusflsuo.SetUpdateAt(*t)
	}
	return ulusflsuo
}

// ClearUpdateAt clears the value of the "update_at" field.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) ClearUpdateAt() *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne {
	ulusflsuo.mutation.ClearUpdateAt()
	return ulusflsuo
}

// Mutation returns the UpgradeLnxUpgradeStrategyFlowLimitStrategyMutation object of the builder.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) Mutation() *UpgradeLnxUpgradeStrategyFlowLimitStrategyMutation {
	return ulusflsuo.mutation
}

// Where appends a list predicates to the UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdate builder.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) Where(ps ...predicate.UpgradeLnxUpgradeStrategyFlowLimitStrategy) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne {
	ulusflsuo.mutation.Where(ps...)
	return ulusflsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) Select(field string, fields ...string) *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne {
	ulusflsuo.fields = append([]string{field}, fields...)
	return ulusflsuo
}

// Save executes the query and returns the updated UpgradeLnxUpgradeStrategyFlowLimitStrategy entity.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) Save(ctx context.Context) (*UpgradeLnxUpgradeStrategyFlowLimitStrategy, error) {
	return withHooks(ctx, ulusflsuo.sqlSave, ulusflsuo.mutation, ulusflsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) SaveX(ctx context.Context) *UpgradeLnxUpgradeStrategyFlowLimitStrategy {
	node, err := ulusflsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) Exec(ctx context.Context) error {
	_, err := ulusflsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) ExecX(ctx context.Context) {
	if err := ulusflsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ulusflsuo *UpgradeLnxUpgradeStrategyFlowLimitStrategyUpdateOne) sqlSave(ctx context.Context) (_node *UpgradeLnxUpgradeStrategyFlowLimitStrategy, err error) {
	_spec := sqlgraph.NewUpdateSpec(upgradelnxupgradestrategyflowlimitstrategy.Table, upgradelnxupgradestrategyflowlimitstrategy.Columns, sqlgraph.NewFieldSpec(upgradelnxupgradestrategyflowlimitstrategy.FieldID, field.TypeInt))
	id, ok := ulusflsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpgradeLnxUpgradeStrategyFlowLimitStrategy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ulusflsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upgradelnxupgradestrategyflowlimitstrategy.FieldID)
		for _, f := range fields {
			if !upgradelnxupgradestrategyflowlimitstrategy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upgradelnxupgradestrategyflowlimitstrategy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ulusflsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ulusflsuo.mutation.Enable(); ok {
		_spec.SetField(upgradelnxupgradestrategyflowlimitstrategy.FieldEnable, field.TypeInt32, value)
	}
	if value, ok := ulusflsuo.mutation.AddedEnable(); ok {
		_spec.AddField(upgradelnxupgradestrategyflowlimitstrategy.FieldEnable, field.TypeInt32, value)
	}
	if value, ok := ulusflsuo.mutation.BeginTime(); ok {
		_spec.SetField(upgradelnxupgradestrategyflowlimitstrategy.FieldBeginTime, field.TypeString, value)
	}
	if value, ok := ulusflsuo.mutation.EndTime(); ok {
		_spec.SetField(upgradelnxupgradestrategyflowlimitstrategy.FieldEndTime, field.TypeString, value)
	}
	if value, ok := ulusflsuo.mutation.Dimension(); ok {
		_spec.SetField(upgradelnxupgradestrategyflowlimitstrategy.FieldDimension, field.TypeInt32, value)
	}
	if value, ok := ulusflsuo.mutation.AddedDimension(); ok {
		_spec.AddField(upgradelnxupgradestrategyflowlimitstrategy.FieldDimension, field.TypeInt32, value)
	}
	if value, ok := ulusflsuo.mutation.Limit(); ok {
		_spec.SetField(upgradelnxupgradestrategyflowlimitstrategy.FieldLimit, field.TypeInt, value)
	}
	if value, ok := ulusflsuo.mutation.AddedLimit(); ok {
		_spec.AddField(upgradelnxupgradestrategyflowlimitstrategy.FieldLimit, field.TypeInt, value)
	}
	if value, ok := ulusflsuo.mutation.IsDel(); ok {
		_spec.SetField(upgradelnxupgradestrategyflowlimitstrategy.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := ulusflsuo.mutation.AddedIsDel(); ok {
		_spec.AddField(upgradelnxupgradestrategyflowlimitstrategy.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := ulusflsuo.mutation.CreateAt(); ok {
		_spec.SetField(upgradelnxupgradestrategyflowlimitstrategy.FieldCreateAt, field.TypeTime, value)
	}
	if ulusflsuo.mutation.CreateAtCleared() {
		_spec.ClearField(upgradelnxupgradestrategyflowlimitstrategy.FieldCreateAt, field.TypeTime)
	}
	if value, ok := ulusflsuo.mutation.UpdateAt(); ok {
		_spec.SetField(upgradelnxupgradestrategyflowlimitstrategy.FieldUpdateAt, field.TypeTime, value)
	}
	if ulusflsuo.mutation.UpdateAtCleared() {
		_spec.ClearField(upgradelnxupgradestrategyflowlimitstrategy.FieldUpdateAt, field.TypeTime)
	}
	_node = &UpgradeLnxUpgradeStrategyFlowLimitStrategy{config: ulusflsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ulusflsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upgradelnxupgradestrategyflowlimitstrategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ulusflsuo.mutation.done = true
	return _node, nil
}
