// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"upgradelink-admin-upgrade/server/ent/upgradewinupgradestrategy"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeWinUpgradeStrategyCreate is the builder for creating a UpgradeWinUpgradeStrategy entity.
type UpgradeWinUpgradeStrategyCreate struct {
	config
	mutation *UpgradeWinUpgradeStrategyMutation
	hooks    []Hook
}

// SetCompanyID sets the "company_id" field.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SetCompanyID(i int) *UpgradeWinUpgradeStrategyCreate {
	uwusc.mutation.SetCompanyID(i)
	return uwusc
}

// SetEnable sets the "enable" field.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SetEnable(i int32) *UpgradeWinUpgradeStrategyCreate {
	uwusc.mutation.SetEnable(i)
	return uwusc
}

// SetName sets the "name" field.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SetName(s string) *UpgradeWinUpgradeStrategyCreate {
	uwusc.mutation.SetName(s)
	return uwusc
}

// SetDescription sets the "description" field.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SetDescription(s string) *UpgradeWinUpgradeStrategyCreate {
	uwusc.mutation.SetDescription(s)
	return uwusc
}

// SetWinID sets the "win_id" field.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SetWinID(i int) *UpgradeWinUpgradeStrategyCreate {
	uwusc.mutation.SetWinID(i)
	return uwusc
}

// SetWinVersionID sets the "win_version_id" field.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SetWinVersionID(i int) *UpgradeWinUpgradeStrategyCreate {
	uwusc.mutation.SetWinVersionID(i)
	return uwusc
}

// SetBeginDatetime sets the "begin_datetime" field.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SetBeginDatetime(t time.Time) *UpgradeWinUpgradeStrategyCreate {
	uwusc.mutation.SetBeginDatetime(t)
	return uwusc
}

// SetEndDatetime sets the "end_datetime" field.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SetEndDatetime(t time.Time) *UpgradeWinUpgradeStrategyCreate {
	uwusc.mutation.SetEndDatetime(t)
	return uwusc
}

// SetUpgradeType sets the "upgrade_type" field.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SetUpgradeType(i int32) *UpgradeWinUpgradeStrategyCreate {
	uwusc.mutation.SetUpgradeType(i)
	return uwusc
}

// SetPromptUpgradeContent sets the "prompt_upgrade_content" field.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SetPromptUpgradeContent(s string) *UpgradeWinUpgradeStrategyCreate {
	uwusc.mutation.SetPromptUpgradeContent(s)
	return uwusc
}

// SetUpgradeDevType sets the "upgrade_dev_type" field.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SetUpgradeDevType(i int32) *UpgradeWinUpgradeStrategyCreate {
	uwusc.mutation.SetUpgradeDevType(i)
	return uwusc
}

// SetUpgradeDevData sets the "upgrade_dev_data" field.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SetUpgradeDevData(s string) *UpgradeWinUpgradeStrategyCreate {
	uwusc.mutation.SetUpgradeDevData(s)
	return uwusc
}

// SetUpgradeVersionType sets the "upgrade_version_type" field.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SetUpgradeVersionType(i int32) *UpgradeWinUpgradeStrategyCreate {
	uwusc.mutation.SetUpgradeVersionType(i)
	return uwusc
}

// SetUpgradeVersionData sets the "upgrade_version_data" field.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SetUpgradeVersionData(s string) *UpgradeWinUpgradeStrategyCreate {
	uwusc.mutation.SetUpgradeVersionData(s)
	return uwusc
}

// SetIsGray sets the "is_gray" field.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SetIsGray(i int32) *UpgradeWinUpgradeStrategyCreate {
	uwusc.mutation.SetIsGray(i)
	return uwusc
}

// SetGrayData sets the "gray_data" field.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SetGrayData(s string) *UpgradeWinUpgradeStrategyCreate {
	uwusc.mutation.SetGrayData(s)
	return uwusc
}

// SetIsFlowLimit sets the "is_flow_limit" field.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SetIsFlowLimit(i int32) *UpgradeWinUpgradeStrategyCreate {
	uwusc.mutation.SetIsFlowLimit(i)
	return uwusc
}

// SetFlowLimitData sets the "flow_limit_data" field.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SetFlowLimitData(s string) *UpgradeWinUpgradeStrategyCreate {
	uwusc.mutation.SetFlowLimitData(s)
	return uwusc
}

// SetIsDel sets the "is_del" field.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SetIsDel(i int32) *UpgradeWinUpgradeStrategyCreate {
	uwusc.mutation.SetIsDel(i)
	return uwusc
}

// SetCreateAt sets the "create_at" field.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SetCreateAt(t time.Time) *UpgradeWinUpgradeStrategyCreate {
	uwusc.mutation.SetCreateAt(t)
	return uwusc
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SetNillableCreateAt(t *time.Time) *UpgradeWinUpgradeStrategyCreate {
	if t != nil {
		uwusc.SetCreateAt(*t)
	}
	return uwusc
}

// SetUpdateAt sets the "update_at" field.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SetUpdateAt(t time.Time) *UpgradeWinUpgradeStrategyCreate {
	uwusc.mutation.SetUpdateAt(t)
	return uwusc
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SetNillableUpdateAt(t *time.Time) *UpgradeWinUpgradeStrategyCreate {
	if t != nil {
		uwusc.SetUpdateAt(*t)
	}
	return uwusc
}

// SetID sets the "id" field.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SetID(i int) *UpgradeWinUpgradeStrategyCreate {
	uwusc.mutation.SetID(i)
	return uwusc
}

// Mutation returns the UpgradeWinUpgradeStrategyMutation object of the builder.
func (uwusc *UpgradeWinUpgradeStrategyCreate) Mutation() *UpgradeWinUpgradeStrategyMutation {
	return uwusc.mutation
}

// Save creates the UpgradeWinUpgradeStrategy in the database.
func (uwusc *UpgradeWinUpgradeStrategyCreate) Save(ctx context.Context) (*UpgradeWinUpgradeStrategy, error) {
	return withHooks(ctx, uwusc.sqlSave, uwusc.mutation, uwusc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (uwusc *UpgradeWinUpgradeStrategyCreate) SaveX(ctx context.Context) *UpgradeWinUpgradeStrategy {
	v, err := uwusc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uwusc *UpgradeWinUpgradeStrategyCreate) Exec(ctx context.Context) error {
	_, err := uwusc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uwusc *UpgradeWinUpgradeStrategyCreate) ExecX(ctx context.Context) {
	if err := uwusc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uwusc *UpgradeWinUpgradeStrategyCreate) check() error {
	if _, ok := uwusc.mutation.CompanyID(); !ok {
		return &ValidationError{Name: "company_id", err: errors.New(`ent: missing required field "UpgradeWinUpgradeStrategy.company_id"`)}
	}
	if _, ok := uwusc.mutation.Enable(); !ok {
		return &ValidationError{Name: "enable", err: errors.New(`ent: missing required field "UpgradeWinUpgradeStrategy.enable"`)}
	}
	if _, ok := uwusc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "UpgradeWinUpgradeStrategy.name"`)}
	}
	if _, ok := uwusc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "UpgradeWinUpgradeStrategy.description"`)}
	}
	if _, ok := uwusc.mutation.WinID(); !ok {
		return &ValidationError{Name: "win_id", err: errors.New(`ent: missing required field "UpgradeWinUpgradeStrategy.win_id"`)}
	}
	if _, ok := uwusc.mutation.WinVersionID(); !ok {
		return &ValidationError{Name: "win_version_id", err: errors.New(`ent: missing required field "UpgradeWinUpgradeStrategy.win_version_id"`)}
	}
	if _, ok := uwusc.mutation.BeginDatetime(); !ok {
		return &ValidationError{Name: "begin_datetime", err: errors.New(`ent: missing required field "UpgradeWinUpgradeStrategy.begin_datetime"`)}
	}
	if _, ok := uwusc.mutation.EndDatetime(); !ok {
		return &ValidationError{Name: "end_datetime", err: errors.New(`ent: missing required field "UpgradeWinUpgradeStrategy.end_datetime"`)}
	}
	if _, ok := uwusc.mutation.UpgradeType(); !ok {
		return &ValidationError{Name: "upgrade_type", err: errors.New(`ent: missing required field "UpgradeWinUpgradeStrategy.upgrade_type"`)}
	}
	if _, ok := uwusc.mutation.PromptUpgradeContent(); !ok {
		return &ValidationError{Name: "prompt_upgrade_content", err: errors.New(`ent: missing required field "UpgradeWinUpgradeStrategy.prompt_upgrade_content"`)}
	}
	if _, ok := uwusc.mutation.UpgradeDevType(); !ok {
		return &ValidationError{Name: "upgrade_dev_type", err: errors.New(`ent: missing required field "UpgradeWinUpgradeStrategy.upgrade_dev_type"`)}
	}
	if _, ok := uwusc.mutation.UpgradeDevData(); !ok {
		return &ValidationError{Name: "upgrade_dev_data", err: errors.New(`ent: missing required field "UpgradeWinUpgradeStrategy.upgrade_dev_data"`)}
	}
	if _, ok := uwusc.mutation.UpgradeVersionType(); !ok {
		return &ValidationError{Name: "upgrade_version_type", err: errors.New(`ent: missing required field "UpgradeWinUpgradeStrategy.upgrade_version_type"`)}
	}
	if _, ok := uwusc.mutation.UpgradeVersionData(); !ok {
		return &ValidationError{Name: "upgrade_version_data", err: errors.New(`ent: missing required field "UpgradeWinUpgradeStrategy.upgrade_version_data"`)}
	}
	if _, ok := uwusc.mutation.IsGray(); !ok {
		return &ValidationError{Name: "is_gray", err: errors.New(`ent: missing required field "UpgradeWinUpgradeStrategy.is_gray"`)}
	}
	if _, ok := uwusc.mutation.GrayData(); !ok {
		return &ValidationError{Name: "gray_data", err: errors.New(`ent: missing required field "UpgradeWinUpgradeStrategy.gray_data"`)}
	}
	if _, ok := uwusc.mutation.IsFlowLimit(); !ok {
		return &ValidationError{Name: "is_flow_limit", err: errors.New(`ent: missing required field "UpgradeWinUpgradeStrategy.is_flow_limit"`)}
	}
	if _, ok := uwusc.mutation.FlowLimitData(); !ok {
		return &ValidationError{Name: "flow_limit_data", err: errors.New(`ent: missing required field "UpgradeWinUpgradeStrategy.flow_limit_data"`)}
	}
	if _, ok := uwusc.mutation.IsDel(); !ok {
		return &ValidationError{Name: "is_del", err: errors.New(`ent: missing required field "UpgradeWinUpgradeStrategy.is_del"`)}
	}
	return nil
}

func (uwusc *UpgradeWinUpgradeStrategyCreate) sqlSave(ctx context.Context) (*UpgradeWinUpgradeStrategy, error) {
	if err := uwusc.check(); err != nil {
		return nil, err
	}
	_node, _spec := uwusc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uwusc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	uwusc.mutation.id = &_node.ID
	uwusc.mutation.done = true
	return _node, nil
}

func (uwusc *UpgradeWinUpgradeStrategyCreate) createSpec() (*UpgradeWinUpgradeStrategy, *sqlgraph.CreateSpec) {
	var (
		_node = &UpgradeWinUpgradeStrategy{config: uwusc.config}
		_spec = sqlgraph.NewCreateSpec(upgradewinupgradestrategy.Table, sqlgraph.NewFieldSpec(upgradewinupgradestrategy.FieldID, field.TypeInt))
	)
	if id, ok := uwusc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := uwusc.mutation.CompanyID(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldCompanyID, field.TypeInt, value)
		_node.CompanyID = value
	}
	if value, ok := uwusc.mutation.Enable(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldEnable, field.TypeInt32, value)
		_node.Enable = value
	}
	if value, ok := uwusc.mutation.Name(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := uwusc.mutation.Description(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := uwusc.mutation.WinID(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldWinID, field.TypeInt, value)
		_node.WinID = value
	}
	if value, ok := uwusc.mutation.WinVersionID(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldWinVersionID, field.TypeInt, value)
		_node.WinVersionID = value
	}
	if value, ok := uwusc.mutation.BeginDatetime(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldBeginDatetime, field.TypeTime, value)
		_node.BeginDatetime = value
	}
	if value, ok := uwusc.mutation.EndDatetime(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldEndDatetime, field.TypeTime, value)
		_node.EndDatetime = value
	}
	if value, ok := uwusc.mutation.UpgradeType(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldUpgradeType, field.TypeInt32, value)
		_node.UpgradeType = value
	}
	if value, ok := uwusc.mutation.PromptUpgradeContent(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldPromptUpgradeContent, field.TypeString, value)
		_node.PromptUpgradeContent = value
	}
	if value, ok := uwusc.mutation.UpgradeDevType(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldUpgradeDevType, field.TypeInt32, value)
		_node.UpgradeDevType = value
	}
	if value, ok := uwusc.mutation.UpgradeDevData(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldUpgradeDevData, field.TypeString, value)
		_node.UpgradeDevData = value
	}
	if value, ok := uwusc.mutation.UpgradeVersionType(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldUpgradeVersionType, field.TypeInt32, value)
		_node.UpgradeVersionType = value
	}
	if value, ok := uwusc.mutation.UpgradeVersionData(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldUpgradeVersionData, field.TypeString, value)
		_node.UpgradeVersionData = value
	}
	if value, ok := uwusc.mutation.IsGray(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldIsGray, field.TypeInt32, value)
		_node.IsGray = value
	}
	if value, ok := uwusc.mutation.GrayData(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldGrayData, field.TypeString, value)
		_node.GrayData = value
	}
	if value, ok := uwusc.mutation.IsFlowLimit(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldIsFlowLimit, field.TypeInt32, value)
		_node.IsFlowLimit = value
	}
	if value, ok := uwusc.mutation.FlowLimitData(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldFlowLimitData, field.TypeString, value)
		_node.FlowLimitData = value
	}
	if value, ok := uwusc.mutation.IsDel(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldIsDel, field.TypeInt32, value)
		_node.IsDel = value
	}
	if value, ok := uwusc.mutation.CreateAt(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldCreateAt, field.TypeTime, value)
		_node.CreateAt = value
	}
	if value, ok := uwusc.mutation.UpdateAt(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldUpdateAt, field.TypeTime, value)
		_node.UpdateAt = value
	}
	return _node, _spec
}

// UpgradeWinUpgradeStrategyCreateBulk is the builder for creating many UpgradeWinUpgradeStrategy entities in bulk.
type UpgradeWinUpgradeStrategyCreateBulk struct {
	config
	err      error
	builders []*UpgradeWinUpgradeStrategyCreate
}

// Save creates the UpgradeWinUpgradeStrategy entities in the database.
func (uwuscb *UpgradeWinUpgradeStrategyCreateBulk) Save(ctx context.Context) ([]*UpgradeWinUpgradeStrategy, error) {
	if uwuscb.err != nil {
		return nil, uwuscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(uwuscb.builders))
	nodes := make([]*UpgradeWinUpgradeStrategy, len(uwuscb.builders))
	mutators := make([]Mutator, len(uwuscb.builders))
	for i := range uwuscb.builders {
		func(i int, root context.Context) {
			builder := uwuscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpgradeWinUpgradeStrategyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uwuscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uwuscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uwuscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uwuscb *UpgradeWinUpgradeStrategyCreateBulk) SaveX(ctx context.Context) []*UpgradeWinUpgradeStrategy {
	v, err := uwuscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uwuscb *UpgradeWinUpgradeStrategyCreateBulk) Exec(ctx context.Context) error {
	_, err := uwuscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uwuscb *UpgradeWinUpgradeStrategyCreateBulk) ExecX(ctx context.Context) {
	if err := uwuscb.Exec(ctx); err != nil {
		panic(err)
	}
}
