// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"upgradelink-admin-upgrade/server/ent/predicate"
	"upgradelink-admin-upgrade/server/ent/upgradewinversion"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeWinVersionDelete is the builder for deleting a UpgradeWinVersion entity.
type UpgradeWinVersionDelete struct {
	config
	hooks    []Hook
	mutation *UpgradeWinVersionMutation
}

// Where appends a list predicates to the UpgradeWinVersionDelete builder.
func (uwvd *UpgradeWinVersionDelete) Where(ps ...predicate.UpgradeWinVersion) *UpgradeWinVersionDelete {
	uwvd.mutation.Where(ps...)
	return uwvd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uwvd *UpgradeWinVersionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, uwvd.sqlExec, uwvd.mutation, uwvd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (uwvd *UpgradeWinVersionDelete) ExecX(ctx context.Context) int {
	n, err := uwvd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uwvd *UpgradeWinVersionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(upgradewinversion.Table, sqlgraph.NewFieldSpec(upgradewinversion.FieldID, field.TypeInt))
	if ps := uwvd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, uwvd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	uwvd.mutation.done = true
	return affected, err
}

// UpgradeWinVersionDeleteOne is the builder for deleting a single UpgradeWinVersion entity.
type UpgradeWinVersionDeleteOne struct {
	uwvd *UpgradeWinVersionDelete
}

// Where appends a list predicates to the UpgradeWinVersionDelete builder.
func (uwvdo *UpgradeWinVersionDeleteOne) Where(ps ...predicate.UpgradeWinVersion) *UpgradeWinVersionDeleteOne {
	uwvdo.uwvd.mutation.Where(ps...)
	return uwvdo
}

// Exec executes the deletion query.
func (uwvdo *UpgradeWinVersionDeleteOne) Exec(ctx context.Context) error {
	n, err := uwvdo.uwvd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{upgradewinversion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uwvdo *UpgradeWinVersionDeleteOne) ExecX(ctx context.Context) {
	if err := uwvdo.Exec(ctx); err != nil {
		panic(err)
	}
}
