// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"upgradelink-admin-upgrade/server/ent/predicate"
	"upgradelink-admin-upgrade/server/ent/upgradewin"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeWinQuery is the builder for querying UpgradeWin entities.
type UpgradeWinQuery struct {
	config
	ctx        *QueryContext
	order      []upgradewin.OrderOption
	inters     []Interceptor
	predicates []predicate.UpgradeWin
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UpgradeWinQuery builder.
func (uwq *UpgradeWinQuery) Where(ps ...predicate.UpgradeWin) *UpgradeWinQuery {
	uwq.predicates = append(uwq.predicates, ps...)
	return uwq
}

// Limit the number of records to be returned by this query.
func (uwq *UpgradeWinQuery) Limit(limit int) *UpgradeWinQuery {
	uwq.ctx.Limit = &limit
	return uwq
}

// Offset to start from.
func (uwq *UpgradeWinQuery) Offset(offset int) *UpgradeWinQuery {
	uwq.ctx.Offset = &offset
	return uwq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uwq *UpgradeWinQuery) Unique(unique bool) *UpgradeWinQuery {
	uwq.ctx.Unique = &unique
	return uwq
}

// Order specifies how the records should be ordered.
func (uwq *UpgradeWinQuery) Order(o ...upgradewin.OrderOption) *UpgradeWinQuery {
	uwq.order = append(uwq.order, o...)
	return uwq
}

// First returns the first UpgradeWin entity from the query.
// Returns a *NotFoundError when no UpgradeWin was found.
func (uwq *UpgradeWinQuery) First(ctx context.Context) (*UpgradeWin, error) {
	nodes, err := uwq.Limit(1).All(setContextOp(ctx, uwq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{upgradewin.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uwq *UpgradeWinQuery) FirstX(ctx context.Context) *UpgradeWin {
	node, err := uwq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UpgradeWin ID from the query.
// Returns a *NotFoundError when no UpgradeWin ID was found.
func (uwq *UpgradeWinQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uwq.Limit(1).IDs(setContextOp(ctx, uwq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{upgradewin.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uwq *UpgradeWinQuery) FirstIDX(ctx context.Context) int {
	id, err := uwq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UpgradeWin entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UpgradeWin entity is found.
// Returns a *NotFoundError when no UpgradeWin entities are found.
func (uwq *UpgradeWinQuery) Only(ctx context.Context) (*UpgradeWin, error) {
	nodes, err := uwq.Limit(2).All(setContextOp(ctx, uwq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{upgradewin.Label}
	default:
		return nil, &NotSingularError{upgradewin.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uwq *UpgradeWinQuery) OnlyX(ctx context.Context) *UpgradeWin {
	node, err := uwq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UpgradeWin ID in the query.
// Returns a *NotSingularError when more than one UpgradeWin ID is found.
// Returns a *NotFoundError when no entities are found.
func (uwq *UpgradeWinQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uwq.Limit(2).IDs(setContextOp(ctx, uwq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{upgradewin.Label}
	default:
		err = &NotSingularError{upgradewin.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uwq *UpgradeWinQuery) OnlyIDX(ctx context.Context) int {
	id, err := uwq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UpgradeWins.
func (uwq *UpgradeWinQuery) All(ctx context.Context) ([]*UpgradeWin, error) {
	ctx = setContextOp(ctx, uwq.ctx, ent.OpQueryAll)
	if err := uwq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UpgradeWin, *UpgradeWinQuery]()
	return withInterceptors[[]*UpgradeWin](ctx, uwq, qr, uwq.inters)
}

// AllX is like All, but panics if an error occurs.
func (uwq *UpgradeWinQuery) AllX(ctx context.Context) []*UpgradeWin {
	nodes, err := uwq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UpgradeWin IDs.
func (uwq *UpgradeWinQuery) IDs(ctx context.Context) (ids []int, err error) {
	if uwq.ctx.Unique == nil && uwq.path != nil {
		uwq.Unique(true)
	}
	ctx = setContextOp(ctx, uwq.ctx, ent.OpQueryIDs)
	if err = uwq.Select(upgradewin.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uwq *UpgradeWinQuery) IDsX(ctx context.Context) []int {
	ids, err := uwq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uwq *UpgradeWinQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, uwq.ctx, ent.OpQueryCount)
	if err := uwq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, uwq, querierCount[*UpgradeWinQuery](), uwq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (uwq *UpgradeWinQuery) CountX(ctx context.Context) int {
	count, err := uwq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uwq *UpgradeWinQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, uwq.ctx, ent.OpQueryExist)
	switch _, err := uwq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (uwq *UpgradeWinQuery) ExistX(ctx context.Context) bool {
	exist, err := uwq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UpgradeWinQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uwq *UpgradeWinQuery) Clone() *UpgradeWinQuery {
	if uwq == nil {
		return nil
	}
	return &UpgradeWinQuery{
		config:     uwq.config,
		ctx:        uwq.ctx.Clone(),
		order:      append([]upgradewin.OrderOption{}, uwq.order...),
		inters:     append([]Interceptor{}, uwq.inters...),
		predicates: append([]predicate.UpgradeWin{}, uwq.predicates...),
		// clone intermediate query.
		sql:  uwq.sql.Clone(),
		path: uwq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CompanyID int `json:"company_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UpgradeWin.Query().
//		GroupBy(upgradewin.FieldCompanyID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (uwq *UpgradeWinQuery) GroupBy(field string, fields ...string) *UpgradeWinGroupBy {
	uwq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UpgradeWinGroupBy{build: uwq}
	grbuild.flds = &uwq.ctx.Fields
	grbuild.label = upgradewin.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CompanyID int `json:"company_id,omitempty"`
//	}
//
//	client.UpgradeWin.Query().
//		Select(upgradewin.FieldCompanyID).
//		Scan(ctx, &v)
func (uwq *UpgradeWinQuery) Select(fields ...string) *UpgradeWinSelect {
	uwq.ctx.Fields = append(uwq.ctx.Fields, fields...)
	sbuild := &UpgradeWinSelect{UpgradeWinQuery: uwq}
	sbuild.label = upgradewin.Label
	sbuild.flds, sbuild.scan = &uwq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UpgradeWinSelect configured with the given aggregations.
func (uwq *UpgradeWinQuery) Aggregate(fns ...AggregateFunc) *UpgradeWinSelect {
	return uwq.Select().Aggregate(fns...)
}

func (uwq *UpgradeWinQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range uwq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, uwq); err != nil {
				return err
			}
		}
	}
	for _, f := range uwq.ctx.Fields {
		if !upgradewin.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uwq.path != nil {
		prev, err := uwq.path(ctx)
		if err != nil {
			return err
		}
		uwq.sql = prev
	}
	return nil
}

func (uwq *UpgradeWinQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UpgradeWin, error) {
	var (
		nodes = []*UpgradeWin{}
		_spec = uwq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UpgradeWin).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UpgradeWin{config: uwq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uwq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (uwq *UpgradeWinQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uwq.querySpec()
	_spec.Node.Columns = uwq.ctx.Fields
	if len(uwq.ctx.Fields) > 0 {
		_spec.Unique = uwq.ctx.Unique != nil && *uwq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, uwq.driver, _spec)
}

func (uwq *UpgradeWinQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(upgradewin.Table, upgradewin.Columns, sqlgraph.NewFieldSpec(upgradewin.FieldID, field.TypeInt))
	_spec.From = uwq.sql
	if unique := uwq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if uwq.path != nil {
		_spec.Unique = true
	}
	if fields := uwq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upgradewin.FieldID)
		for i := range fields {
			if fields[i] != upgradewin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uwq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uwq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uwq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uwq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uwq *UpgradeWinQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uwq.driver.Dialect())
	t1 := builder.Table(upgradewin.Table)
	columns := uwq.ctx.Fields
	if len(columns) == 0 {
		columns = upgradewin.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uwq.sql != nil {
		selector = uwq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uwq.ctx.Unique != nil && *uwq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range uwq.predicates {
		p(selector)
	}
	for _, p := range uwq.order {
		p(selector)
	}
	if offset := uwq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uwq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UpgradeWinGroupBy is the group-by builder for UpgradeWin entities.
type UpgradeWinGroupBy struct {
	selector
	build *UpgradeWinQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uwgb *UpgradeWinGroupBy) Aggregate(fns ...AggregateFunc) *UpgradeWinGroupBy {
	uwgb.fns = append(uwgb.fns, fns...)
	return uwgb
}

// Scan applies the selector query and scans the result into the given value.
func (uwgb *UpgradeWinGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uwgb.build.ctx, ent.OpQueryGroupBy)
	if err := uwgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpgradeWinQuery, *UpgradeWinGroupBy](ctx, uwgb.build, uwgb, uwgb.build.inters, v)
}

func (uwgb *UpgradeWinGroupBy) sqlScan(ctx context.Context, root *UpgradeWinQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(uwgb.fns))
	for _, fn := range uwgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*uwgb.flds)+len(uwgb.fns))
		for _, f := range *uwgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*uwgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uwgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UpgradeWinSelect is the builder for selecting fields of UpgradeWin entities.
type UpgradeWinSelect struct {
	*UpgradeWinQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uws *UpgradeWinSelect) Aggregate(fns ...AggregateFunc) *UpgradeWinSelect {
	uws.fns = append(uws.fns, fns...)
	return uws
}

// Scan applies the selector query and scans the result into the given value.
func (uws *UpgradeWinSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uws.ctx, ent.OpQuerySelect)
	if err := uws.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpgradeWinQuery, *UpgradeWinSelect](ctx, uws.UpgradeWinQuery, uws, uws.inters, v)
}

func (uws *UpgradeWinSelect) sqlScan(ctx context.Context, root *UpgradeWinQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(uws.fns))
	for _, fn := range uws.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*uws.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uws.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
