// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"upgradelink-admin-upgrade/server/ent/predicate"
	"upgradelink-admin-upgrade/server/ent/upgradewinupgradestrategyflowlimitstrategy"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeWinUpgradeStrategyFlowLimitStrategyQuery is the builder for querying UpgradeWinUpgradeStrategyFlowLimitStrategy entities.
type UpgradeWinUpgradeStrategyFlowLimitStrategyQuery struct {
	config
	ctx        *QueryContext
	order      []upgradewinupgradestrategyflowlimitstrategy.OrderOption
	inters     []Interceptor
	predicates []predicate.UpgradeWinUpgradeStrategyFlowLimitStrategy
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UpgradeWinUpgradeStrategyFlowLimitStrategyQuery builder.
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) Where(ps ...predicate.UpgradeWinUpgradeStrategyFlowLimitStrategy) *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery {
	uwusflsq.predicates = append(uwusflsq.predicates, ps...)
	return uwusflsq
}

// Limit the number of records to be returned by this query.
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) Limit(limit int) *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery {
	uwusflsq.ctx.Limit = &limit
	return uwusflsq
}

// Offset to start from.
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) Offset(offset int) *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery {
	uwusflsq.ctx.Offset = &offset
	return uwusflsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) Unique(unique bool) *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery {
	uwusflsq.ctx.Unique = &unique
	return uwusflsq
}

// Order specifies how the records should be ordered.
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) Order(o ...upgradewinupgradestrategyflowlimitstrategy.OrderOption) *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery {
	uwusflsq.order = append(uwusflsq.order, o...)
	return uwusflsq
}

// First returns the first UpgradeWinUpgradeStrategyFlowLimitStrategy entity from the query.
// Returns a *NotFoundError when no UpgradeWinUpgradeStrategyFlowLimitStrategy was found.
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) First(ctx context.Context) (*UpgradeWinUpgradeStrategyFlowLimitStrategy, error) {
	nodes, err := uwusflsq.Limit(1).All(setContextOp(ctx, uwusflsq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{upgradewinupgradestrategyflowlimitstrategy.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) FirstX(ctx context.Context) *UpgradeWinUpgradeStrategyFlowLimitStrategy {
	node, err := uwusflsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UpgradeWinUpgradeStrategyFlowLimitStrategy ID from the query.
// Returns a *NotFoundError when no UpgradeWinUpgradeStrategyFlowLimitStrategy ID was found.
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uwusflsq.Limit(1).IDs(setContextOp(ctx, uwusflsq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{upgradewinupgradestrategyflowlimitstrategy.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) FirstIDX(ctx context.Context) int {
	id, err := uwusflsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UpgradeWinUpgradeStrategyFlowLimitStrategy entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UpgradeWinUpgradeStrategyFlowLimitStrategy entity is found.
// Returns a *NotFoundError when no UpgradeWinUpgradeStrategyFlowLimitStrategy entities are found.
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) Only(ctx context.Context) (*UpgradeWinUpgradeStrategyFlowLimitStrategy, error) {
	nodes, err := uwusflsq.Limit(2).All(setContextOp(ctx, uwusflsq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{upgradewinupgradestrategyflowlimitstrategy.Label}
	default:
		return nil, &NotSingularError{upgradewinupgradestrategyflowlimitstrategy.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) OnlyX(ctx context.Context) *UpgradeWinUpgradeStrategyFlowLimitStrategy {
	node, err := uwusflsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UpgradeWinUpgradeStrategyFlowLimitStrategy ID in the query.
// Returns a *NotSingularError when more than one UpgradeWinUpgradeStrategyFlowLimitStrategy ID is found.
// Returns a *NotFoundError when no entities are found.
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uwusflsq.Limit(2).IDs(setContextOp(ctx, uwusflsq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{upgradewinupgradestrategyflowlimitstrategy.Label}
	default:
		err = &NotSingularError{upgradewinupgradestrategyflowlimitstrategy.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) OnlyIDX(ctx context.Context) int {
	id, err := uwusflsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UpgradeWinUpgradeStrategyFlowLimitStrategies.
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) All(ctx context.Context) ([]*UpgradeWinUpgradeStrategyFlowLimitStrategy, error) {
	ctx = setContextOp(ctx, uwusflsq.ctx, ent.OpQueryAll)
	if err := uwusflsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UpgradeWinUpgradeStrategyFlowLimitStrategy, *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery]()
	return withInterceptors[[]*UpgradeWinUpgradeStrategyFlowLimitStrategy](ctx, uwusflsq, qr, uwusflsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) AllX(ctx context.Context) []*UpgradeWinUpgradeStrategyFlowLimitStrategy {
	nodes, err := uwusflsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UpgradeWinUpgradeStrategyFlowLimitStrategy IDs.
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) IDs(ctx context.Context) (ids []int, err error) {
	if uwusflsq.ctx.Unique == nil && uwusflsq.path != nil {
		uwusflsq.Unique(true)
	}
	ctx = setContextOp(ctx, uwusflsq.ctx, ent.OpQueryIDs)
	if err = uwusflsq.Select(upgradewinupgradestrategyflowlimitstrategy.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) IDsX(ctx context.Context) []int {
	ids, err := uwusflsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, uwusflsq.ctx, ent.OpQueryCount)
	if err := uwusflsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, uwusflsq, querierCount[*UpgradeWinUpgradeStrategyFlowLimitStrategyQuery](), uwusflsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) CountX(ctx context.Context) int {
	count, err := uwusflsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, uwusflsq.ctx, ent.OpQueryExist)
	switch _, err := uwusflsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) ExistX(ctx context.Context) bool {
	exist, err := uwusflsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UpgradeWinUpgradeStrategyFlowLimitStrategyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) Clone() *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery {
	if uwusflsq == nil {
		return nil
	}
	return &UpgradeWinUpgradeStrategyFlowLimitStrategyQuery{
		config:     uwusflsq.config,
		ctx:        uwusflsq.ctx.Clone(),
		order:      append([]upgradewinupgradestrategyflowlimitstrategy.OrderOption{}, uwusflsq.order...),
		inters:     append([]Interceptor{}, uwusflsq.inters...),
		predicates: append([]predicate.UpgradeWinUpgradeStrategyFlowLimitStrategy{}, uwusflsq.predicates...),
		// clone intermediate query.
		sql:  uwusflsq.sql.Clone(),
		path: uwusflsq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Enable int32 `json:"enable,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UpgradeWinUpgradeStrategyFlowLimitStrategy.Query().
//		GroupBy(upgradewinupgradestrategyflowlimitstrategy.FieldEnable).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) GroupBy(field string, fields ...string) *UpgradeWinUpgradeStrategyFlowLimitStrategyGroupBy {
	uwusflsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UpgradeWinUpgradeStrategyFlowLimitStrategyGroupBy{build: uwusflsq}
	grbuild.flds = &uwusflsq.ctx.Fields
	grbuild.label = upgradewinupgradestrategyflowlimitstrategy.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Enable int32 `json:"enable,omitempty"`
//	}
//
//	client.UpgradeWinUpgradeStrategyFlowLimitStrategy.Query().
//		Select(upgradewinupgradestrategyflowlimitstrategy.FieldEnable).
//		Scan(ctx, &v)
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) Select(fields ...string) *UpgradeWinUpgradeStrategyFlowLimitStrategySelect {
	uwusflsq.ctx.Fields = append(uwusflsq.ctx.Fields, fields...)
	sbuild := &UpgradeWinUpgradeStrategyFlowLimitStrategySelect{UpgradeWinUpgradeStrategyFlowLimitStrategyQuery: uwusflsq}
	sbuild.label = upgradewinupgradestrategyflowlimitstrategy.Label
	sbuild.flds, sbuild.scan = &uwusflsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UpgradeWinUpgradeStrategyFlowLimitStrategySelect configured with the given aggregations.
func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) Aggregate(fns ...AggregateFunc) *UpgradeWinUpgradeStrategyFlowLimitStrategySelect {
	return uwusflsq.Select().Aggregate(fns...)
}

func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range uwusflsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, uwusflsq); err != nil {
				return err
			}
		}
	}
	for _, f := range uwusflsq.ctx.Fields {
		if !upgradewinupgradestrategyflowlimitstrategy.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uwusflsq.path != nil {
		prev, err := uwusflsq.path(ctx)
		if err != nil {
			return err
		}
		uwusflsq.sql = prev
	}
	return nil
}

func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UpgradeWinUpgradeStrategyFlowLimitStrategy, error) {
	var (
		nodes = []*UpgradeWinUpgradeStrategyFlowLimitStrategy{}
		_spec = uwusflsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UpgradeWinUpgradeStrategyFlowLimitStrategy).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UpgradeWinUpgradeStrategyFlowLimitStrategy{config: uwusflsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uwusflsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uwusflsq.querySpec()
	_spec.Node.Columns = uwusflsq.ctx.Fields
	if len(uwusflsq.ctx.Fields) > 0 {
		_spec.Unique = uwusflsq.ctx.Unique != nil && *uwusflsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, uwusflsq.driver, _spec)
}

func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(upgradewinupgradestrategyflowlimitstrategy.Table, upgradewinupgradestrategyflowlimitstrategy.Columns, sqlgraph.NewFieldSpec(upgradewinupgradestrategyflowlimitstrategy.FieldID, field.TypeInt))
	_spec.From = uwusflsq.sql
	if unique := uwusflsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if uwusflsq.path != nil {
		_spec.Unique = true
	}
	if fields := uwusflsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upgradewinupgradestrategyflowlimitstrategy.FieldID)
		for i := range fields {
			if fields[i] != upgradewinupgradestrategyflowlimitstrategy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uwusflsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uwusflsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uwusflsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uwusflsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uwusflsq *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uwusflsq.driver.Dialect())
	t1 := builder.Table(upgradewinupgradestrategyflowlimitstrategy.Table)
	columns := uwusflsq.ctx.Fields
	if len(columns) == 0 {
		columns = upgradewinupgradestrategyflowlimitstrategy.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uwusflsq.sql != nil {
		selector = uwusflsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uwusflsq.ctx.Unique != nil && *uwusflsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range uwusflsq.predicates {
		p(selector)
	}
	for _, p := range uwusflsq.order {
		p(selector)
	}
	if offset := uwusflsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uwusflsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UpgradeWinUpgradeStrategyFlowLimitStrategyGroupBy is the group-by builder for UpgradeWinUpgradeStrategyFlowLimitStrategy entities.
type UpgradeWinUpgradeStrategyFlowLimitStrategyGroupBy struct {
	selector
	build *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uwusflsgb *UpgradeWinUpgradeStrategyFlowLimitStrategyGroupBy) Aggregate(fns ...AggregateFunc) *UpgradeWinUpgradeStrategyFlowLimitStrategyGroupBy {
	uwusflsgb.fns = append(uwusflsgb.fns, fns...)
	return uwusflsgb
}

// Scan applies the selector query and scans the result into the given value.
func (uwusflsgb *UpgradeWinUpgradeStrategyFlowLimitStrategyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uwusflsgb.build.ctx, ent.OpQueryGroupBy)
	if err := uwusflsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpgradeWinUpgradeStrategyFlowLimitStrategyQuery, *UpgradeWinUpgradeStrategyFlowLimitStrategyGroupBy](ctx, uwusflsgb.build, uwusflsgb, uwusflsgb.build.inters, v)
}

func (uwusflsgb *UpgradeWinUpgradeStrategyFlowLimitStrategyGroupBy) sqlScan(ctx context.Context, root *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(uwusflsgb.fns))
	for _, fn := range uwusflsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*uwusflsgb.flds)+len(uwusflsgb.fns))
		for _, f := range *uwusflsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*uwusflsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uwusflsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UpgradeWinUpgradeStrategyFlowLimitStrategySelect is the builder for selecting fields of UpgradeWinUpgradeStrategyFlowLimitStrategy entities.
type UpgradeWinUpgradeStrategyFlowLimitStrategySelect struct {
	*UpgradeWinUpgradeStrategyFlowLimitStrategyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uwusflss *UpgradeWinUpgradeStrategyFlowLimitStrategySelect) Aggregate(fns ...AggregateFunc) *UpgradeWinUpgradeStrategyFlowLimitStrategySelect {
	uwusflss.fns = append(uwusflss.fns, fns...)
	return uwusflss
}

// Scan applies the selector query and scans the result into the given value.
func (uwusflss *UpgradeWinUpgradeStrategyFlowLimitStrategySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uwusflss.ctx, ent.OpQuerySelect)
	if err := uwusflss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpgradeWinUpgradeStrategyFlowLimitStrategyQuery, *UpgradeWinUpgradeStrategyFlowLimitStrategySelect](ctx, uwusflss.UpgradeWinUpgradeStrategyFlowLimitStrategyQuery, uwusflss, uwusflss.inters, v)
}

func (uwusflss *UpgradeWinUpgradeStrategyFlowLimitStrategySelect) sqlScan(ctx context.Context, root *UpgradeWinUpgradeStrategyFlowLimitStrategyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(uwusflss.fns))
	for _, fn := range uwusflss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*uwusflss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uwusflss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
