// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"upgradelink-admin-upgrade/server/ent/upgradelnxversion"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UpgradeLnxVersion is the model entity for the UpgradeLnxVersion schema.
type UpgradeLnxVersion struct {
	config `json:"-"`
	// ID of the ent.
	// ID
	ID int `json:"id,omitempty"`
	// 公司ID
	CompanyID int `json:"company_id,omitempty"`
	// lnx应用ID
	LnxID int `json:"lnx_id,omitempty"`
	// 云文件id
	CloudFileID string `json:"cloud_file_id,omitempty"`
	// 版本名
	VersionName string `json:"version_name,omitempty"`
	// 版本号
	VersionCode int `json:"version_code,omitempty"`
	// 机器架构:x64、arm64
	Arch string `json:"arch,omitempty"`
	// 描述信息
	Description string `json:"description,omitempty"`
	// 是否删除 0：正常；1：已删除
	IsDel int32 `json:"is_del,omitempty"`
	// 创建时间
	CreateAt time.Time `json:"create_at,omitempty"`
	// 修改时间
	UpdateAt     time.Time `json:"update_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpgradeLnxVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upgradelnxversion.FieldID, upgradelnxversion.FieldCompanyID, upgradelnxversion.FieldLnxID, upgradelnxversion.FieldVersionCode, upgradelnxversion.FieldIsDel:
			values[i] = new(sql.NullInt64)
		case upgradelnxversion.FieldCloudFileID, upgradelnxversion.FieldVersionName, upgradelnxversion.FieldArch, upgradelnxversion.FieldDescription:
			values[i] = new(sql.NullString)
		case upgradelnxversion.FieldCreateAt, upgradelnxversion.FieldUpdateAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpgradeLnxVersion fields.
func (ulv *UpgradeLnxVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upgradelnxversion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ulv.ID = int(value.Int64)
		case upgradelnxversion.FieldCompanyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field company_id", values[i])
			} else if value.Valid {
				ulv.CompanyID = int(value.Int64)
			}
		case upgradelnxversion.FieldLnxID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lnx_id", values[i])
			} else if value.Valid {
				ulv.LnxID = int(value.Int64)
			}
		case upgradelnxversion.FieldCloudFileID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cloud_file_id", values[i])
			} else if value.Valid {
				ulv.CloudFileID = value.String
			}
		case upgradelnxversion.FieldVersionName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version_name", values[i])
			} else if value.Valid {
				ulv.VersionName = value.String
			}
		case upgradelnxversion.FieldVersionCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version_code", values[i])
			} else if value.Valid {
				ulv.VersionCode = int(value.Int64)
			}
		case upgradelnxversion.FieldArch:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field arch", values[i])
			} else if value.Valid {
				ulv.Arch = value.String
			}
		case upgradelnxversion.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				ulv.Description = value.String
			}
		case upgradelnxversion.FieldIsDel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field is_del", values[i])
			} else if value.Valid {
				ulv.IsDel = int32(value.Int64)
			}
		case upgradelnxversion.FieldCreateAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_at", values[i])
			} else if value.Valid {
				ulv.CreateAt = value.Time
			}
		case upgradelnxversion.FieldUpdateAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_at", values[i])
			} else if value.Valid {
				ulv.UpdateAt = value.Time
			}
		default:
			ulv.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpgradeLnxVersion.
// This includes values selected through modifiers, order, etc.
func (ulv *UpgradeLnxVersion) Value(name string) (ent.Value, error) {
	return ulv.selectValues.Get(name)
}

// Update returns a builder for updating this UpgradeLnxVersion.
// Note that you need to call UpgradeLnxVersion.Unwrap() before calling this method if this UpgradeLnxVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (ulv *UpgradeLnxVersion) Update() *UpgradeLnxVersionUpdateOne {
	return NewUpgradeLnxVersionClient(ulv.config).UpdateOne(ulv)
}

// Unwrap unwraps the UpgradeLnxVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ulv *UpgradeLnxVersion) Unwrap() *UpgradeLnxVersion {
	_tx, ok := ulv.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpgradeLnxVersion is not a transactional entity")
	}
	ulv.config.driver = _tx.drv
	return ulv
}

// String implements the fmt.Stringer.
func (ulv *UpgradeLnxVersion) String() string {
	var builder strings.Builder
	builder.WriteString("UpgradeLnxVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ulv.ID))
	builder.WriteString("company_id=")
	builder.WriteString(fmt.Sprintf("%v", ulv.CompanyID))
	builder.WriteString(", ")
	builder.WriteString("lnx_id=")
	builder.WriteString(fmt.Sprintf("%v", ulv.LnxID))
	builder.WriteString(", ")
	builder.WriteString("cloud_file_id=")
	builder.WriteString(ulv.CloudFileID)
	builder.WriteString(", ")
	builder.WriteString("version_name=")
	builder.WriteString(ulv.VersionName)
	builder.WriteString(", ")
	builder.WriteString("version_code=")
	builder.WriteString(fmt.Sprintf("%v", ulv.VersionCode))
	builder.WriteString(", ")
	builder.WriteString("arch=")
	builder.WriteString(ulv.Arch)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(ulv.Description)
	builder.WriteString(", ")
	builder.WriteString("is_del=")
	builder.WriteString(fmt.Sprintf("%v", ulv.IsDel))
	builder.WriteString(", ")
	builder.WriteString("create_at=")
	builder.WriteString(ulv.CreateAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_at=")
	builder.WriteString(ulv.UpdateAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UpgradeLnxVersions is a parsable slice of UpgradeLnxVersion.
type UpgradeLnxVersions []*UpgradeLnxVersion
