// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"upgradelink-admin-upgrade/server/ent/predicate"
	"upgradelink-admin-upgrade/server/ent/upgradelnx"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeLnxUpdate is the builder for updating UpgradeLnx entities.
type UpgradeLnxUpdate struct {
	config
	hooks    []Hook
	mutation *UpgradeLnxMutation
}

// Where appends a list predicates to the UpgradeLnxUpdate builder.
func (ulu *UpgradeLnxUpdate) Where(ps ...predicate.UpgradeLnx) *UpgradeLnxUpdate {
	ulu.mutation.Where(ps...)
	return ulu
}

// SetCompanyID sets the "company_id" field.
func (ulu *UpgradeLnxUpdate) SetCompanyID(i int) *UpgradeLnxUpdate {
	ulu.mutation.ResetCompanyID()
	ulu.mutation.SetCompanyID(i)
	return ulu
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (ulu *UpgradeLnxUpdate) SetNillableCompanyID(i *int) *UpgradeLnxUpdate {
	if i != nil {
		ulu.SetCompanyID(*i)
	}
	return ulu
}

// AddCompanyID adds i to the "company_id" field.
func (ulu *UpgradeLnxUpdate) AddCompanyID(i int) *UpgradeLnxUpdate {
	ulu.mutation.AddCompanyID(i)
	return ulu
}

// SetKey sets the "key" field.
func (ulu *UpgradeLnxUpdate) SetKey(s string) *UpgradeLnxUpdate {
	ulu.mutation.SetKey(s)
	return ulu
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (ulu *UpgradeLnxUpdate) SetNillableKey(s *string) *UpgradeLnxUpdate {
	if s != nil {
		ulu.SetKey(*s)
	}
	return ulu
}

// SetName sets the "name" field.
func (ulu *UpgradeLnxUpdate) SetName(s string) *UpgradeLnxUpdate {
	ulu.mutation.SetName(s)
	return ulu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ulu *UpgradeLnxUpdate) SetNillableName(s *string) *UpgradeLnxUpdate {
	if s != nil {
		ulu.SetName(*s)
	}
	return ulu
}

// SetPackageName sets the "package_name" field.
func (ulu *UpgradeLnxUpdate) SetPackageName(s string) *UpgradeLnxUpdate {
	ulu.mutation.SetPackageName(s)
	return ulu
}

// SetNillablePackageName sets the "package_name" field if the given value is not nil.
func (ulu *UpgradeLnxUpdate) SetNillablePackageName(s *string) *UpgradeLnxUpdate {
	if s != nil {
		ulu.SetPackageName(*s)
	}
	return ulu
}

// SetDescription sets the "description" field.
func (ulu *UpgradeLnxUpdate) SetDescription(s string) *UpgradeLnxUpdate {
	ulu.mutation.SetDescription(s)
	return ulu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ulu *UpgradeLnxUpdate) SetNillableDescription(s *string) *UpgradeLnxUpdate {
	if s != nil {
		ulu.SetDescription(*s)
	}
	return ulu
}

// ClearDescription clears the value of the "description" field.
func (ulu *UpgradeLnxUpdate) ClearDescription() *UpgradeLnxUpdate {
	ulu.mutation.ClearDescription()
	return ulu
}

// SetIsDel sets the "is_del" field.
func (ulu *UpgradeLnxUpdate) SetIsDel(i int32) *UpgradeLnxUpdate {
	ulu.mutation.ResetIsDel()
	ulu.mutation.SetIsDel(i)
	return ulu
}

// SetNillableIsDel sets the "is_del" field if the given value is not nil.
func (ulu *UpgradeLnxUpdate) SetNillableIsDel(i *int32) *UpgradeLnxUpdate {
	if i != nil {
		ulu.SetIsDel(*i)
	}
	return ulu
}

// AddIsDel adds i to the "is_del" field.
func (ulu *UpgradeLnxUpdate) AddIsDel(i int32) *UpgradeLnxUpdate {
	ulu.mutation.AddIsDel(i)
	return ulu
}

// SetCreateAt sets the "create_at" field.
func (ulu *UpgradeLnxUpdate) SetCreateAt(t time.Time) *UpgradeLnxUpdate {
	ulu.mutation.SetCreateAt(t)
	return ulu
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (ulu *UpgradeLnxUpdate) SetNillableCreateAt(t *time.Time) *UpgradeLnxUpdate {
	if t != nil {
		ulu.SetCreateAt(*t)
	}
	return ulu
}

// ClearCreateAt clears the value of the "create_at" field.
func (ulu *UpgradeLnxUpdate) ClearCreateAt() *UpgradeLnxUpdate {
	ulu.mutation.ClearCreateAt()
	return ulu
}

// SetUpdateAt sets the "update_at" field.
func (ulu *UpgradeLnxUpdate) SetUpdateAt(t time.Time) *UpgradeLnxUpdate {
	ulu.mutation.SetUpdateAt(t)
	return ulu
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (ulu *UpgradeLnxUpdate) SetNillableUpdateAt(t *time.Time) *UpgradeLnxUpdate {
	if t != nil {
		ulu.SetUpdateAt(*t)
	}
	return ulu
}

// ClearUpdateAt clears the value of the "update_at" field.
func (ulu *UpgradeLnxUpdate) ClearUpdateAt() *UpgradeLnxUpdate {
	ulu.mutation.ClearUpdateAt()
	return ulu
}

// Mutation returns the UpgradeLnxMutation object of the builder.
func (ulu *UpgradeLnxUpdate) Mutation() *UpgradeLnxMutation {
	return ulu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ulu *UpgradeLnxUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ulu.sqlSave, ulu.mutation, ulu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ulu *UpgradeLnxUpdate) SaveX(ctx context.Context) int {
	affected, err := ulu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ulu *UpgradeLnxUpdate) Exec(ctx context.Context) error {
	_, err := ulu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ulu *UpgradeLnxUpdate) ExecX(ctx context.Context) {
	if err := ulu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ulu *UpgradeLnxUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(upgradelnx.Table, upgradelnx.Columns, sqlgraph.NewFieldSpec(upgradelnx.FieldID, field.TypeInt))
	if ps := ulu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ulu.mutation.CompanyID(); ok {
		_spec.SetField(upgradelnx.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := ulu.mutation.AddedCompanyID(); ok {
		_spec.AddField(upgradelnx.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := ulu.mutation.Key(); ok {
		_spec.SetField(upgradelnx.FieldKey, field.TypeString, value)
	}
	if value, ok := ulu.mutation.Name(); ok {
		_spec.SetField(upgradelnx.FieldName, field.TypeString, value)
	}
	if value, ok := ulu.mutation.PackageName(); ok {
		_spec.SetField(upgradelnx.FieldPackageName, field.TypeString, value)
	}
	if value, ok := ulu.mutation.Description(); ok {
		_spec.SetField(upgradelnx.FieldDescription, field.TypeString, value)
	}
	if ulu.mutation.DescriptionCleared() {
		_spec.ClearField(upgradelnx.FieldDescription, field.TypeString)
	}
	if value, ok := ulu.mutation.IsDel(); ok {
		_spec.SetField(upgradelnx.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := ulu.mutation.AddedIsDel(); ok {
		_spec.AddField(upgradelnx.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := ulu.mutation.CreateAt(); ok {
		_spec.SetField(upgradelnx.FieldCreateAt, field.TypeTime, value)
	}
	if ulu.mutation.CreateAtCleared() {
		_spec.ClearField(upgradelnx.FieldCreateAt, field.TypeTime)
	}
	if value, ok := ulu.mutation.UpdateAt(); ok {
		_spec.SetField(upgradelnx.FieldUpdateAt, field.TypeTime, value)
	}
	if ulu.mutation.UpdateAtCleared() {
		_spec.ClearField(upgradelnx.FieldUpdateAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ulu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upgradelnx.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ulu.mutation.done = true
	return n, nil
}

// UpgradeLnxUpdateOne is the builder for updating a single UpgradeLnx entity.
type UpgradeLnxUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpgradeLnxMutation
}

// SetCompanyID sets the "company_id" field.
func (uluo *UpgradeLnxUpdateOne) SetCompanyID(i int) *UpgradeLnxUpdateOne {
	uluo.mutation.ResetCompanyID()
	uluo.mutation.SetCompanyID(i)
	return uluo
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (uluo *UpgradeLnxUpdateOne) SetNillableCompanyID(i *int) *UpgradeLnxUpdateOne {
	if i != nil {
		uluo.SetCompanyID(*i)
	}
	return uluo
}

// AddCompanyID adds i to the "company_id" field.
func (uluo *UpgradeLnxUpdateOne) AddCompanyID(i int) *UpgradeLnxUpdateOne {
	uluo.mutation.AddCompanyID(i)
	return uluo
}

// SetKey sets the "key" field.
func (uluo *UpgradeLnxUpdateOne) SetKey(s string) *UpgradeLnxUpdateOne {
	uluo.mutation.SetKey(s)
	return uluo
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (uluo *UpgradeLnxUpdateOne) SetNillableKey(s *string) *UpgradeLnxUpdateOne {
	if s != nil {
		uluo.SetKey(*s)
	}
	return uluo
}

// SetName sets the "name" field.
func (uluo *UpgradeLnxUpdateOne) SetName(s string) *UpgradeLnxUpdateOne {
	uluo.mutation.SetName(s)
	return uluo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (uluo *UpgradeLnxUpdateOne) SetNillableName(s *string) *UpgradeLnxUpdateOne {
	if s != nil {
		uluo.SetName(*s)
	}
	return uluo
}

// SetPackageName sets the "package_name" field.
func (uluo *UpgradeLnxUpdateOne) SetPackageName(s string) *UpgradeLnxUpdateOne {
	uluo.mutation.SetPackageName(s)
	return uluo
}

// SetNillablePackageName sets the "package_name" field if the given value is not nil.
func (uluo *UpgradeLnxUpdateOne) SetNillablePackageName(s *string) *UpgradeLnxUpdateOne {
	if s != nil {
		uluo.SetPackageName(*s)
	}
	return uluo
}

// SetDescription sets the "description" field.
func (uluo *UpgradeLnxUpdateOne) SetDescription(s string) *UpgradeLnxUpdateOne {
	uluo.mutation.SetDescription(s)
	return uluo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (uluo *UpgradeLnxUpdateOne) SetNillableDescription(s *string) *UpgradeLnxUpdateOne {
	if s != nil {
		uluo.SetDescription(*s)
	}
	return uluo
}

// ClearDescription clears the value of the "description" field.
func (uluo *UpgradeLnxUpdateOne) ClearDescription() *UpgradeLnxUpdateOne {
	uluo.mutation.ClearDescription()
	return uluo
}

// SetIsDel sets the "is_del" field.
func (uluo *UpgradeLnxUpdateOne) SetIsDel(i int32) *UpgradeLnxUpdateOne {
	uluo.mutation.ResetIsDel()
	uluo.mutation.SetIsDel(i)
	return uluo
}

// SetNillableIsDel sets the "is_del" field if the given value is not nil.
func (uluo *UpgradeLnxUpdateOne) SetNillableIsDel(i *int32) *UpgradeLnxUpdateOne {
	if i != nil {
		uluo.SetIsDel(*i)
	}
	return uluo
}

// AddIsDel adds i to the "is_del" field.
func (uluo *UpgradeLnxUpdateOne) AddIsDel(i int32) *UpgradeLnxUpdateOne {
	uluo.mutation.AddIsDel(i)
	return uluo
}

// SetCreateAt sets the "create_at" field.
func (uluo *UpgradeLnxUpdateOne) SetCreateAt(t time.Time) *UpgradeLnxUpdateOne {
	uluo.mutation.SetCreateAt(t)
	return uluo
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (uluo *UpgradeLnxUpdateOne) SetNillableCreateAt(t *time.Time) *UpgradeLnxUpdateOne {
	if t != nil {
		uluo.SetCreateAt(*t)
	}
	return uluo
}

// ClearCreateAt clears the value of the "create_at" field.
func (uluo *UpgradeLnxUpdateOne) ClearCreateAt() *UpgradeLnxUpdateOne {
	uluo.mutation.ClearCreateAt()
	return uluo
}

// SetUpdateAt sets the "update_at" field.
func (uluo *UpgradeLnxUpdateOne) SetUpdateAt(t time.Time) *UpgradeLnxUpdateOne {
	uluo.mutation.SetUpdateAt(t)
	return uluo
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (uluo *UpgradeLnxUpdateOne) SetNillableUpdateAt(t *time.Time) *UpgradeLnxUpdateOne {
	if t != nil {
		uluo.SetUpdateAt(*t)
	}
	return uluo
}

// ClearUpdateAt clears the value of the "update_at" field.
func (uluo *UpgradeLnxUpdateOne) ClearUpdateAt() *UpgradeLnxUpdateOne {
	uluo.mutation.ClearUpdateAt()
	return uluo
}

// Mutation returns the UpgradeLnxMutation object of the builder.
func (uluo *UpgradeLnxUpdateOne) Mutation() *UpgradeLnxMutation {
	return uluo.mutation
}

// Where appends a list predicates to the UpgradeLnxUpdate builder.
func (uluo *UpgradeLnxUpdateOne) Where(ps ...predicate.UpgradeLnx) *UpgradeLnxUpdateOne {
	uluo.mutation.Where(ps...)
	return uluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uluo *UpgradeLnxUpdateOne) Select(field string, fields ...string) *UpgradeLnxUpdateOne {
	uluo.fields = append([]string{field}, fields...)
	return uluo
}

// Save executes the query and returns the updated UpgradeLnx entity.
func (uluo *UpgradeLnxUpdateOne) Save(ctx context.Context) (*UpgradeLnx, error) {
	return withHooks(ctx, uluo.sqlSave, uluo.mutation, uluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uluo *UpgradeLnxUpdateOne) SaveX(ctx context.Context) *UpgradeLnx {
	node, err := uluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uluo *UpgradeLnxUpdateOne) Exec(ctx context.Context) error {
	_, err := uluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uluo *UpgradeLnxUpdateOne) ExecX(ctx context.Context) {
	if err := uluo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uluo *UpgradeLnxUpdateOne) sqlSave(ctx context.Context) (_node *UpgradeLnx, err error) {
	_spec := sqlgraph.NewUpdateSpec(upgradelnx.Table, upgradelnx.Columns, sqlgraph.NewFieldSpec(upgradelnx.FieldID, field.TypeInt))
	id, ok := uluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpgradeLnx.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upgradelnx.FieldID)
		for _, f := range fields {
			if !upgradelnx.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upgradelnx.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uluo.mutation.CompanyID(); ok {
		_spec.SetField(upgradelnx.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := uluo.mutation.AddedCompanyID(); ok {
		_spec.AddField(upgradelnx.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := uluo.mutation.Key(); ok {
		_spec.SetField(upgradelnx.FieldKey, field.TypeString, value)
	}
	if value, ok := uluo.mutation.Name(); ok {
		_spec.SetField(upgradelnx.FieldName, field.TypeString, value)
	}
	if value, ok := uluo.mutation.PackageName(); ok {
		_spec.SetField(upgradelnx.FieldPackageName, field.TypeString, value)
	}
	if value, ok := uluo.mutation.Description(); ok {
		_spec.SetField(upgradelnx.FieldDescription, field.TypeString, value)
	}
	if uluo.mutation.DescriptionCleared() {
		_spec.ClearField(upgradelnx.FieldDescription, field.TypeString)
	}
	if value, ok := uluo.mutation.IsDel(); ok {
		_spec.SetField(upgradelnx.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := uluo.mutation.AddedIsDel(); ok {
		_spec.AddField(upgradelnx.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := uluo.mutation.CreateAt(); ok {
		_spec.SetField(upgradelnx.FieldCreateAt, field.TypeTime, value)
	}
	if uluo.mutation.CreateAtCleared() {
		_spec.ClearField(upgradelnx.FieldCreateAt, field.TypeTime)
	}
	if value, ok := uluo.mutation.UpdateAt(); ok {
		_spec.SetField(upgradelnx.FieldUpdateAt, field.TypeTime, value)
	}
	if uluo.mutation.UpdateAtCleared() {
		_spec.ClearField(upgradelnx.FieldUpdateAt, field.TypeTime)
	}
	_node = &UpgradeLnx{config: uluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upgradelnx.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uluo.mutation.done = true
	return _node, nil
}
