// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"upgradelink-admin-upgrade/server/ent/predicate"
	"upgradelink-admin-upgrade/server/ent/upgradewin"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeWinUpdate is the builder for updating UpgradeWin entities.
type UpgradeWinUpdate struct {
	config
	hooks    []Hook
	mutation *UpgradeWinMutation
}

// Where appends a list predicates to the UpgradeWinUpdate builder.
func (uwu *UpgradeWinUpdate) Where(ps ...predicate.UpgradeWin) *UpgradeWinUpdate {
	uwu.mutation.Where(ps...)
	return uwu
}

// SetCompanyID sets the "company_id" field.
func (uwu *UpgradeWinUpdate) SetCompanyID(i int) *UpgradeWinUpdate {
	uwu.mutation.ResetCompanyID()
	uwu.mutation.SetCompanyID(i)
	return uwu
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (uwu *UpgradeWinUpdate) SetNillableCompanyID(i *int) *UpgradeWinUpdate {
	if i != nil {
		uwu.SetCompanyID(*i)
	}
	return uwu
}

// AddCompanyID adds i to the "company_id" field.
func (uwu *UpgradeWinUpdate) AddCompanyID(i int) *UpgradeWinUpdate {
	uwu.mutation.AddCompanyID(i)
	return uwu
}

// SetKey sets the "key" field.
func (uwu *UpgradeWinUpdate) SetKey(s string) *UpgradeWinUpdate {
	uwu.mutation.SetKey(s)
	return uwu
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (uwu *UpgradeWinUpdate) SetNillableKey(s *string) *UpgradeWinUpdate {
	if s != nil {
		uwu.SetKey(*s)
	}
	return uwu
}

// SetName sets the "name" field.
func (uwu *UpgradeWinUpdate) SetName(s string) *UpgradeWinUpdate {
	uwu.mutation.SetName(s)
	return uwu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (uwu *UpgradeWinUpdate) SetNillableName(s *string) *UpgradeWinUpdate {
	if s != nil {
		uwu.SetName(*s)
	}
	return uwu
}

// SetPackageName sets the "package_name" field.
func (uwu *UpgradeWinUpdate) SetPackageName(s string) *UpgradeWinUpdate {
	uwu.mutation.SetPackageName(s)
	return uwu
}

// SetNillablePackageName sets the "package_name" field if the given value is not nil.
func (uwu *UpgradeWinUpdate) SetNillablePackageName(s *string) *UpgradeWinUpdate {
	if s != nil {
		uwu.SetPackageName(*s)
	}
	return uwu
}

// SetDescription sets the "description" field.
func (uwu *UpgradeWinUpdate) SetDescription(s string) *UpgradeWinUpdate {
	uwu.mutation.SetDescription(s)
	return uwu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (uwu *UpgradeWinUpdate) SetNillableDescription(s *string) *UpgradeWinUpdate {
	if s != nil {
		uwu.SetDescription(*s)
	}
	return uwu
}

// ClearDescription clears the value of the "description" field.
func (uwu *UpgradeWinUpdate) ClearDescription() *UpgradeWinUpdate {
	uwu.mutation.ClearDescription()
	return uwu
}

// SetIsDel sets the "is_del" field.
func (uwu *UpgradeWinUpdate) SetIsDel(i int32) *UpgradeWinUpdate {
	uwu.mutation.ResetIsDel()
	uwu.mutation.SetIsDel(i)
	return uwu
}

// SetNillableIsDel sets the "is_del" field if the given value is not nil.
func (uwu *UpgradeWinUpdate) SetNillableIsDel(i *int32) *UpgradeWinUpdate {
	if i != nil {
		uwu.SetIsDel(*i)
	}
	return uwu
}

// AddIsDel adds i to the "is_del" field.
func (uwu *UpgradeWinUpdate) AddIsDel(i int32) *UpgradeWinUpdate {
	uwu.mutation.AddIsDel(i)
	return uwu
}

// SetCreateAt sets the "create_at" field.
func (uwu *UpgradeWinUpdate) SetCreateAt(t time.Time) *UpgradeWinUpdate {
	uwu.mutation.SetCreateAt(t)
	return uwu
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (uwu *UpgradeWinUpdate) SetNillableCreateAt(t *time.Time) *UpgradeWinUpdate {
	if t != nil {
		uwu.SetCreateAt(*t)
	}
	return uwu
}

// ClearCreateAt clears the value of the "create_at" field.
func (uwu *UpgradeWinUpdate) ClearCreateAt() *UpgradeWinUpdate {
	uwu.mutation.ClearCreateAt()
	return uwu
}

// SetUpdateAt sets the "update_at" field.
func (uwu *UpgradeWinUpdate) SetUpdateAt(t time.Time) *UpgradeWinUpdate {
	uwu.mutation.SetUpdateAt(t)
	return uwu
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (uwu *UpgradeWinUpdate) SetNillableUpdateAt(t *time.Time) *UpgradeWinUpdate {
	if t != nil {
		uwu.SetUpdateAt(*t)
	}
	return uwu
}

// ClearUpdateAt clears the value of the "update_at" field.
func (uwu *UpgradeWinUpdate) ClearUpdateAt() *UpgradeWinUpdate {
	uwu.mutation.ClearUpdateAt()
	return uwu
}

// Mutation returns the UpgradeWinMutation object of the builder.
func (uwu *UpgradeWinUpdate) Mutation() *UpgradeWinMutation {
	return uwu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uwu *UpgradeWinUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, uwu.sqlSave, uwu.mutation, uwu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uwu *UpgradeWinUpdate) SaveX(ctx context.Context) int {
	affected, err := uwu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uwu *UpgradeWinUpdate) Exec(ctx context.Context) error {
	_, err := uwu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uwu *UpgradeWinUpdate) ExecX(ctx context.Context) {
	if err := uwu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uwu *UpgradeWinUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(upgradewin.Table, upgradewin.Columns, sqlgraph.NewFieldSpec(upgradewin.FieldID, field.TypeInt))
	if ps := uwu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uwu.mutation.CompanyID(); ok {
		_spec.SetField(upgradewin.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := uwu.mutation.AddedCompanyID(); ok {
		_spec.AddField(upgradewin.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := uwu.mutation.Key(); ok {
		_spec.SetField(upgradewin.FieldKey, field.TypeString, value)
	}
	if value, ok := uwu.mutation.Name(); ok {
		_spec.SetField(upgradewin.FieldName, field.TypeString, value)
	}
	if value, ok := uwu.mutation.PackageName(); ok {
		_spec.SetField(upgradewin.FieldPackageName, field.TypeString, value)
	}
	if value, ok := uwu.mutation.Description(); ok {
		_spec.SetField(upgradewin.FieldDescription, field.TypeString, value)
	}
	if uwu.mutation.DescriptionCleared() {
		_spec.ClearField(upgradewin.FieldDescription, field.TypeString)
	}
	if value, ok := uwu.mutation.IsDel(); ok {
		_spec.SetField(upgradewin.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := uwu.mutation.AddedIsDel(); ok {
		_spec.AddField(upgradewin.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := uwu.mutation.CreateAt(); ok {
		_spec.SetField(upgradewin.FieldCreateAt, field.TypeTime, value)
	}
	if uwu.mutation.CreateAtCleared() {
		_spec.ClearField(upgradewin.FieldCreateAt, field.TypeTime)
	}
	if value, ok := uwu.mutation.UpdateAt(); ok {
		_spec.SetField(upgradewin.FieldUpdateAt, field.TypeTime, value)
	}
	if uwu.mutation.UpdateAtCleared() {
		_spec.ClearField(upgradewin.FieldUpdateAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uwu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upgradewin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uwu.mutation.done = true
	return n, nil
}

// UpgradeWinUpdateOne is the builder for updating a single UpgradeWin entity.
type UpgradeWinUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpgradeWinMutation
}

// SetCompanyID sets the "company_id" field.
func (uwuo *UpgradeWinUpdateOne) SetCompanyID(i int) *UpgradeWinUpdateOne {
	uwuo.mutation.ResetCompanyID()
	uwuo.mutation.SetCompanyID(i)
	return uwuo
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (uwuo *UpgradeWinUpdateOne) SetNillableCompanyID(i *int) *UpgradeWinUpdateOne {
	if i != nil {
		uwuo.SetCompanyID(*i)
	}
	return uwuo
}

// AddCompanyID adds i to the "company_id" field.
func (uwuo *UpgradeWinUpdateOne) AddCompanyID(i int) *UpgradeWinUpdateOne {
	uwuo.mutation.AddCompanyID(i)
	return uwuo
}

// SetKey sets the "key" field.
func (uwuo *UpgradeWinUpdateOne) SetKey(s string) *UpgradeWinUpdateOne {
	uwuo.mutation.SetKey(s)
	return uwuo
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (uwuo *UpgradeWinUpdateOne) SetNillableKey(s *string) *UpgradeWinUpdateOne {
	if s != nil {
		uwuo.SetKey(*s)
	}
	return uwuo
}

// SetName sets the "name" field.
func (uwuo *UpgradeWinUpdateOne) SetName(s string) *UpgradeWinUpdateOne {
	uwuo.mutation.SetName(s)
	return uwuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (uwuo *UpgradeWinUpdateOne) SetNillableName(s *string) *UpgradeWinUpdateOne {
	if s != nil {
		uwuo.SetName(*s)
	}
	return uwuo
}

// SetPackageName sets the "package_name" field.
func (uwuo *UpgradeWinUpdateOne) SetPackageName(s string) *UpgradeWinUpdateOne {
	uwuo.mutation.SetPackageName(s)
	return uwuo
}

// SetNillablePackageName sets the "package_name" field if the given value is not nil.
func (uwuo *UpgradeWinUpdateOne) SetNillablePackageName(s *string) *UpgradeWinUpdateOne {
	if s != nil {
		uwuo.SetPackageName(*s)
	}
	return uwuo
}

// SetDescription sets the "description" field.
func (uwuo *UpgradeWinUpdateOne) SetDescription(s string) *UpgradeWinUpdateOne {
	uwuo.mutation.SetDescription(s)
	return uwuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (uwuo *UpgradeWinUpdateOne) SetNillableDescription(s *string) *UpgradeWinUpdateOne {
	if s != nil {
		uwuo.SetDescription(*s)
	}
	return uwuo
}

// ClearDescription clears the value of the "description" field.
func (uwuo *UpgradeWinUpdateOne) ClearDescription() *UpgradeWinUpdateOne {
	uwuo.mutation.ClearDescription()
	return uwuo
}

// SetIsDel sets the "is_del" field.
func (uwuo *UpgradeWinUpdateOne) SetIsDel(i int32) *UpgradeWinUpdateOne {
	uwuo.mutation.ResetIsDel()
	uwuo.mutation.SetIsDel(i)
	return uwuo
}

// SetNillableIsDel sets the "is_del" field if the given value is not nil.
func (uwuo *UpgradeWinUpdateOne) SetNillableIsDel(i *int32) *UpgradeWinUpdateOne {
	if i != nil {
		uwuo.SetIsDel(*i)
	}
	return uwuo
}

// AddIsDel adds i to the "is_del" field.
func (uwuo *UpgradeWinUpdateOne) AddIsDel(i int32) *UpgradeWinUpdateOne {
	uwuo.mutation.AddIsDel(i)
	return uwuo
}

// SetCreateAt sets the "create_at" field.
func (uwuo *UpgradeWinUpdateOne) SetCreateAt(t time.Time) *UpgradeWinUpdateOne {
	uwuo.mutation.SetCreateAt(t)
	return uwuo
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (uwuo *UpgradeWinUpdateOne) SetNillableCreateAt(t *time.Time) *UpgradeWinUpdateOne {
	if t != nil {
		uwuo.SetCreateAt(*t)
	}
	return uwuo
}

// ClearCreateAt clears the value of the "create_at" field.
func (uwuo *UpgradeWinUpdateOne) ClearCreateAt() *UpgradeWinUpdateOne {
	uwuo.mutation.ClearCreateAt()
	return uwuo
}

// SetUpdateAt sets the "update_at" field.
func (uwuo *UpgradeWinUpdateOne) SetUpdateAt(t time.Time) *UpgradeWinUpdateOne {
	uwuo.mutation.SetUpdateAt(t)
	return uwuo
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (uwuo *UpgradeWinUpdateOne) SetNillableUpdateAt(t *time.Time) *UpgradeWinUpdateOne {
	if t != nil {
		uwuo.SetUpdateAt(*t)
	}
	return uwuo
}

// ClearUpdateAt clears the value of the "update_at" field.
func (uwuo *UpgradeWinUpdateOne) ClearUpdateAt() *UpgradeWinUpdateOne {
	uwuo.mutation.ClearUpdateAt()
	return uwuo
}

// Mutation returns the UpgradeWinMutation object of the builder.
func (uwuo *UpgradeWinUpdateOne) Mutation() *UpgradeWinMutation {
	return uwuo.mutation
}

// Where appends a list predicates to the UpgradeWinUpdate builder.
func (uwuo *UpgradeWinUpdateOne) Where(ps ...predicate.UpgradeWin) *UpgradeWinUpdateOne {
	uwuo.mutation.Where(ps...)
	return uwuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uwuo *UpgradeWinUpdateOne) Select(field string, fields ...string) *UpgradeWinUpdateOne {
	uwuo.fields = append([]string{field}, fields...)
	return uwuo
}

// Save executes the query and returns the updated UpgradeWin entity.
func (uwuo *UpgradeWinUpdateOne) Save(ctx context.Context) (*UpgradeWin, error) {
	return withHooks(ctx, uwuo.sqlSave, uwuo.mutation, uwuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uwuo *UpgradeWinUpdateOne) SaveX(ctx context.Context) *UpgradeWin {
	node, err := uwuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uwuo *UpgradeWinUpdateOne) Exec(ctx context.Context) error {
	_, err := uwuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uwuo *UpgradeWinUpdateOne) ExecX(ctx context.Context) {
	if err := uwuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uwuo *UpgradeWinUpdateOne) sqlSave(ctx context.Context) (_node *UpgradeWin, err error) {
	_spec := sqlgraph.NewUpdateSpec(upgradewin.Table, upgradewin.Columns, sqlgraph.NewFieldSpec(upgradewin.FieldID, field.TypeInt))
	id, ok := uwuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpgradeWin.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uwuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upgradewin.FieldID)
		for _, f := range fields {
			if !upgradewin.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upgradewin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uwuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uwuo.mutation.CompanyID(); ok {
		_spec.SetField(upgradewin.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := uwuo.mutation.AddedCompanyID(); ok {
		_spec.AddField(upgradewin.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := uwuo.mutation.Key(); ok {
		_spec.SetField(upgradewin.FieldKey, field.TypeString, value)
	}
	if value, ok := uwuo.mutation.Name(); ok {
		_spec.SetField(upgradewin.FieldName, field.TypeString, value)
	}
	if value, ok := uwuo.mutation.PackageName(); ok {
		_spec.SetField(upgradewin.FieldPackageName, field.TypeString, value)
	}
	if value, ok := uwuo.mutation.Description(); ok {
		_spec.SetField(upgradewin.FieldDescription, field.TypeString, value)
	}
	if uwuo.mutation.DescriptionCleared() {
		_spec.ClearField(upgradewin.FieldDescription, field.TypeString)
	}
	if value, ok := uwuo.mutation.IsDel(); ok {
		_spec.SetField(upgradewin.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := uwuo.mutation.AddedIsDel(); ok {
		_spec.AddField(upgradewin.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := uwuo.mutation.CreateAt(); ok {
		_spec.SetField(upgradewin.FieldCreateAt, field.TypeTime, value)
	}
	if uwuo.mutation.CreateAtCleared() {
		_spec.ClearField(upgradewin.FieldCreateAt, field.TypeTime)
	}
	if value, ok := uwuo.mutation.UpdateAt(); ok {
		_spec.SetField(upgradewin.FieldUpdateAt, field.TypeTime, value)
	}
	if uwuo.mutation.UpdateAtCleared() {
		_spec.ClearField(upgradewin.FieldUpdateAt, field.TypeTime)
	}
	_node = &UpgradeWin{config: uwuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uwuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upgradewin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uwuo.mutation.done = true
	return _node, nil
}
