// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"upgradelink-admin-upgrade/server/ent/predicate"
	"upgradelink-admin-upgrade/server/ent/upgradelnxversion"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeLnxVersionUpdate is the builder for updating UpgradeLnxVersion entities.
type UpgradeLnxVersionUpdate struct {
	config
	hooks    []Hook
	mutation *UpgradeLnxVersionMutation
}

// Where appends a list predicates to the UpgradeLnxVersionUpdate builder.
func (ulvu *UpgradeLnxVersionUpdate) Where(ps ...predicate.UpgradeLnxVersion) *UpgradeLnxVersionUpdate {
	ulvu.mutation.Where(ps...)
	return ulvu
}

// SetCompanyID sets the "company_id" field.
func (ulvu *UpgradeLnxVersionUpdate) SetCompanyID(i int) *UpgradeLnxVersionUpdate {
	ulvu.mutation.ResetCompanyID()
	ulvu.mutation.SetCompanyID(i)
	return ulvu
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (ulvu *UpgradeLnxVersionUpdate) SetNillableCompanyID(i *int) *UpgradeLnxVersionUpdate {
	if i != nil {
		ulvu.SetCompanyID(*i)
	}
	return ulvu
}

// AddCompanyID adds i to the "company_id" field.
func (ulvu *UpgradeLnxVersionUpdate) AddCompanyID(i int) *UpgradeLnxVersionUpdate {
	ulvu.mutation.AddCompanyID(i)
	return ulvu
}

// SetLnxID sets the "lnx_id" field.
func (ulvu *UpgradeLnxVersionUpdate) SetLnxID(i int) *UpgradeLnxVersionUpdate {
	ulvu.mutation.ResetLnxID()
	ulvu.mutation.SetLnxID(i)
	return ulvu
}

// SetNillableLnxID sets the "lnx_id" field if the given value is not nil.
func (ulvu *UpgradeLnxVersionUpdate) SetNillableLnxID(i *int) *UpgradeLnxVersionUpdate {
	if i != nil {
		ulvu.SetLnxID(*i)
	}
	return ulvu
}

// AddLnxID adds i to the "lnx_id" field.
func (ulvu *UpgradeLnxVersionUpdate) AddLnxID(i int) *UpgradeLnxVersionUpdate {
	ulvu.mutation.AddLnxID(i)
	return ulvu
}

// SetCloudFileID sets the "cloud_file_id" field.
func (ulvu *UpgradeLnxVersionUpdate) SetCloudFileID(s string) *UpgradeLnxVersionUpdate {
	ulvu.mutation.SetCloudFileID(s)
	return ulvu
}

// SetNillableCloudFileID sets the "cloud_file_id" field if the given value is not nil.
func (ulvu *UpgradeLnxVersionUpdate) SetNillableCloudFileID(s *string) *UpgradeLnxVersionUpdate {
	if s != nil {
		ulvu.SetCloudFileID(*s)
	}
	return ulvu
}

// SetVersionName sets the "version_name" field.
func (ulvu *UpgradeLnxVersionUpdate) SetVersionName(s string) *UpgradeLnxVersionUpdate {
	ulvu.mutation.SetVersionName(s)
	return ulvu
}

// SetNillableVersionName sets the "version_name" field if the given value is not nil.
func (ulvu *UpgradeLnxVersionUpdate) SetNillableVersionName(s *string) *UpgradeLnxVersionUpdate {
	if s != nil {
		ulvu.SetVersionName(*s)
	}
	return ulvu
}

// SetVersionCode sets the "version_code" field.
func (ulvu *UpgradeLnxVersionUpdate) SetVersionCode(i int) *UpgradeLnxVersionUpdate {
	ulvu.mutation.ResetVersionCode()
	ulvu.mutation.SetVersionCode(i)
	return ulvu
}

// SetNillableVersionCode sets the "version_code" field if the given value is not nil.
func (ulvu *UpgradeLnxVersionUpdate) SetNillableVersionCode(i *int) *UpgradeLnxVersionUpdate {
	if i != nil {
		ulvu.SetVersionCode(*i)
	}
	return ulvu
}

// AddVersionCode adds i to the "version_code" field.
func (ulvu *UpgradeLnxVersionUpdate) AddVersionCode(i int) *UpgradeLnxVersionUpdate {
	ulvu.mutation.AddVersionCode(i)
	return ulvu
}

// SetArch sets the "arch" field.
func (ulvu *UpgradeLnxVersionUpdate) SetArch(s string) *UpgradeLnxVersionUpdate {
	ulvu.mutation.SetArch(s)
	return ulvu
}

// SetNillableArch sets the "arch" field if the given value is not nil.
func (ulvu *UpgradeLnxVersionUpdate) SetNillableArch(s *string) *UpgradeLnxVersionUpdate {
	if s != nil {
		ulvu.SetArch(*s)
	}
	return ulvu
}

// SetDescription sets the "description" field.
func (ulvu *UpgradeLnxVersionUpdate) SetDescription(s string) *UpgradeLnxVersionUpdate {
	ulvu.mutation.SetDescription(s)
	return ulvu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ulvu *UpgradeLnxVersionUpdate) SetNillableDescription(s *string) *UpgradeLnxVersionUpdate {
	if s != nil {
		ulvu.SetDescription(*s)
	}
	return ulvu
}

// ClearDescription clears the value of the "description" field.
func (ulvu *UpgradeLnxVersionUpdate) ClearDescription() *UpgradeLnxVersionUpdate {
	ulvu.mutation.ClearDescription()
	return ulvu
}

// SetIsDel sets the "is_del" field.
func (ulvu *UpgradeLnxVersionUpdate) SetIsDel(i int32) *UpgradeLnxVersionUpdate {
	ulvu.mutation.ResetIsDel()
	ulvu.mutation.SetIsDel(i)
	return ulvu
}

// SetNillableIsDel sets the "is_del" field if the given value is not nil.
func (ulvu *UpgradeLnxVersionUpdate) SetNillableIsDel(i *int32) *UpgradeLnxVersionUpdate {
	if i != nil {
		ulvu.SetIsDel(*i)
	}
	return ulvu
}

// AddIsDel adds i to the "is_del" field.
func (ulvu *UpgradeLnxVersionUpdate) AddIsDel(i int32) *UpgradeLnxVersionUpdate {
	ulvu.mutation.AddIsDel(i)
	return ulvu
}

// SetCreateAt sets the "create_at" field.
func (ulvu *UpgradeLnxVersionUpdate) SetCreateAt(t time.Time) *UpgradeLnxVersionUpdate {
	ulvu.mutation.SetCreateAt(t)
	return ulvu
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (ulvu *UpgradeLnxVersionUpdate) SetNillableCreateAt(t *time.Time) *UpgradeLnxVersionUpdate {
	if t != nil {
		ulvu.SetCreateAt(*t)
	}
	return ulvu
}

// ClearCreateAt clears the value of the "create_at" field.
func (ulvu *UpgradeLnxVersionUpdate) ClearCreateAt() *UpgradeLnxVersionUpdate {
	ulvu.mutation.ClearCreateAt()
	return ulvu
}

// SetUpdateAt sets the "update_at" field.
func (ulvu *UpgradeLnxVersionUpdate) SetUpdateAt(t time.Time) *UpgradeLnxVersionUpdate {
	ulvu.mutation.SetUpdateAt(t)
	return ulvu
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (ulvu *UpgradeLnxVersionUpdate) SetNillableUpdateAt(t *time.Time) *UpgradeLnxVersionUpdate {
	if t != nil {
		ulvu.SetUpdateAt(*t)
	}
	return ulvu
}

// ClearUpdateAt clears the value of the "update_at" field.
func (ulvu *UpgradeLnxVersionUpdate) ClearUpdateAt() *UpgradeLnxVersionUpdate {
	ulvu.mutation.ClearUpdateAt()
	return ulvu
}

// Mutation returns the UpgradeLnxVersionMutation object of the builder.
func (ulvu *UpgradeLnxVersionUpdate) Mutation() *UpgradeLnxVersionMutation {
	return ulvu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ulvu *UpgradeLnxVersionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ulvu.sqlSave, ulvu.mutation, ulvu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ulvu *UpgradeLnxVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := ulvu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ulvu *UpgradeLnxVersionUpdate) Exec(ctx context.Context) error {
	_, err := ulvu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ulvu *UpgradeLnxVersionUpdate) ExecX(ctx context.Context) {
	if err := ulvu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ulvu *UpgradeLnxVersionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(upgradelnxversion.Table, upgradelnxversion.Columns, sqlgraph.NewFieldSpec(upgradelnxversion.FieldID, field.TypeInt))
	if ps := ulvu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ulvu.mutation.CompanyID(); ok {
		_spec.SetField(upgradelnxversion.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := ulvu.mutation.AddedCompanyID(); ok {
		_spec.AddField(upgradelnxversion.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := ulvu.mutation.LnxID(); ok {
		_spec.SetField(upgradelnxversion.FieldLnxID, field.TypeInt, value)
	}
	if value, ok := ulvu.mutation.AddedLnxID(); ok {
		_spec.AddField(upgradelnxversion.FieldLnxID, field.TypeInt, value)
	}
	if value, ok := ulvu.mutation.CloudFileID(); ok {
		_spec.SetField(upgradelnxversion.FieldCloudFileID, field.TypeString, value)
	}
	if value, ok := ulvu.mutation.VersionName(); ok {
		_spec.SetField(upgradelnxversion.FieldVersionName, field.TypeString, value)
	}
	if value, ok := ulvu.mutation.VersionCode(); ok {
		_spec.SetField(upgradelnxversion.FieldVersionCode, field.TypeInt, value)
	}
	if value, ok := ulvu.mutation.AddedVersionCode(); ok {
		_spec.AddField(upgradelnxversion.FieldVersionCode, field.TypeInt, value)
	}
	if value, ok := ulvu.mutation.Arch(); ok {
		_spec.SetField(upgradelnxversion.FieldArch, field.TypeString, value)
	}
	if value, ok := ulvu.mutation.Description(); ok {
		_spec.SetField(upgradelnxversion.FieldDescription, field.TypeString, value)
	}
	if ulvu.mutation.DescriptionCleared() {
		_spec.ClearField(upgradelnxversion.FieldDescription, field.TypeString)
	}
	if value, ok := ulvu.mutation.IsDel(); ok {
		_spec.SetField(upgradelnxversion.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := ulvu.mutation.AddedIsDel(); ok {
		_spec.AddField(upgradelnxversion.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := ulvu.mutation.CreateAt(); ok {
		_spec.SetField(upgradelnxversion.FieldCreateAt, field.TypeTime, value)
	}
	if ulvu.mutation.CreateAtCleared() {
		_spec.ClearField(upgradelnxversion.FieldCreateAt, field.TypeTime)
	}
	if value, ok := ulvu.mutation.UpdateAt(); ok {
		_spec.SetField(upgradelnxversion.FieldUpdateAt, field.TypeTime, value)
	}
	if ulvu.mutation.UpdateAtCleared() {
		_spec.ClearField(upgradelnxversion.FieldUpdateAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ulvu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upgradelnxversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ulvu.mutation.done = true
	return n, nil
}

// UpgradeLnxVersionUpdateOne is the builder for updating a single UpgradeLnxVersion entity.
type UpgradeLnxVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpgradeLnxVersionMutation
}

// SetCompanyID sets the "company_id" field.
func (ulvuo *UpgradeLnxVersionUpdateOne) SetCompanyID(i int) *UpgradeLnxVersionUpdateOne {
	ulvuo.mutation.ResetCompanyID()
	ulvuo.mutation.SetCompanyID(i)
	return ulvuo
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (ulvuo *UpgradeLnxVersionUpdateOne) SetNillableCompanyID(i *int) *UpgradeLnxVersionUpdateOne {
	if i != nil {
		ulvuo.SetCompanyID(*i)
	}
	return ulvuo
}

// AddCompanyID adds i to the "company_id" field.
func (ulvuo *UpgradeLnxVersionUpdateOne) AddCompanyID(i int) *UpgradeLnxVersionUpdateOne {
	ulvuo.mutation.AddCompanyID(i)
	return ulvuo
}

// SetLnxID sets the "lnx_id" field.
func (ulvuo *UpgradeLnxVersionUpdateOne) SetLnxID(i int) *UpgradeLnxVersionUpdateOne {
	ulvuo.mutation.ResetLnxID()
	ulvuo.mutation.SetLnxID(i)
	return ulvuo
}

// SetNillableLnxID sets the "lnx_id" field if the given value is not nil.
func (ulvuo *UpgradeLnxVersionUpdateOne) SetNillableLnxID(i *int) *UpgradeLnxVersionUpdateOne {
	if i != nil {
		ulvuo.SetLnxID(*i)
	}
	return ulvuo
}

// AddLnxID adds i to the "lnx_id" field.
func (ulvuo *UpgradeLnxVersionUpdateOne) AddLnxID(i int) *UpgradeLnxVersionUpdateOne {
	ulvuo.mutation.AddLnxID(i)
	return ulvuo
}

// SetCloudFileID sets the "cloud_file_id" field.
func (ulvuo *UpgradeLnxVersionUpdateOne) SetCloudFileID(s string) *UpgradeLnxVersionUpdateOne {
	ulvuo.mutation.SetCloudFileID(s)
	return ulvuo
}

// SetNillableCloudFileID sets the "cloud_file_id" field if the given value is not nil.
func (ulvuo *UpgradeLnxVersionUpdateOne) SetNillableCloudFileID(s *string) *UpgradeLnxVersionUpdateOne {
	if s != nil {
		ulvuo.SetCloudFileID(*s)
	}
	return ulvuo
}

// SetVersionName sets the "version_name" field.
func (ulvuo *UpgradeLnxVersionUpdateOne) SetVersionName(s string) *UpgradeLnxVersionUpdateOne {
	ulvuo.mutation.SetVersionName(s)
	return ulvuo
}

// SetNillableVersionName sets the "version_name" field if the given value is not nil.
func (ulvuo *UpgradeLnxVersionUpdateOne) SetNillableVersionName(s *string) *UpgradeLnxVersionUpdateOne {
	if s != nil {
		ulvuo.SetVersionName(*s)
	}
	return ulvuo
}

// SetVersionCode sets the "version_code" field.
func (ulvuo *UpgradeLnxVersionUpdateOne) SetVersionCode(i int) *UpgradeLnxVersionUpdateOne {
	ulvuo.mutation.ResetVersionCode()
	ulvuo.mutation.SetVersionCode(i)
	return ulvuo
}

// SetNillableVersionCode sets the "version_code" field if the given value is not nil.
func (ulvuo *UpgradeLnxVersionUpdateOne) SetNillableVersionCode(i *int) *UpgradeLnxVersionUpdateOne {
	if i != nil {
		ulvuo.SetVersionCode(*i)
	}
	return ulvuo
}

// AddVersionCode adds i to the "version_code" field.
func (ulvuo *UpgradeLnxVersionUpdateOne) AddVersionCode(i int) *UpgradeLnxVersionUpdateOne {
	ulvuo.mutation.AddVersionCode(i)
	return ulvuo
}

// SetArch sets the "arch" field.
func (ulvuo *UpgradeLnxVersionUpdateOne) SetArch(s string) *UpgradeLnxVersionUpdateOne {
	ulvuo.mutation.SetArch(s)
	return ulvuo
}

// SetNillableArch sets the "arch" field if the given value is not nil.
func (ulvuo *UpgradeLnxVersionUpdateOne) SetNillableArch(s *string) *UpgradeLnxVersionUpdateOne {
	if s != nil {
		ulvuo.SetArch(*s)
	}
	return ulvuo
}

// SetDescription sets the "description" field.
func (ulvuo *UpgradeLnxVersionUpdateOne) SetDescription(s string) *UpgradeLnxVersionUpdateOne {
	ulvuo.mutation.SetDescription(s)
	return ulvuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ulvuo *UpgradeLnxVersionUpdateOne) SetNillableDescription(s *string) *UpgradeLnxVersionUpdateOne {
	if s != nil {
		ulvuo.SetDescription(*s)
	}
	return ulvuo
}

// ClearDescription clears the value of the "description" field.
func (ulvuo *UpgradeLnxVersionUpdateOne) ClearDescription() *UpgradeLnxVersionUpdateOne {
	ulvuo.mutation.ClearDescription()
	return ulvuo
}

// SetIsDel sets the "is_del" field.
func (ulvuo *UpgradeLnxVersionUpdateOne) SetIsDel(i int32) *UpgradeLnxVersionUpdateOne {
	ulvuo.mutation.ResetIsDel()
	ulvuo.mutation.SetIsDel(i)
	return ulvuo
}

// SetNillableIsDel sets the "is_del" field if the given value is not nil.
func (ulvuo *UpgradeLnxVersionUpdateOne) SetNillableIsDel(i *int32) *UpgradeLnxVersionUpdateOne {
	if i != nil {
		ulvuo.SetIsDel(*i)
	}
	return ulvuo
}

// AddIsDel adds i to the "is_del" field.
func (ulvuo *UpgradeLnxVersionUpdateOne) AddIsDel(i int32) *UpgradeLnxVersionUpdateOne {
	ulvuo.mutation.AddIsDel(i)
	return ulvuo
}

// SetCreateAt sets the "create_at" field.
func (ulvuo *UpgradeLnxVersionUpdateOne) SetCreateAt(t time.Time) *UpgradeLnxVersionUpdateOne {
	ulvuo.mutation.SetCreateAt(t)
	return ulvuo
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (ulvuo *UpgradeLnxVersionUpdateOne) SetNillableCreateAt(t *time.Time) *UpgradeLnxVersionUpdateOne {
	if t != nil {
		ulvuo.SetCreateAt(*t)
	}
	return ulvuo
}

// ClearCreateAt clears the value of the "create_at" field.
func (ulvuo *UpgradeLnxVersionUpdateOne) ClearCreateAt() *UpgradeLnxVersionUpdateOne {
	ulvuo.mutation.ClearCreateAt()
	return ulvuo
}

// SetUpdateAt sets the "update_at" field.
func (ulvuo *UpgradeLnxVersionUpdateOne) SetUpdateAt(t time.Time) *UpgradeLnxVersionUpdateOne {
	ulvuo.mutation.SetUpdateAt(t)
	return ulvuo
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (ulvuo *UpgradeLnxVersionUpdateOne) SetNillableUpdateAt(t *time.Time) *UpgradeLnxVersionUpdateOne {
	if t != nil {
		ulvuo.SetUpdateAt(*t)
	}
	return ulvuo
}

// ClearUpdateAt clears the value of the "update_at" field.
func (ulvuo *UpgradeLnxVersionUpdateOne) ClearUpdateAt() *UpgradeLnxVersionUpdateOne {
	ulvuo.mutation.ClearUpdateAt()
	return ulvuo
}

// Mutation returns the UpgradeLnxVersionMutation object of the builder.
func (ulvuo *UpgradeLnxVersionUpdateOne) Mutation() *UpgradeLnxVersionMutation {
	return ulvuo.mutation
}

// Where appends a list predicates to the UpgradeLnxVersionUpdate builder.
func (ulvuo *UpgradeLnxVersionUpdateOne) Where(ps ...predicate.UpgradeLnxVersion) *UpgradeLnxVersionUpdateOne {
	ulvuo.mutation.Where(ps...)
	return ulvuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ulvuo *UpgradeLnxVersionUpdateOne) Select(field string, fields ...string) *UpgradeLnxVersionUpdateOne {
	ulvuo.fields = append([]string{field}, fields...)
	return ulvuo
}

// Save executes the query and returns the updated UpgradeLnxVersion entity.
func (ulvuo *UpgradeLnxVersionUpdateOne) Save(ctx context.Context) (*UpgradeLnxVersion, error) {
	return withHooks(ctx, ulvuo.sqlSave, ulvuo.mutation, ulvuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ulvuo *UpgradeLnxVersionUpdateOne) SaveX(ctx context.Context) *UpgradeLnxVersion {
	node, err := ulvuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ulvuo *UpgradeLnxVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := ulvuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ulvuo *UpgradeLnxVersionUpdateOne) ExecX(ctx context.Context) {
	if err := ulvuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ulvuo *UpgradeLnxVersionUpdateOne) sqlSave(ctx context.Context) (_node *UpgradeLnxVersion, err error) {
	_spec := sqlgraph.NewUpdateSpec(upgradelnxversion.Table, upgradelnxversion.Columns, sqlgraph.NewFieldSpec(upgradelnxversion.FieldID, field.TypeInt))
	id, ok := ulvuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpgradeLnxVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ulvuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upgradelnxversion.FieldID)
		for _, f := range fields {
			if !upgradelnxversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upgradelnxversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ulvuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ulvuo.mutation.CompanyID(); ok {
		_spec.SetField(upgradelnxversion.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := ulvuo.mutation.AddedCompanyID(); ok {
		_spec.AddField(upgradelnxversion.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := ulvuo.mutation.LnxID(); ok {
		_spec.SetField(upgradelnxversion.FieldLnxID, field.TypeInt, value)
	}
	if value, ok := ulvuo.mutation.AddedLnxID(); ok {
		_spec.AddField(upgradelnxversion.FieldLnxID, field.TypeInt, value)
	}
	if value, ok := ulvuo.mutation.CloudFileID(); ok {
		_spec.SetField(upgradelnxversion.FieldCloudFileID, field.TypeString, value)
	}
	if value, ok := ulvuo.mutation.VersionName(); ok {
		_spec.SetField(upgradelnxversion.FieldVersionName, field.TypeString, value)
	}
	if value, ok := ulvuo.mutation.VersionCode(); ok {
		_spec.SetField(upgradelnxversion.FieldVersionCode, field.TypeInt, value)
	}
	if value, ok := ulvuo.mutation.AddedVersionCode(); ok {
		_spec.AddField(upgradelnxversion.FieldVersionCode, field.TypeInt, value)
	}
	if value, ok := ulvuo.mutation.Arch(); ok {
		_spec.SetField(upgradelnxversion.FieldArch, field.TypeString, value)
	}
	if value, ok := ulvuo.mutation.Description(); ok {
		_spec.SetField(upgradelnxversion.FieldDescription, field.TypeString, value)
	}
	if ulvuo.mutation.DescriptionCleared() {
		_spec.ClearField(upgradelnxversion.FieldDescription, field.TypeString)
	}
	if value, ok := ulvuo.mutation.IsDel(); ok {
		_spec.SetField(upgradelnxversion.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := ulvuo.mutation.AddedIsDel(); ok {
		_spec.AddField(upgradelnxversion.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := ulvuo.mutation.CreateAt(); ok {
		_spec.SetField(upgradelnxversion.FieldCreateAt, field.TypeTime, value)
	}
	if ulvuo.mutation.CreateAtCleared() {
		_spec.ClearField(upgradelnxversion.FieldCreateAt, field.TypeTime)
	}
	if value, ok := ulvuo.mutation.UpdateAt(); ok {
		_spec.SetField(upgradelnxversion.FieldUpdateAt, field.TypeTime, value)
	}
	if ulvuo.mutation.UpdateAtCleared() {
		_spec.ClearField(upgradelnxversion.FieldUpdateAt, field.TypeTime)
	}
	_node = &UpgradeLnxVersion{config: ulvuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ulvuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upgradelnxversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ulvuo.mutation.done = true
	return _node, nil
}
