// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"upgradelink-admin-upgrade/server/ent/predicate"
	"upgradelink-admin-upgrade/server/ent/upgradelnxversion"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeLnxVersionQuery is the builder for querying UpgradeLnxVersion entities.
type UpgradeLnxVersionQuery struct {
	config
	ctx        *QueryContext
	order      []upgradelnxversion.OrderOption
	inters     []Interceptor
	predicates []predicate.UpgradeLnxVersion
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UpgradeLnxVersionQuery builder.
func (ulvq *UpgradeLnxVersionQuery) Where(ps ...predicate.UpgradeLnxVersion) *UpgradeLnxVersionQuery {
	ulvq.predicates = append(ulvq.predicates, ps...)
	return ulvq
}

// Limit the number of records to be returned by this query.
func (ulvq *UpgradeLnxVersionQuery) Limit(limit int) *UpgradeLnxVersionQuery {
	ulvq.ctx.Limit = &limit
	return ulvq
}

// Offset to start from.
func (ulvq *UpgradeLnxVersionQuery) Offset(offset int) *UpgradeLnxVersionQuery {
	ulvq.ctx.Offset = &offset
	return ulvq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ulvq *UpgradeLnxVersionQuery) Unique(unique bool) *UpgradeLnxVersionQuery {
	ulvq.ctx.Unique = &unique
	return ulvq
}

// Order specifies how the records should be ordered.
func (ulvq *UpgradeLnxVersionQuery) Order(o ...upgradelnxversion.OrderOption) *UpgradeLnxVersionQuery {
	ulvq.order = append(ulvq.order, o...)
	return ulvq
}

// First returns the first UpgradeLnxVersion entity from the query.
// Returns a *NotFoundError when no UpgradeLnxVersion was found.
func (ulvq *UpgradeLnxVersionQuery) First(ctx context.Context) (*UpgradeLnxVersion, error) {
	nodes, err := ulvq.Limit(1).All(setContextOp(ctx, ulvq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{upgradelnxversion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ulvq *UpgradeLnxVersionQuery) FirstX(ctx context.Context) *UpgradeLnxVersion {
	node, err := ulvq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UpgradeLnxVersion ID from the query.
// Returns a *NotFoundError when no UpgradeLnxVersion ID was found.
func (ulvq *UpgradeLnxVersionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ulvq.Limit(1).IDs(setContextOp(ctx, ulvq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{upgradelnxversion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ulvq *UpgradeLnxVersionQuery) FirstIDX(ctx context.Context) int {
	id, err := ulvq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UpgradeLnxVersion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UpgradeLnxVersion entity is found.
// Returns a *NotFoundError when no UpgradeLnxVersion entities are found.
func (ulvq *UpgradeLnxVersionQuery) Only(ctx context.Context) (*UpgradeLnxVersion, error) {
	nodes, err := ulvq.Limit(2).All(setContextOp(ctx, ulvq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{upgradelnxversion.Label}
	default:
		return nil, &NotSingularError{upgradelnxversion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ulvq *UpgradeLnxVersionQuery) OnlyX(ctx context.Context) *UpgradeLnxVersion {
	node, err := ulvq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UpgradeLnxVersion ID in the query.
// Returns a *NotSingularError when more than one UpgradeLnxVersion ID is found.
// Returns a *NotFoundError when no entities are found.
func (ulvq *UpgradeLnxVersionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ulvq.Limit(2).IDs(setContextOp(ctx, ulvq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{upgradelnxversion.Label}
	default:
		err = &NotSingularError{upgradelnxversion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ulvq *UpgradeLnxVersionQuery) OnlyIDX(ctx context.Context) int {
	id, err := ulvq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UpgradeLnxVersions.
func (ulvq *UpgradeLnxVersionQuery) All(ctx context.Context) ([]*UpgradeLnxVersion, error) {
	ctx = setContextOp(ctx, ulvq.ctx, ent.OpQueryAll)
	if err := ulvq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UpgradeLnxVersion, *UpgradeLnxVersionQuery]()
	return withInterceptors[[]*UpgradeLnxVersion](ctx, ulvq, qr, ulvq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ulvq *UpgradeLnxVersionQuery) AllX(ctx context.Context) []*UpgradeLnxVersion {
	nodes, err := ulvq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UpgradeLnxVersion IDs.
func (ulvq *UpgradeLnxVersionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ulvq.ctx.Unique == nil && ulvq.path != nil {
		ulvq.Unique(true)
	}
	ctx = setContextOp(ctx, ulvq.ctx, ent.OpQueryIDs)
	if err = ulvq.Select(upgradelnxversion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ulvq *UpgradeLnxVersionQuery) IDsX(ctx context.Context) []int {
	ids, err := ulvq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ulvq *UpgradeLnxVersionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ulvq.ctx, ent.OpQueryCount)
	if err := ulvq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ulvq, querierCount[*UpgradeLnxVersionQuery](), ulvq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ulvq *UpgradeLnxVersionQuery) CountX(ctx context.Context) int {
	count, err := ulvq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ulvq *UpgradeLnxVersionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ulvq.ctx, ent.OpQueryExist)
	switch _, err := ulvq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ulvq *UpgradeLnxVersionQuery) ExistX(ctx context.Context) bool {
	exist, err := ulvq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UpgradeLnxVersionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ulvq *UpgradeLnxVersionQuery) Clone() *UpgradeLnxVersionQuery {
	if ulvq == nil {
		return nil
	}
	return &UpgradeLnxVersionQuery{
		config:     ulvq.config,
		ctx:        ulvq.ctx.Clone(),
		order:      append([]upgradelnxversion.OrderOption{}, ulvq.order...),
		inters:     append([]Interceptor{}, ulvq.inters...),
		predicates: append([]predicate.UpgradeLnxVersion{}, ulvq.predicates...),
		// clone intermediate query.
		sql:  ulvq.sql.Clone(),
		path: ulvq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CompanyID int `json:"company_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UpgradeLnxVersion.Query().
//		GroupBy(upgradelnxversion.FieldCompanyID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ulvq *UpgradeLnxVersionQuery) GroupBy(field string, fields ...string) *UpgradeLnxVersionGroupBy {
	ulvq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UpgradeLnxVersionGroupBy{build: ulvq}
	grbuild.flds = &ulvq.ctx.Fields
	grbuild.label = upgradelnxversion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CompanyID int `json:"company_id,omitempty"`
//	}
//
//	client.UpgradeLnxVersion.Query().
//		Select(upgradelnxversion.FieldCompanyID).
//		Scan(ctx, &v)
func (ulvq *UpgradeLnxVersionQuery) Select(fields ...string) *UpgradeLnxVersionSelect {
	ulvq.ctx.Fields = append(ulvq.ctx.Fields, fields...)
	sbuild := &UpgradeLnxVersionSelect{UpgradeLnxVersionQuery: ulvq}
	sbuild.label = upgradelnxversion.Label
	sbuild.flds, sbuild.scan = &ulvq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UpgradeLnxVersionSelect configured with the given aggregations.
func (ulvq *UpgradeLnxVersionQuery) Aggregate(fns ...AggregateFunc) *UpgradeLnxVersionSelect {
	return ulvq.Select().Aggregate(fns...)
}

func (ulvq *UpgradeLnxVersionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ulvq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ulvq); err != nil {
				return err
			}
		}
	}
	for _, f := range ulvq.ctx.Fields {
		if !upgradelnxversion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ulvq.path != nil {
		prev, err := ulvq.path(ctx)
		if err != nil {
			return err
		}
		ulvq.sql = prev
	}
	return nil
}

func (ulvq *UpgradeLnxVersionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UpgradeLnxVersion, error) {
	var (
		nodes = []*UpgradeLnxVersion{}
		_spec = ulvq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UpgradeLnxVersion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UpgradeLnxVersion{config: ulvq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ulvq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ulvq *UpgradeLnxVersionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ulvq.querySpec()
	_spec.Node.Columns = ulvq.ctx.Fields
	if len(ulvq.ctx.Fields) > 0 {
		_spec.Unique = ulvq.ctx.Unique != nil && *ulvq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ulvq.driver, _spec)
}

func (ulvq *UpgradeLnxVersionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(upgradelnxversion.Table, upgradelnxversion.Columns, sqlgraph.NewFieldSpec(upgradelnxversion.FieldID, field.TypeInt))
	_spec.From = ulvq.sql
	if unique := ulvq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ulvq.path != nil {
		_spec.Unique = true
	}
	if fields := ulvq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upgradelnxversion.FieldID)
		for i := range fields {
			if fields[i] != upgradelnxversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ulvq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ulvq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ulvq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ulvq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ulvq *UpgradeLnxVersionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ulvq.driver.Dialect())
	t1 := builder.Table(upgradelnxversion.Table)
	columns := ulvq.ctx.Fields
	if len(columns) == 0 {
		columns = upgradelnxversion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ulvq.sql != nil {
		selector = ulvq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ulvq.ctx.Unique != nil && *ulvq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ulvq.predicates {
		p(selector)
	}
	for _, p := range ulvq.order {
		p(selector)
	}
	if offset := ulvq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ulvq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UpgradeLnxVersionGroupBy is the group-by builder for UpgradeLnxVersion entities.
type UpgradeLnxVersionGroupBy struct {
	selector
	build *UpgradeLnxVersionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ulvgb *UpgradeLnxVersionGroupBy) Aggregate(fns ...AggregateFunc) *UpgradeLnxVersionGroupBy {
	ulvgb.fns = append(ulvgb.fns, fns...)
	return ulvgb
}

// Scan applies the selector query and scans the result into the given value.
func (ulvgb *UpgradeLnxVersionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ulvgb.build.ctx, ent.OpQueryGroupBy)
	if err := ulvgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpgradeLnxVersionQuery, *UpgradeLnxVersionGroupBy](ctx, ulvgb.build, ulvgb, ulvgb.build.inters, v)
}

func (ulvgb *UpgradeLnxVersionGroupBy) sqlScan(ctx context.Context, root *UpgradeLnxVersionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ulvgb.fns))
	for _, fn := range ulvgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ulvgb.flds)+len(ulvgb.fns))
		for _, f := range *ulvgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ulvgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ulvgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UpgradeLnxVersionSelect is the builder for selecting fields of UpgradeLnxVersion entities.
type UpgradeLnxVersionSelect struct {
	*UpgradeLnxVersionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ulvs *UpgradeLnxVersionSelect) Aggregate(fns ...AggregateFunc) *UpgradeLnxVersionSelect {
	ulvs.fns = append(ulvs.fns, fns...)
	return ulvs
}

// Scan applies the selector query and scans the result into the given value.
func (ulvs *UpgradeLnxVersionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ulvs.ctx, ent.OpQuerySelect)
	if err := ulvs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpgradeLnxVersionQuery, *UpgradeLnxVersionSelect](ctx, ulvs.UpgradeLnxVersionQuery, ulvs, ulvs.inters, v)
}

func (ulvs *UpgradeLnxVersionSelect) sqlScan(ctx context.Context, root *UpgradeLnxVersionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ulvs.fns))
	for _, fn := range ulvs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ulvs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ulvs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
