// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"upgradelink-admin-upgrade/server/ent/predicate"
	"upgradelink-admin-upgrade/server/ent/upgradewinupgradestrategy"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeWinUpgradeStrategyUpdate is the builder for updating UpgradeWinUpgradeStrategy entities.
type UpgradeWinUpgradeStrategyUpdate struct {
	config
	hooks    []Hook
	mutation *UpgradeWinUpgradeStrategyMutation
}

// Where appends a list predicates to the UpgradeWinUpgradeStrategyUpdate builder.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) Where(ps ...predicate.UpgradeWinUpgradeStrategy) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.Where(ps...)
	return uwusu
}

// SetCompanyID sets the "company_id" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetCompanyID(i int) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.ResetCompanyID()
	uwusu.mutation.SetCompanyID(i)
	return uwusu
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetNillableCompanyID(i *int) *UpgradeWinUpgradeStrategyUpdate {
	if i != nil {
		uwusu.SetCompanyID(*i)
	}
	return uwusu
}

// AddCompanyID adds i to the "company_id" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) AddCompanyID(i int) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.AddCompanyID(i)
	return uwusu
}

// SetEnable sets the "enable" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetEnable(i int32) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.ResetEnable()
	uwusu.mutation.SetEnable(i)
	return uwusu
}

// SetNillableEnable sets the "enable" field if the given value is not nil.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetNillableEnable(i *int32) *UpgradeWinUpgradeStrategyUpdate {
	if i != nil {
		uwusu.SetEnable(*i)
	}
	return uwusu
}

// AddEnable adds i to the "enable" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) AddEnable(i int32) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.AddEnable(i)
	return uwusu
}

// SetName sets the "name" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetName(s string) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.SetName(s)
	return uwusu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetNillableName(s *string) *UpgradeWinUpgradeStrategyUpdate {
	if s != nil {
		uwusu.SetName(*s)
	}
	return uwusu
}

// SetDescription sets the "description" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetDescription(s string) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.SetDescription(s)
	return uwusu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetNillableDescription(s *string) *UpgradeWinUpgradeStrategyUpdate {
	if s != nil {
		uwusu.SetDescription(*s)
	}
	return uwusu
}

// SetWinID sets the "win_id" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetWinID(i int) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.ResetWinID()
	uwusu.mutation.SetWinID(i)
	return uwusu
}

// SetNillableWinID sets the "win_id" field if the given value is not nil.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetNillableWinID(i *int) *UpgradeWinUpgradeStrategyUpdate {
	if i != nil {
		uwusu.SetWinID(*i)
	}
	return uwusu
}

// AddWinID adds i to the "win_id" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) AddWinID(i int) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.AddWinID(i)
	return uwusu
}

// SetWinVersionID sets the "win_version_id" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetWinVersionID(i int) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.ResetWinVersionID()
	uwusu.mutation.SetWinVersionID(i)
	return uwusu
}

// SetNillableWinVersionID sets the "win_version_id" field if the given value is not nil.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetNillableWinVersionID(i *int) *UpgradeWinUpgradeStrategyUpdate {
	if i != nil {
		uwusu.SetWinVersionID(*i)
	}
	return uwusu
}

// AddWinVersionID adds i to the "win_version_id" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) AddWinVersionID(i int) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.AddWinVersionID(i)
	return uwusu
}

// SetBeginDatetime sets the "begin_datetime" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetBeginDatetime(t time.Time) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.SetBeginDatetime(t)
	return uwusu
}

// SetNillableBeginDatetime sets the "begin_datetime" field if the given value is not nil.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetNillableBeginDatetime(t *time.Time) *UpgradeWinUpgradeStrategyUpdate {
	if t != nil {
		uwusu.SetBeginDatetime(*t)
	}
	return uwusu
}

// SetEndDatetime sets the "end_datetime" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetEndDatetime(t time.Time) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.SetEndDatetime(t)
	return uwusu
}

// SetNillableEndDatetime sets the "end_datetime" field if the given value is not nil.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetNillableEndDatetime(t *time.Time) *UpgradeWinUpgradeStrategyUpdate {
	if t != nil {
		uwusu.SetEndDatetime(*t)
	}
	return uwusu
}

// SetUpgradeType sets the "upgrade_type" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetUpgradeType(i int32) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.ResetUpgradeType()
	uwusu.mutation.SetUpgradeType(i)
	return uwusu
}

// SetNillableUpgradeType sets the "upgrade_type" field if the given value is not nil.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetNillableUpgradeType(i *int32) *UpgradeWinUpgradeStrategyUpdate {
	if i != nil {
		uwusu.SetUpgradeType(*i)
	}
	return uwusu
}

// AddUpgradeType adds i to the "upgrade_type" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) AddUpgradeType(i int32) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.AddUpgradeType(i)
	return uwusu
}

// SetPromptUpgradeContent sets the "prompt_upgrade_content" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetPromptUpgradeContent(s string) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.SetPromptUpgradeContent(s)
	return uwusu
}

// SetNillablePromptUpgradeContent sets the "prompt_upgrade_content" field if the given value is not nil.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetNillablePromptUpgradeContent(s *string) *UpgradeWinUpgradeStrategyUpdate {
	if s != nil {
		uwusu.SetPromptUpgradeContent(*s)
	}
	return uwusu
}

// SetUpgradeDevType sets the "upgrade_dev_type" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetUpgradeDevType(i int32) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.ResetUpgradeDevType()
	uwusu.mutation.SetUpgradeDevType(i)
	return uwusu
}

// SetNillableUpgradeDevType sets the "upgrade_dev_type" field if the given value is not nil.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetNillableUpgradeDevType(i *int32) *UpgradeWinUpgradeStrategyUpdate {
	if i != nil {
		uwusu.SetUpgradeDevType(*i)
	}
	return uwusu
}

// AddUpgradeDevType adds i to the "upgrade_dev_type" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) AddUpgradeDevType(i int32) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.AddUpgradeDevType(i)
	return uwusu
}

// SetUpgradeDevData sets the "upgrade_dev_data" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetUpgradeDevData(s string) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.SetUpgradeDevData(s)
	return uwusu
}

// SetNillableUpgradeDevData sets the "upgrade_dev_data" field if the given value is not nil.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetNillableUpgradeDevData(s *string) *UpgradeWinUpgradeStrategyUpdate {
	if s != nil {
		uwusu.SetUpgradeDevData(*s)
	}
	return uwusu
}

// SetUpgradeVersionType sets the "upgrade_version_type" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetUpgradeVersionType(i int32) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.ResetUpgradeVersionType()
	uwusu.mutation.SetUpgradeVersionType(i)
	return uwusu
}

// SetNillableUpgradeVersionType sets the "upgrade_version_type" field if the given value is not nil.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetNillableUpgradeVersionType(i *int32) *UpgradeWinUpgradeStrategyUpdate {
	if i != nil {
		uwusu.SetUpgradeVersionType(*i)
	}
	return uwusu
}

// AddUpgradeVersionType adds i to the "upgrade_version_type" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) AddUpgradeVersionType(i int32) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.AddUpgradeVersionType(i)
	return uwusu
}

// SetUpgradeVersionData sets the "upgrade_version_data" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetUpgradeVersionData(s string) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.SetUpgradeVersionData(s)
	return uwusu
}

// SetNillableUpgradeVersionData sets the "upgrade_version_data" field if the given value is not nil.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetNillableUpgradeVersionData(s *string) *UpgradeWinUpgradeStrategyUpdate {
	if s != nil {
		uwusu.SetUpgradeVersionData(*s)
	}
	return uwusu
}

// SetIsGray sets the "is_gray" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetIsGray(i int32) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.ResetIsGray()
	uwusu.mutation.SetIsGray(i)
	return uwusu
}

// SetNillableIsGray sets the "is_gray" field if the given value is not nil.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetNillableIsGray(i *int32) *UpgradeWinUpgradeStrategyUpdate {
	if i != nil {
		uwusu.SetIsGray(*i)
	}
	return uwusu
}

// AddIsGray adds i to the "is_gray" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) AddIsGray(i int32) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.AddIsGray(i)
	return uwusu
}

// SetGrayData sets the "gray_data" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetGrayData(s string) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.SetGrayData(s)
	return uwusu
}

// SetNillableGrayData sets the "gray_data" field if the given value is not nil.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetNillableGrayData(s *string) *UpgradeWinUpgradeStrategyUpdate {
	if s != nil {
		uwusu.SetGrayData(*s)
	}
	return uwusu
}

// SetIsFlowLimit sets the "is_flow_limit" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetIsFlowLimit(i int32) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.ResetIsFlowLimit()
	uwusu.mutation.SetIsFlowLimit(i)
	return uwusu
}

// SetNillableIsFlowLimit sets the "is_flow_limit" field if the given value is not nil.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetNillableIsFlowLimit(i *int32) *UpgradeWinUpgradeStrategyUpdate {
	if i != nil {
		uwusu.SetIsFlowLimit(*i)
	}
	return uwusu
}

// AddIsFlowLimit adds i to the "is_flow_limit" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) AddIsFlowLimit(i int32) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.AddIsFlowLimit(i)
	return uwusu
}

// SetFlowLimitData sets the "flow_limit_data" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetFlowLimitData(s string) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.SetFlowLimitData(s)
	return uwusu
}

// SetNillableFlowLimitData sets the "flow_limit_data" field if the given value is not nil.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetNillableFlowLimitData(s *string) *UpgradeWinUpgradeStrategyUpdate {
	if s != nil {
		uwusu.SetFlowLimitData(*s)
	}
	return uwusu
}

// SetIsDel sets the "is_del" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetIsDel(i int32) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.ResetIsDel()
	uwusu.mutation.SetIsDel(i)
	return uwusu
}

// SetNillableIsDel sets the "is_del" field if the given value is not nil.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetNillableIsDel(i *int32) *UpgradeWinUpgradeStrategyUpdate {
	if i != nil {
		uwusu.SetIsDel(*i)
	}
	return uwusu
}

// AddIsDel adds i to the "is_del" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) AddIsDel(i int32) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.AddIsDel(i)
	return uwusu
}

// SetCreateAt sets the "create_at" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetCreateAt(t time.Time) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.SetCreateAt(t)
	return uwusu
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetNillableCreateAt(t *time.Time) *UpgradeWinUpgradeStrategyUpdate {
	if t != nil {
		uwusu.SetCreateAt(*t)
	}
	return uwusu
}

// ClearCreateAt clears the value of the "create_at" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) ClearCreateAt() *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.ClearCreateAt()
	return uwusu
}

// SetUpdateAt sets the "update_at" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetUpdateAt(t time.Time) *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.SetUpdateAt(t)
	return uwusu
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SetNillableUpdateAt(t *time.Time) *UpgradeWinUpgradeStrategyUpdate {
	if t != nil {
		uwusu.SetUpdateAt(*t)
	}
	return uwusu
}

// ClearUpdateAt clears the value of the "update_at" field.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) ClearUpdateAt() *UpgradeWinUpgradeStrategyUpdate {
	uwusu.mutation.ClearUpdateAt()
	return uwusu
}

// Mutation returns the UpgradeWinUpgradeStrategyMutation object of the builder.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) Mutation() *UpgradeWinUpgradeStrategyMutation {
	return uwusu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, uwusu.sqlSave, uwusu.mutation, uwusu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) SaveX(ctx context.Context) int {
	affected, err := uwusu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) Exec(ctx context.Context) error {
	_, err := uwusu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uwusu *UpgradeWinUpgradeStrategyUpdate) ExecX(ctx context.Context) {
	if err := uwusu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uwusu *UpgradeWinUpgradeStrategyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(upgradewinupgradestrategy.Table, upgradewinupgradestrategy.Columns, sqlgraph.NewFieldSpec(upgradewinupgradestrategy.FieldID, field.TypeInt))
	if ps := uwusu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uwusu.mutation.CompanyID(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := uwusu.mutation.AddedCompanyID(); ok {
		_spec.AddField(upgradewinupgradestrategy.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := uwusu.mutation.Enable(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldEnable, field.TypeInt32, value)
	}
	if value, ok := uwusu.mutation.AddedEnable(); ok {
		_spec.AddField(upgradewinupgradestrategy.FieldEnable, field.TypeInt32, value)
	}
	if value, ok := uwusu.mutation.Name(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldName, field.TypeString, value)
	}
	if value, ok := uwusu.mutation.Description(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldDescription, field.TypeString, value)
	}
	if value, ok := uwusu.mutation.WinID(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldWinID, field.TypeInt, value)
	}
	if value, ok := uwusu.mutation.AddedWinID(); ok {
		_spec.AddField(upgradewinupgradestrategy.FieldWinID, field.TypeInt, value)
	}
	if value, ok := uwusu.mutation.WinVersionID(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldWinVersionID, field.TypeInt, value)
	}
	if value, ok := uwusu.mutation.AddedWinVersionID(); ok {
		_spec.AddField(upgradewinupgradestrategy.FieldWinVersionID, field.TypeInt, value)
	}
	if value, ok := uwusu.mutation.BeginDatetime(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldBeginDatetime, field.TypeTime, value)
	}
	if value, ok := uwusu.mutation.EndDatetime(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldEndDatetime, field.TypeTime, value)
	}
	if value, ok := uwusu.mutation.UpgradeType(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldUpgradeType, field.TypeInt32, value)
	}
	if value, ok := uwusu.mutation.AddedUpgradeType(); ok {
		_spec.AddField(upgradewinupgradestrategy.FieldUpgradeType, field.TypeInt32, value)
	}
	if value, ok := uwusu.mutation.PromptUpgradeContent(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldPromptUpgradeContent, field.TypeString, value)
	}
	if value, ok := uwusu.mutation.UpgradeDevType(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldUpgradeDevType, field.TypeInt32, value)
	}
	if value, ok := uwusu.mutation.AddedUpgradeDevType(); ok {
		_spec.AddField(upgradewinupgradestrategy.FieldUpgradeDevType, field.TypeInt32, value)
	}
	if value, ok := uwusu.mutation.UpgradeDevData(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldUpgradeDevData, field.TypeString, value)
	}
	if value, ok := uwusu.mutation.UpgradeVersionType(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldUpgradeVersionType, field.TypeInt32, value)
	}
	if value, ok := uwusu.mutation.AddedUpgradeVersionType(); ok {
		_spec.AddField(upgradewinupgradestrategy.FieldUpgradeVersionType, field.TypeInt32, value)
	}
	if value, ok := uwusu.mutation.UpgradeVersionData(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldUpgradeVersionData, field.TypeString, value)
	}
	if value, ok := uwusu.mutation.IsGray(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldIsGray, field.TypeInt32, value)
	}
	if value, ok := uwusu.mutation.AddedIsGray(); ok {
		_spec.AddField(upgradewinupgradestrategy.FieldIsGray, field.TypeInt32, value)
	}
	if value, ok := uwusu.mutation.GrayData(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldGrayData, field.TypeString, value)
	}
	if value, ok := uwusu.mutation.IsFlowLimit(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldIsFlowLimit, field.TypeInt32, value)
	}
	if value, ok := uwusu.mutation.AddedIsFlowLimit(); ok {
		_spec.AddField(upgradewinupgradestrategy.FieldIsFlowLimit, field.TypeInt32, value)
	}
	if value, ok := uwusu.mutation.FlowLimitData(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldFlowLimitData, field.TypeString, value)
	}
	if value, ok := uwusu.mutation.IsDel(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := uwusu.mutation.AddedIsDel(); ok {
		_spec.AddField(upgradewinupgradestrategy.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := uwusu.mutation.CreateAt(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldCreateAt, field.TypeTime, value)
	}
	if uwusu.mutation.CreateAtCleared() {
		_spec.ClearField(upgradewinupgradestrategy.FieldCreateAt, field.TypeTime)
	}
	if value, ok := uwusu.mutation.UpdateAt(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldUpdateAt, field.TypeTime, value)
	}
	if uwusu.mutation.UpdateAtCleared() {
		_spec.ClearField(upgradewinupgradestrategy.FieldUpdateAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uwusu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upgradewinupgradestrategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uwusu.mutation.done = true
	return n, nil
}

// UpgradeWinUpgradeStrategyUpdateOne is the builder for updating a single UpgradeWinUpgradeStrategy entity.
type UpgradeWinUpgradeStrategyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpgradeWinUpgradeStrategyMutation
}

// SetCompanyID sets the "company_id" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetCompanyID(i int) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.ResetCompanyID()
	uwusuo.mutation.SetCompanyID(i)
	return uwusuo
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetNillableCompanyID(i *int) *UpgradeWinUpgradeStrategyUpdateOne {
	if i != nil {
		uwusuo.SetCompanyID(*i)
	}
	return uwusuo
}

// AddCompanyID adds i to the "company_id" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) AddCompanyID(i int) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.AddCompanyID(i)
	return uwusuo
}

// SetEnable sets the "enable" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetEnable(i int32) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.ResetEnable()
	uwusuo.mutation.SetEnable(i)
	return uwusuo
}

// SetNillableEnable sets the "enable" field if the given value is not nil.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetNillableEnable(i *int32) *UpgradeWinUpgradeStrategyUpdateOne {
	if i != nil {
		uwusuo.SetEnable(*i)
	}
	return uwusuo
}

// AddEnable adds i to the "enable" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) AddEnable(i int32) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.AddEnable(i)
	return uwusuo
}

// SetName sets the "name" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetName(s string) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.SetName(s)
	return uwusuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetNillableName(s *string) *UpgradeWinUpgradeStrategyUpdateOne {
	if s != nil {
		uwusuo.SetName(*s)
	}
	return uwusuo
}

// SetDescription sets the "description" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetDescription(s string) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.SetDescription(s)
	return uwusuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetNillableDescription(s *string) *UpgradeWinUpgradeStrategyUpdateOne {
	if s != nil {
		uwusuo.SetDescription(*s)
	}
	return uwusuo
}

// SetWinID sets the "win_id" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetWinID(i int) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.ResetWinID()
	uwusuo.mutation.SetWinID(i)
	return uwusuo
}

// SetNillableWinID sets the "win_id" field if the given value is not nil.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetNillableWinID(i *int) *UpgradeWinUpgradeStrategyUpdateOne {
	if i != nil {
		uwusuo.SetWinID(*i)
	}
	return uwusuo
}

// AddWinID adds i to the "win_id" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) AddWinID(i int) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.AddWinID(i)
	return uwusuo
}

// SetWinVersionID sets the "win_version_id" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetWinVersionID(i int) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.ResetWinVersionID()
	uwusuo.mutation.SetWinVersionID(i)
	return uwusuo
}

// SetNillableWinVersionID sets the "win_version_id" field if the given value is not nil.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetNillableWinVersionID(i *int) *UpgradeWinUpgradeStrategyUpdateOne {
	if i != nil {
		uwusuo.SetWinVersionID(*i)
	}
	return uwusuo
}

// AddWinVersionID adds i to the "win_version_id" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) AddWinVersionID(i int) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.AddWinVersionID(i)
	return uwusuo
}

// SetBeginDatetime sets the "begin_datetime" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetBeginDatetime(t time.Time) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.SetBeginDatetime(t)
	return uwusuo
}

// SetNillableBeginDatetime sets the "begin_datetime" field if the given value is not nil.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetNillableBeginDatetime(t *time.Time) *UpgradeWinUpgradeStrategyUpdateOne {
	if t != nil {
		uwusuo.SetBeginDatetime(*t)
	}
	return uwusuo
}

// SetEndDatetime sets the "end_datetime" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetEndDatetime(t time.Time) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.SetEndDatetime(t)
	return uwusuo
}

// SetNillableEndDatetime sets the "end_datetime" field if the given value is not nil.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetNillableEndDatetime(t *time.Time) *UpgradeWinUpgradeStrategyUpdateOne {
	if t != nil {
		uwusuo.SetEndDatetime(*t)
	}
	return uwusuo
}

// SetUpgradeType sets the "upgrade_type" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetUpgradeType(i int32) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.ResetUpgradeType()
	uwusuo.mutation.SetUpgradeType(i)
	return uwusuo
}

// SetNillableUpgradeType sets the "upgrade_type" field if the given value is not nil.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetNillableUpgradeType(i *int32) *UpgradeWinUpgradeStrategyUpdateOne {
	if i != nil {
		uwusuo.SetUpgradeType(*i)
	}
	return uwusuo
}

// AddUpgradeType adds i to the "upgrade_type" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) AddUpgradeType(i int32) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.AddUpgradeType(i)
	return uwusuo
}

// SetPromptUpgradeContent sets the "prompt_upgrade_content" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetPromptUpgradeContent(s string) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.SetPromptUpgradeContent(s)
	return uwusuo
}

// SetNillablePromptUpgradeContent sets the "prompt_upgrade_content" field if the given value is not nil.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetNillablePromptUpgradeContent(s *string) *UpgradeWinUpgradeStrategyUpdateOne {
	if s != nil {
		uwusuo.SetPromptUpgradeContent(*s)
	}
	return uwusuo
}

// SetUpgradeDevType sets the "upgrade_dev_type" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetUpgradeDevType(i int32) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.ResetUpgradeDevType()
	uwusuo.mutation.SetUpgradeDevType(i)
	return uwusuo
}

// SetNillableUpgradeDevType sets the "upgrade_dev_type" field if the given value is not nil.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetNillableUpgradeDevType(i *int32) *UpgradeWinUpgradeStrategyUpdateOne {
	if i != nil {
		uwusuo.SetUpgradeDevType(*i)
	}
	return uwusuo
}

// AddUpgradeDevType adds i to the "upgrade_dev_type" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) AddUpgradeDevType(i int32) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.AddUpgradeDevType(i)
	return uwusuo
}

// SetUpgradeDevData sets the "upgrade_dev_data" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetUpgradeDevData(s string) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.SetUpgradeDevData(s)
	return uwusuo
}

// SetNillableUpgradeDevData sets the "upgrade_dev_data" field if the given value is not nil.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetNillableUpgradeDevData(s *string) *UpgradeWinUpgradeStrategyUpdateOne {
	if s != nil {
		uwusuo.SetUpgradeDevData(*s)
	}
	return uwusuo
}

// SetUpgradeVersionType sets the "upgrade_version_type" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetUpgradeVersionType(i int32) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.ResetUpgradeVersionType()
	uwusuo.mutation.SetUpgradeVersionType(i)
	return uwusuo
}

// SetNillableUpgradeVersionType sets the "upgrade_version_type" field if the given value is not nil.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetNillableUpgradeVersionType(i *int32) *UpgradeWinUpgradeStrategyUpdateOne {
	if i != nil {
		uwusuo.SetUpgradeVersionType(*i)
	}
	return uwusuo
}

// AddUpgradeVersionType adds i to the "upgrade_version_type" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) AddUpgradeVersionType(i int32) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.AddUpgradeVersionType(i)
	return uwusuo
}

// SetUpgradeVersionData sets the "upgrade_version_data" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetUpgradeVersionData(s string) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.SetUpgradeVersionData(s)
	return uwusuo
}

// SetNillableUpgradeVersionData sets the "upgrade_version_data" field if the given value is not nil.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetNillableUpgradeVersionData(s *string) *UpgradeWinUpgradeStrategyUpdateOne {
	if s != nil {
		uwusuo.SetUpgradeVersionData(*s)
	}
	return uwusuo
}

// SetIsGray sets the "is_gray" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetIsGray(i int32) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.ResetIsGray()
	uwusuo.mutation.SetIsGray(i)
	return uwusuo
}

// SetNillableIsGray sets the "is_gray" field if the given value is not nil.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetNillableIsGray(i *int32) *UpgradeWinUpgradeStrategyUpdateOne {
	if i != nil {
		uwusuo.SetIsGray(*i)
	}
	return uwusuo
}

// AddIsGray adds i to the "is_gray" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) AddIsGray(i int32) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.AddIsGray(i)
	return uwusuo
}

// SetGrayData sets the "gray_data" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetGrayData(s string) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.SetGrayData(s)
	return uwusuo
}

// SetNillableGrayData sets the "gray_data" field if the given value is not nil.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetNillableGrayData(s *string) *UpgradeWinUpgradeStrategyUpdateOne {
	if s != nil {
		uwusuo.SetGrayData(*s)
	}
	return uwusuo
}

// SetIsFlowLimit sets the "is_flow_limit" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetIsFlowLimit(i int32) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.ResetIsFlowLimit()
	uwusuo.mutation.SetIsFlowLimit(i)
	return uwusuo
}

// SetNillableIsFlowLimit sets the "is_flow_limit" field if the given value is not nil.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetNillableIsFlowLimit(i *int32) *UpgradeWinUpgradeStrategyUpdateOne {
	if i != nil {
		uwusuo.SetIsFlowLimit(*i)
	}
	return uwusuo
}

// AddIsFlowLimit adds i to the "is_flow_limit" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) AddIsFlowLimit(i int32) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.AddIsFlowLimit(i)
	return uwusuo
}

// SetFlowLimitData sets the "flow_limit_data" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetFlowLimitData(s string) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.SetFlowLimitData(s)
	return uwusuo
}

// SetNillableFlowLimitData sets the "flow_limit_data" field if the given value is not nil.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetNillableFlowLimitData(s *string) *UpgradeWinUpgradeStrategyUpdateOne {
	if s != nil {
		uwusuo.SetFlowLimitData(*s)
	}
	return uwusuo
}

// SetIsDel sets the "is_del" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetIsDel(i int32) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.ResetIsDel()
	uwusuo.mutation.SetIsDel(i)
	return uwusuo
}

// SetNillableIsDel sets the "is_del" field if the given value is not nil.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetNillableIsDel(i *int32) *UpgradeWinUpgradeStrategyUpdateOne {
	if i != nil {
		uwusuo.SetIsDel(*i)
	}
	return uwusuo
}

// AddIsDel adds i to the "is_del" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) AddIsDel(i int32) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.AddIsDel(i)
	return uwusuo
}

// SetCreateAt sets the "create_at" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetCreateAt(t time.Time) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.SetCreateAt(t)
	return uwusuo
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetNillableCreateAt(t *time.Time) *UpgradeWinUpgradeStrategyUpdateOne {
	if t != nil {
		uwusuo.SetCreateAt(*t)
	}
	return uwusuo
}

// ClearCreateAt clears the value of the "create_at" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) ClearCreateAt() *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.ClearCreateAt()
	return uwusuo
}

// SetUpdateAt sets the "update_at" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetUpdateAt(t time.Time) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.SetUpdateAt(t)
	return uwusuo
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SetNillableUpdateAt(t *time.Time) *UpgradeWinUpgradeStrategyUpdateOne {
	if t != nil {
		uwusuo.SetUpdateAt(*t)
	}
	return uwusuo
}

// ClearUpdateAt clears the value of the "update_at" field.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) ClearUpdateAt() *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.ClearUpdateAt()
	return uwusuo
}

// Mutation returns the UpgradeWinUpgradeStrategyMutation object of the builder.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) Mutation() *UpgradeWinUpgradeStrategyMutation {
	return uwusuo.mutation
}

// Where appends a list predicates to the UpgradeWinUpgradeStrategyUpdate builder.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) Where(ps ...predicate.UpgradeWinUpgradeStrategy) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.mutation.Where(ps...)
	return uwusuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) Select(field string, fields ...string) *UpgradeWinUpgradeStrategyUpdateOne {
	uwusuo.fields = append([]string{field}, fields...)
	return uwusuo
}

// Save executes the query and returns the updated UpgradeWinUpgradeStrategy entity.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) Save(ctx context.Context) (*UpgradeWinUpgradeStrategy, error) {
	return withHooks(ctx, uwusuo.sqlSave, uwusuo.mutation, uwusuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) SaveX(ctx context.Context) *UpgradeWinUpgradeStrategy {
	node, err := uwusuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) Exec(ctx context.Context) error {
	_, err := uwusuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) ExecX(ctx context.Context) {
	if err := uwusuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uwusuo *UpgradeWinUpgradeStrategyUpdateOne) sqlSave(ctx context.Context) (_node *UpgradeWinUpgradeStrategy, err error) {
	_spec := sqlgraph.NewUpdateSpec(upgradewinupgradestrategy.Table, upgradewinupgradestrategy.Columns, sqlgraph.NewFieldSpec(upgradewinupgradestrategy.FieldID, field.TypeInt))
	id, ok := uwusuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpgradeWinUpgradeStrategy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uwusuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upgradewinupgradestrategy.FieldID)
		for _, f := range fields {
			if !upgradewinupgradestrategy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upgradewinupgradestrategy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uwusuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uwusuo.mutation.CompanyID(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := uwusuo.mutation.AddedCompanyID(); ok {
		_spec.AddField(upgradewinupgradestrategy.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := uwusuo.mutation.Enable(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldEnable, field.TypeInt32, value)
	}
	if value, ok := uwusuo.mutation.AddedEnable(); ok {
		_spec.AddField(upgradewinupgradestrategy.FieldEnable, field.TypeInt32, value)
	}
	if value, ok := uwusuo.mutation.Name(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldName, field.TypeString, value)
	}
	if value, ok := uwusuo.mutation.Description(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldDescription, field.TypeString, value)
	}
	if value, ok := uwusuo.mutation.WinID(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldWinID, field.TypeInt, value)
	}
	if value, ok := uwusuo.mutation.AddedWinID(); ok {
		_spec.AddField(upgradewinupgradestrategy.FieldWinID, field.TypeInt, value)
	}
	if value, ok := uwusuo.mutation.WinVersionID(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldWinVersionID, field.TypeInt, value)
	}
	if value, ok := uwusuo.mutation.AddedWinVersionID(); ok {
		_spec.AddField(upgradewinupgradestrategy.FieldWinVersionID, field.TypeInt, value)
	}
	if value, ok := uwusuo.mutation.BeginDatetime(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldBeginDatetime, field.TypeTime, value)
	}
	if value, ok := uwusuo.mutation.EndDatetime(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldEndDatetime, field.TypeTime, value)
	}
	if value, ok := uwusuo.mutation.UpgradeType(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldUpgradeType, field.TypeInt32, value)
	}
	if value, ok := uwusuo.mutation.AddedUpgradeType(); ok {
		_spec.AddField(upgradewinupgradestrategy.FieldUpgradeType, field.TypeInt32, value)
	}
	if value, ok := uwusuo.mutation.PromptUpgradeContent(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldPromptUpgradeContent, field.TypeString, value)
	}
	if value, ok := uwusuo.mutation.UpgradeDevType(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldUpgradeDevType, field.TypeInt32, value)
	}
	if value, ok := uwusuo.mutation.AddedUpgradeDevType(); ok {
		_spec.AddField(upgradewinupgradestrategy.FieldUpgradeDevType, field.TypeInt32, value)
	}
	if value, ok := uwusuo.mutation.UpgradeDevData(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldUpgradeDevData, field.TypeString, value)
	}
	if value, ok := uwusuo.mutation.UpgradeVersionType(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldUpgradeVersionType, field.TypeInt32, value)
	}
	if value, ok := uwusuo.mutation.AddedUpgradeVersionType(); ok {
		_spec.AddField(upgradewinupgradestrategy.FieldUpgradeVersionType, field.TypeInt32, value)
	}
	if value, ok := uwusuo.mutation.UpgradeVersionData(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldUpgradeVersionData, field.TypeString, value)
	}
	if value, ok := uwusuo.mutation.IsGray(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldIsGray, field.TypeInt32, value)
	}
	if value, ok := uwusuo.mutation.AddedIsGray(); ok {
		_spec.AddField(upgradewinupgradestrategy.FieldIsGray, field.TypeInt32, value)
	}
	if value, ok := uwusuo.mutation.GrayData(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldGrayData, field.TypeString, value)
	}
	if value, ok := uwusuo.mutation.IsFlowLimit(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldIsFlowLimit, field.TypeInt32, value)
	}
	if value, ok := uwusuo.mutation.AddedIsFlowLimit(); ok {
		_spec.AddField(upgradewinupgradestrategy.FieldIsFlowLimit, field.TypeInt32, value)
	}
	if value, ok := uwusuo.mutation.FlowLimitData(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldFlowLimitData, field.TypeString, value)
	}
	if value, ok := uwusuo.mutation.IsDel(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := uwusuo.mutation.AddedIsDel(); ok {
		_spec.AddField(upgradewinupgradestrategy.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := uwusuo.mutation.CreateAt(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldCreateAt, field.TypeTime, value)
	}
	if uwusuo.mutation.CreateAtCleared() {
		_spec.ClearField(upgradewinupgradestrategy.FieldCreateAt, field.TypeTime)
	}
	if value, ok := uwusuo.mutation.UpdateAt(); ok {
		_spec.SetField(upgradewinupgradestrategy.FieldUpdateAt, field.TypeTime, value)
	}
	if uwusuo.mutation.UpdateAtCleared() {
		_spec.ClearField(upgradewinupgradestrategy.FieldUpdateAt, field.TypeTime)
	}
	_node = &UpgradeWinUpgradeStrategy{config: uwusuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uwusuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upgradewinupgradestrategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uwusuo.mutation.done = true
	return _node, nil
}
