// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"upgradelink-admin-upgrade/server/ent/predicate"
	"upgradelink-admin-upgrade/server/ent/upgradewinupgradestrategyflowlimitstrategy"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeWinUpgradeStrategyFlowLimitStrategyDelete is the builder for deleting a UpgradeWinUpgradeStrategyFlowLimitStrategy entity.
type UpgradeWinUpgradeStrategyFlowLimitStrategyDelete struct {
	config
	hooks    []Hook
	mutation *UpgradeWinUpgradeStrategyFlowLimitStrategyMutation
}

// Where appends a list predicates to the UpgradeWinUpgradeStrategyFlowLimitStrategyDelete builder.
func (uwusflsd *UpgradeWinUpgradeStrategyFlowLimitStrategyDelete) Where(ps ...predicate.UpgradeWinUpgradeStrategyFlowLimitStrategy) *UpgradeWinUpgradeStrategyFlowLimitStrategyDelete {
	uwusflsd.mutation.Where(ps...)
	return uwusflsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uwusflsd *UpgradeWinUpgradeStrategyFlowLimitStrategyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, uwusflsd.sqlExec, uwusflsd.mutation, uwusflsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (uwusflsd *UpgradeWinUpgradeStrategyFlowLimitStrategyDelete) ExecX(ctx context.Context) int {
	n, err := uwusflsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uwusflsd *UpgradeWinUpgradeStrategyFlowLimitStrategyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(upgradewinupgradestrategyflowlimitstrategy.Table, sqlgraph.NewFieldSpec(upgradewinupgradestrategyflowlimitstrategy.FieldID, field.TypeInt))
	if ps := uwusflsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, uwusflsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	uwusflsd.mutation.done = true
	return affected, err
}

// UpgradeWinUpgradeStrategyFlowLimitStrategyDeleteOne is the builder for deleting a single UpgradeWinUpgradeStrategyFlowLimitStrategy entity.
type UpgradeWinUpgradeStrategyFlowLimitStrategyDeleteOne struct {
	uwusflsd *UpgradeWinUpgradeStrategyFlowLimitStrategyDelete
}

// Where appends a list predicates to the UpgradeWinUpgradeStrategyFlowLimitStrategyDelete builder.
func (uwusflsdo *UpgradeWinUpgradeStrategyFlowLimitStrategyDeleteOne) Where(ps ...predicate.UpgradeWinUpgradeStrategyFlowLimitStrategy) *UpgradeWinUpgradeStrategyFlowLimitStrategyDeleteOne {
	uwusflsdo.uwusflsd.mutation.Where(ps...)
	return uwusflsdo
}

// Exec executes the deletion query.
func (uwusflsdo *UpgradeWinUpgradeStrategyFlowLimitStrategyDeleteOne) Exec(ctx context.Context) error {
	n, err := uwusflsdo.uwusflsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{upgradewinupgradestrategyflowlimitstrategy.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uwusflsdo *UpgradeWinUpgradeStrategyFlowLimitStrategyDeleteOne) ExecX(ctx context.Context) {
	if err := uwusflsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
