// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"upgradelink-admin-upgrade/server/ent/predicate"
	"upgradelink-admin-upgrade/server/ent/upgradewinupgradestrategy"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeWinUpgradeStrategyQuery is the builder for querying UpgradeWinUpgradeStrategy entities.
type UpgradeWinUpgradeStrategyQuery struct {
	config
	ctx        *QueryContext
	order      []upgradewinupgradestrategy.OrderOption
	inters     []Interceptor
	predicates []predicate.UpgradeWinUpgradeStrategy
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UpgradeWinUpgradeStrategyQuery builder.
func (uwusq *UpgradeWinUpgradeStrategyQuery) Where(ps ...predicate.UpgradeWinUpgradeStrategy) *UpgradeWinUpgradeStrategyQuery {
	uwusq.predicates = append(uwusq.predicates, ps...)
	return uwusq
}

// Limit the number of records to be returned by this query.
func (uwusq *UpgradeWinUpgradeStrategyQuery) Limit(limit int) *UpgradeWinUpgradeStrategyQuery {
	uwusq.ctx.Limit = &limit
	return uwusq
}

// Offset to start from.
func (uwusq *UpgradeWinUpgradeStrategyQuery) Offset(offset int) *UpgradeWinUpgradeStrategyQuery {
	uwusq.ctx.Offset = &offset
	return uwusq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uwusq *UpgradeWinUpgradeStrategyQuery) Unique(unique bool) *UpgradeWinUpgradeStrategyQuery {
	uwusq.ctx.Unique = &unique
	return uwusq
}

// Order specifies how the records should be ordered.
func (uwusq *UpgradeWinUpgradeStrategyQuery) Order(o ...upgradewinupgradestrategy.OrderOption) *UpgradeWinUpgradeStrategyQuery {
	uwusq.order = append(uwusq.order, o...)
	return uwusq
}

// First returns the first UpgradeWinUpgradeStrategy entity from the query.
// Returns a *NotFoundError when no UpgradeWinUpgradeStrategy was found.
func (uwusq *UpgradeWinUpgradeStrategyQuery) First(ctx context.Context) (*UpgradeWinUpgradeStrategy, error) {
	nodes, err := uwusq.Limit(1).All(setContextOp(ctx, uwusq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{upgradewinupgradestrategy.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uwusq *UpgradeWinUpgradeStrategyQuery) FirstX(ctx context.Context) *UpgradeWinUpgradeStrategy {
	node, err := uwusq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UpgradeWinUpgradeStrategy ID from the query.
// Returns a *NotFoundError when no UpgradeWinUpgradeStrategy ID was found.
func (uwusq *UpgradeWinUpgradeStrategyQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uwusq.Limit(1).IDs(setContextOp(ctx, uwusq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{upgradewinupgradestrategy.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uwusq *UpgradeWinUpgradeStrategyQuery) FirstIDX(ctx context.Context) int {
	id, err := uwusq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UpgradeWinUpgradeStrategy entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UpgradeWinUpgradeStrategy entity is found.
// Returns a *NotFoundError when no UpgradeWinUpgradeStrategy entities are found.
func (uwusq *UpgradeWinUpgradeStrategyQuery) Only(ctx context.Context) (*UpgradeWinUpgradeStrategy, error) {
	nodes, err := uwusq.Limit(2).All(setContextOp(ctx, uwusq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{upgradewinupgradestrategy.Label}
	default:
		return nil, &NotSingularError{upgradewinupgradestrategy.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uwusq *UpgradeWinUpgradeStrategyQuery) OnlyX(ctx context.Context) *UpgradeWinUpgradeStrategy {
	node, err := uwusq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UpgradeWinUpgradeStrategy ID in the query.
// Returns a *NotSingularError when more than one UpgradeWinUpgradeStrategy ID is found.
// Returns a *NotFoundError when no entities are found.
func (uwusq *UpgradeWinUpgradeStrategyQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uwusq.Limit(2).IDs(setContextOp(ctx, uwusq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{upgradewinupgradestrategy.Label}
	default:
		err = &NotSingularError{upgradewinupgradestrategy.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uwusq *UpgradeWinUpgradeStrategyQuery) OnlyIDX(ctx context.Context) int {
	id, err := uwusq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UpgradeWinUpgradeStrategies.
func (uwusq *UpgradeWinUpgradeStrategyQuery) All(ctx context.Context) ([]*UpgradeWinUpgradeStrategy, error) {
	ctx = setContextOp(ctx, uwusq.ctx, ent.OpQueryAll)
	if err := uwusq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UpgradeWinUpgradeStrategy, *UpgradeWinUpgradeStrategyQuery]()
	return withInterceptors[[]*UpgradeWinUpgradeStrategy](ctx, uwusq, qr, uwusq.inters)
}

// AllX is like All, but panics if an error occurs.
func (uwusq *UpgradeWinUpgradeStrategyQuery) AllX(ctx context.Context) []*UpgradeWinUpgradeStrategy {
	nodes, err := uwusq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UpgradeWinUpgradeStrategy IDs.
func (uwusq *UpgradeWinUpgradeStrategyQuery) IDs(ctx context.Context) (ids []int, err error) {
	if uwusq.ctx.Unique == nil && uwusq.path != nil {
		uwusq.Unique(true)
	}
	ctx = setContextOp(ctx, uwusq.ctx, ent.OpQueryIDs)
	if err = uwusq.Select(upgradewinupgradestrategy.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uwusq *UpgradeWinUpgradeStrategyQuery) IDsX(ctx context.Context) []int {
	ids, err := uwusq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uwusq *UpgradeWinUpgradeStrategyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, uwusq.ctx, ent.OpQueryCount)
	if err := uwusq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, uwusq, querierCount[*UpgradeWinUpgradeStrategyQuery](), uwusq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (uwusq *UpgradeWinUpgradeStrategyQuery) CountX(ctx context.Context) int {
	count, err := uwusq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uwusq *UpgradeWinUpgradeStrategyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, uwusq.ctx, ent.OpQueryExist)
	switch _, err := uwusq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (uwusq *UpgradeWinUpgradeStrategyQuery) ExistX(ctx context.Context) bool {
	exist, err := uwusq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UpgradeWinUpgradeStrategyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uwusq *UpgradeWinUpgradeStrategyQuery) Clone() *UpgradeWinUpgradeStrategyQuery {
	if uwusq == nil {
		return nil
	}
	return &UpgradeWinUpgradeStrategyQuery{
		config:     uwusq.config,
		ctx:        uwusq.ctx.Clone(),
		order:      append([]upgradewinupgradestrategy.OrderOption{}, uwusq.order...),
		inters:     append([]Interceptor{}, uwusq.inters...),
		predicates: append([]predicate.UpgradeWinUpgradeStrategy{}, uwusq.predicates...),
		// clone intermediate query.
		sql:  uwusq.sql.Clone(),
		path: uwusq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CompanyID int `json:"company_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UpgradeWinUpgradeStrategy.Query().
//		GroupBy(upgradewinupgradestrategy.FieldCompanyID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (uwusq *UpgradeWinUpgradeStrategyQuery) GroupBy(field string, fields ...string) *UpgradeWinUpgradeStrategyGroupBy {
	uwusq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UpgradeWinUpgradeStrategyGroupBy{build: uwusq}
	grbuild.flds = &uwusq.ctx.Fields
	grbuild.label = upgradewinupgradestrategy.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CompanyID int `json:"company_id,omitempty"`
//	}
//
//	client.UpgradeWinUpgradeStrategy.Query().
//		Select(upgradewinupgradestrategy.FieldCompanyID).
//		Scan(ctx, &v)
func (uwusq *UpgradeWinUpgradeStrategyQuery) Select(fields ...string) *UpgradeWinUpgradeStrategySelect {
	uwusq.ctx.Fields = append(uwusq.ctx.Fields, fields...)
	sbuild := &UpgradeWinUpgradeStrategySelect{UpgradeWinUpgradeStrategyQuery: uwusq}
	sbuild.label = upgradewinupgradestrategy.Label
	sbuild.flds, sbuild.scan = &uwusq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UpgradeWinUpgradeStrategySelect configured with the given aggregations.
func (uwusq *UpgradeWinUpgradeStrategyQuery) Aggregate(fns ...AggregateFunc) *UpgradeWinUpgradeStrategySelect {
	return uwusq.Select().Aggregate(fns...)
}

func (uwusq *UpgradeWinUpgradeStrategyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range uwusq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, uwusq); err != nil {
				return err
			}
		}
	}
	for _, f := range uwusq.ctx.Fields {
		if !upgradewinupgradestrategy.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uwusq.path != nil {
		prev, err := uwusq.path(ctx)
		if err != nil {
			return err
		}
		uwusq.sql = prev
	}
	return nil
}

func (uwusq *UpgradeWinUpgradeStrategyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UpgradeWinUpgradeStrategy, error) {
	var (
		nodes = []*UpgradeWinUpgradeStrategy{}
		_spec = uwusq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UpgradeWinUpgradeStrategy).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UpgradeWinUpgradeStrategy{config: uwusq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uwusq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (uwusq *UpgradeWinUpgradeStrategyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uwusq.querySpec()
	_spec.Node.Columns = uwusq.ctx.Fields
	if len(uwusq.ctx.Fields) > 0 {
		_spec.Unique = uwusq.ctx.Unique != nil && *uwusq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, uwusq.driver, _spec)
}

func (uwusq *UpgradeWinUpgradeStrategyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(upgradewinupgradestrategy.Table, upgradewinupgradestrategy.Columns, sqlgraph.NewFieldSpec(upgradewinupgradestrategy.FieldID, field.TypeInt))
	_spec.From = uwusq.sql
	if unique := uwusq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if uwusq.path != nil {
		_spec.Unique = true
	}
	if fields := uwusq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upgradewinupgradestrategy.FieldID)
		for i := range fields {
			if fields[i] != upgradewinupgradestrategy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uwusq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uwusq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uwusq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uwusq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uwusq *UpgradeWinUpgradeStrategyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uwusq.driver.Dialect())
	t1 := builder.Table(upgradewinupgradestrategy.Table)
	columns := uwusq.ctx.Fields
	if len(columns) == 0 {
		columns = upgradewinupgradestrategy.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uwusq.sql != nil {
		selector = uwusq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uwusq.ctx.Unique != nil && *uwusq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range uwusq.predicates {
		p(selector)
	}
	for _, p := range uwusq.order {
		p(selector)
	}
	if offset := uwusq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uwusq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UpgradeWinUpgradeStrategyGroupBy is the group-by builder for UpgradeWinUpgradeStrategy entities.
type UpgradeWinUpgradeStrategyGroupBy struct {
	selector
	build *UpgradeWinUpgradeStrategyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uwusgb *UpgradeWinUpgradeStrategyGroupBy) Aggregate(fns ...AggregateFunc) *UpgradeWinUpgradeStrategyGroupBy {
	uwusgb.fns = append(uwusgb.fns, fns...)
	return uwusgb
}

// Scan applies the selector query and scans the result into the given value.
func (uwusgb *UpgradeWinUpgradeStrategyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uwusgb.build.ctx, ent.OpQueryGroupBy)
	if err := uwusgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpgradeWinUpgradeStrategyQuery, *UpgradeWinUpgradeStrategyGroupBy](ctx, uwusgb.build, uwusgb, uwusgb.build.inters, v)
}

func (uwusgb *UpgradeWinUpgradeStrategyGroupBy) sqlScan(ctx context.Context, root *UpgradeWinUpgradeStrategyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(uwusgb.fns))
	for _, fn := range uwusgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*uwusgb.flds)+len(uwusgb.fns))
		for _, f := range *uwusgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*uwusgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uwusgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UpgradeWinUpgradeStrategySelect is the builder for selecting fields of UpgradeWinUpgradeStrategy entities.
type UpgradeWinUpgradeStrategySelect struct {
	*UpgradeWinUpgradeStrategyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uwuss *UpgradeWinUpgradeStrategySelect) Aggregate(fns ...AggregateFunc) *UpgradeWinUpgradeStrategySelect {
	uwuss.fns = append(uwuss.fns, fns...)
	return uwuss
}

// Scan applies the selector query and scans the result into the given value.
func (uwuss *UpgradeWinUpgradeStrategySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uwuss.ctx, ent.OpQuerySelect)
	if err := uwuss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpgradeWinUpgradeStrategyQuery, *UpgradeWinUpgradeStrategySelect](ctx, uwuss.UpgradeWinUpgradeStrategyQuery, uwuss, uwuss.inters, v)
}

func (uwuss *UpgradeWinUpgradeStrategySelect) sqlScan(ctx context.Context, root *UpgradeWinUpgradeStrategyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(uwuss.fns))
	for _, fn := range uwuss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*uwuss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uwuss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
