// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"upgradelink-admin-upgrade/server/ent/predicate"
	"upgradelink-admin-upgrade/server/ent/upgradewinupgradestrategygraystrategy"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeWinUpgradeStrategyGrayStrategyDelete is the builder for deleting a UpgradeWinUpgradeStrategyGrayStrategy entity.
type UpgradeWinUpgradeStrategyGrayStrategyDelete struct {
	config
	hooks    []Hook
	mutation *UpgradeWinUpgradeStrategyGrayStrategyMutation
}

// Where appends a list predicates to the UpgradeWinUpgradeStrategyGrayStrategyDelete builder.
func (uwusgsd *UpgradeWinUpgradeStrategyGrayStrategyDelete) Where(ps ...predicate.UpgradeWinUpgradeStrategyGrayStrategy) *UpgradeWinUpgradeStrategyGrayStrategyDelete {
	uwusgsd.mutation.Where(ps...)
	return uwusgsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uwusgsd *UpgradeWinUpgradeStrategyGrayStrategyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, uwusgsd.sqlExec, uwusgsd.mutation, uwusgsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (uwusgsd *UpgradeWinUpgradeStrategyGrayStrategyDelete) ExecX(ctx context.Context) int {
	n, err := uwusgsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uwusgsd *UpgradeWinUpgradeStrategyGrayStrategyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(upgradewinupgradestrategygraystrategy.Table, sqlgraph.NewFieldSpec(upgradewinupgradestrategygraystrategy.FieldID, field.TypeInt))
	if ps := uwusgsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, uwusgsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	uwusgsd.mutation.done = true
	return affected, err
}

// UpgradeWinUpgradeStrategyGrayStrategyDeleteOne is the builder for deleting a single UpgradeWinUpgradeStrategyGrayStrategy entity.
type UpgradeWinUpgradeStrategyGrayStrategyDeleteOne struct {
	uwusgsd *UpgradeWinUpgradeStrategyGrayStrategyDelete
}

// Where appends a list predicates to the UpgradeWinUpgradeStrategyGrayStrategyDelete builder.
func (uwusgsdo *UpgradeWinUpgradeStrategyGrayStrategyDeleteOne) Where(ps ...predicate.UpgradeWinUpgradeStrategyGrayStrategy) *UpgradeWinUpgradeStrategyGrayStrategyDeleteOne {
	uwusgsdo.uwusgsd.mutation.Where(ps...)
	return uwusgsdo
}

// Exec executes the deletion query.
func (uwusgsdo *UpgradeWinUpgradeStrategyGrayStrategyDeleteOne) Exec(ctx context.Context) error {
	n, err := uwusgsdo.uwusgsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{upgradewinupgradestrategygraystrategy.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uwusgsdo *UpgradeWinUpgradeStrategyGrayStrategyDeleteOne) ExecX(ctx context.Context) {
	if err := uwusgsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
