// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"upgradelink-admin-upgrade/server/ent/predicate"
	"upgradelink-admin-upgrade/server/ent/upgradelnxupgradestrategy"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeLnxUpgradeStrategyUpdate is the builder for updating UpgradeLnxUpgradeStrategy entities.
type UpgradeLnxUpgradeStrategyUpdate struct {
	config
	hooks    []Hook
	mutation *UpgradeLnxUpgradeStrategyMutation
}

// Where appends a list predicates to the UpgradeLnxUpgradeStrategyUpdate builder.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) Where(ps ...predicate.UpgradeLnxUpgradeStrategy) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.Where(ps...)
	return ulusu
}

// SetCompanyID sets the "company_id" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetCompanyID(i int) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.ResetCompanyID()
	ulusu.mutation.SetCompanyID(i)
	return ulusu
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetNillableCompanyID(i *int) *UpgradeLnxUpgradeStrategyUpdate {
	if i != nil {
		ulusu.SetCompanyID(*i)
	}
	return ulusu
}

// AddCompanyID adds i to the "company_id" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) AddCompanyID(i int) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.AddCompanyID(i)
	return ulusu
}

// SetEnable sets the "enable" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetEnable(i int32) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.ResetEnable()
	ulusu.mutation.SetEnable(i)
	return ulusu
}

// SetNillableEnable sets the "enable" field if the given value is not nil.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetNillableEnable(i *int32) *UpgradeLnxUpgradeStrategyUpdate {
	if i != nil {
		ulusu.SetEnable(*i)
	}
	return ulusu
}

// AddEnable adds i to the "enable" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) AddEnable(i int32) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.AddEnable(i)
	return ulusu
}

// SetName sets the "name" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetName(s string) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.SetName(s)
	return ulusu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetNillableName(s *string) *UpgradeLnxUpgradeStrategyUpdate {
	if s != nil {
		ulusu.SetName(*s)
	}
	return ulusu
}

// SetDescription sets the "description" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetDescription(s string) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.SetDescription(s)
	return ulusu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetNillableDescription(s *string) *UpgradeLnxUpgradeStrategyUpdate {
	if s != nil {
		ulusu.SetDescription(*s)
	}
	return ulusu
}

// ClearDescription clears the value of the "description" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) ClearDescription() *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.ClearDescription()
	return ulusu
}

// SetLnxID sets the "lnx_id" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetLnxID(i int) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.ResetLnxID()
	ulusu.mutation.SetLnxID(i)
	return ulusu
}

// SetNillableLnxID sets the "lnx_id" field if the given value is not nil.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetNillableLnxID(i *int) *UpgradeLnxUpgradeStrategyUpdate {
	if i != nil {
		ulusu.SetLnxID(*i)
	}
	return ulusu
}

// AddLnxID adds i to the "lnx_id" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) AddLnxID(i int) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.AddLnxID(i)
	return ulusu
}

// SetLnxVersionID sets the "lnx_version_id" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetLnxVersionID(i int) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.ResetLnxVersionID()
	ulusu.mutation.SetLnxVersionID(i)
	return ulusu
}

// SetNillableLnxVersionID sets the "lnx_version_id" field if the given value is not nil.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetNillableLnxVersionID(i *int) *UpgradeLnxUpgradeStrategyUpdate {
	if i != nil {
		ulusu.SetLnxVersionID(*i)
	}
	return ulusu
}

// AddLnxVersionID adds i to the "lnx_version_id" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) AddLnxVersionID(i int) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.AddLnxVersionID(i)
	return ulusu
}

// SetBeginDatetime sets the "begin_datetime" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetBeginDatetime(t time.Time) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.SetBeginDatetime(t)
	return ulusu
}

// SetNillableBeginDatetime sets the "begin_datetime" field if the given value is not nil.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetNillableBeginDatetime(t *time.Time) *UpgradeLnxUpgradeStrategyUpdate {
	if t != nil {
		ulusu.SetBeginDatetime(*t)
	}
	return ulusu
}

// SetEndDatetime sets the "end_datetime" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetEndDatetime(t time.Time) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.SetEndDatetime(t)
	return ulusu
}

// SetNillableEndDatetime sets the "end_datetime" field if the given value is not nil.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetNillableEndDatetime(t *time.Time) *UpgradeLnxUpgradeStrategyUpdate {
	if t != nil {
		ulusu.SetEndDatetime(*t)
	}
	return ulusu
}

// SetUpgradeType sets the "upgrade_type" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetUpgradeType(i int32) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.ResetUpgradeType()
	ulusu.mutation.SetUpgradeType(i)
	return ulusu
}

// SetNillableUpgradeType sets the "upgrade_type" field if the given value is not nil.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetNillableUpgradeType(i *int32) *UpgradeLnxUpgradeStrategyUpdate {
	if i != nil {
		ulusu.SetUpgradeType(*i)
	}
	return ulusu
}

// AddUpgradeType adds i to the "upgrade_type" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) AddUpgradeType(i int32) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.AddUpgradeType(i)
	return ulusu
}

// SetPromptUpgradeContent sets the "prompt_upgrade_content" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetPromptUpgradeContent(s string) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.SetPromptUpgradeContent(s)
	return ulusu
}

// SetNillablePromptUpgradeContent sets the "prompt_upgrade_content" field if the given value is not nil.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetNillablePromptUpgradeContent(s *string) *UpgradeLnxUpgradeStrategyUpdate {
	if s != nil {
		ulusu.SetPromptUpgradeContent(*s)
	}
	return ulusu
}

// ClearPromptUpgradeContent clears the value of the "prompt_upgrade_content" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) ClearPromptUpgradeContent() *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.ClearPromptUpgradeContent()
	return ulusu
}

// SetUpgradeDevType sets the "upgrade_dev_type" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetUpgradeDevType(i int32) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.ResetUpgradeDevType()
	ulusu.mutation.SetUpgradeDevType(i)
	return ulusu
}

// SetNillableUpgradeDevType sets the "upgrade_dev_type" field if the given value is not nil.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetNillableUpgradeDevType(i *int32) *UpgradeLnxUpgradeStrategyUpdate {
	if i != nil {
		ulusu.SetUpgradeDevType(*i)
	}
	return ulusu
}

// AddUpgradeDevType adds i to the "upgrade_dev_type" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) AddUpgradeDevType(i int32) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.AddUpgradeDevType(i)
	return ulusu
}

// SetUpgradeDevData sets the "upgrade_dev_data" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetUpgradeDevData(s string) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.SetUpgradeDevData(s)
	return ulusu
}

// SetNillableUpgradeDevData sets the "upgrade_dev_data" field if the given value is not nil.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetNillableUpgradeDevData(s *string) *UpgradeLnxUpgradeStrategyUpdate {
	if s != nil {
		ulusu.SetUpgradeDevData(*s)
	}
	return ulusu
}

// SetUpgradeVersionType sets the "upgrade_version_type" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetUpgradeVersionType(i int32) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.ResetUpgradeVersionType()
	ulusu.mutation.SetUpgradeVersionType(i)
	return ulusu
}

// SetNillableUpgradeVersionType sets the "upgrade_version_type" field if the given value is not nil.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetNillableUpgradeVersionType(i *int32) *UpgradeLnxUpgradeStrategyUpdate {
	if i != nil {
		ulusu.SetUpgradeVersionType(*i)
	}
	return ulusu
}

// AddUpgradeVersionType adds i to the "upgrade_version_type" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) AddUpgradeVersionType(i int32) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.AddUpgradeVersionType(i)
	return ulusu
}

// SetUpgradeVersionData sets the "upgrade_version_data" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetUpgradeVersionData(s string) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.SetUpgradeVersionData(s)
	return ulusu
}

// SetNillableUpgradeVersionData sets the "upgrade_version_data" field if the given value is not nil.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetNillableUpgradeVersionData(s *string) *UpgradeLnxUpgradeStrategyUpdate {
	if s != nil {
		ulusu.SetUpgradeVersionData(*s)
	}
	return ulusu
}

// SetIsGray sets the "is_gray" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetIsGray(i int32) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.ResetIsGray()
	ulusu.mutation.SetIsGray(i)
	return ulusu
}

// SetNillableIsGray sets the "is_gray" field if the given value is not nil.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetNillableIsGray(i *int32) *UpgradeLnxUpgradeStrategyUpdate {
	if i != nil {
		ulusu.SetIsGray(*i)
	}
	return ulusu
}

// AddIsGray adds i to the "is_gray" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) AddIsGray(i int32) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.AddIsGray(i)
	return ulusu
}

// SetGrayData sets the "gray_data" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetGrayData(s string) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.SetGrayData(s)
	return ulusu
}

// SetNillableGrayData sets the "gray_data" field if the given value is not nil.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetNillableGrayData(s *string) *UpgradeLnxUpgradeStrategyUpdate {
	if s != nil {
		ulusu.SetGrayData(*s)
	}
	return ulusu
}

// SetIsFlowLimit sets the "is_flow_limit" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetIsFlowLimit(i int32) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.ResetIsFlowLimit()
	ulusu.mutation.SetIsFlowLimit(i)
	return ulusu
}

// SetNillableIsFlowLimit sets the "is_flow_limit" field if the given value is not nil.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetNillableIsFlowLimit(i *int32) *UpgradeLnxUpgradeStrategyUpdate {
	if i != nil {
		ulusu.SetIsFlowLimit(*i)
	}
	return ulusu
}

// AddIsFlowLimit adds i to the "is_flow_limit" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) AddIsFlowLimit(i int32) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.AddIsFlowLimit(i)
	return ulusu
}

// SetFlowLimitData sets the "flow_limit_data" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetFlowLimitData(s string) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.SetFlowLimitData(s)
	return ulusu
}

// SetNillableFlowLimitData sets the "flow_limit_data" field if the given value is not nil.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetNillableFlowLimitData(s *string) *UpgradeLnxUpgradeStrategyUpdate {
	if s != nil {
		ulusu.SetFlowLimitData(*s)
	}
	return ulusu
}

// SetIsDel sets the "is_del" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetIsDel(i int32) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.ResetIsDel()
	ulusu.mutation.SetIsDel(i)
	return ulusu
}

// SetNillableIsDel sets the "is_del" field if the given value is not nil.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetNillableIsDel(i *int32) *UpgradeLnxUpgradeStrategyUpdate {
	if i != nil {
		ulusu.SetIsDel(*i)
	}
	return ulusu
}

// AddIsDel adds i to the "is_del" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) AddIsDel(i int32) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.AddIsDel(i)
	return ulusu
}

// SetCreateAt sets the "create_at" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetCreateAt(t time.Time) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.SetCreateAt(t)
	return ulusu
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetNillableCreateAt(t *time.Time) *UpgradeLnxUpgradeStrategyUpdate {
	if t != nil {
		ulusu.SetCreateAt(*t)
	}
	return ulusu
}

// ClearCreateAt clears the value of the "create_at" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) ClearCreateAt() *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.ClearCreateAt()
	return ulusu
}

// SetUpdateAt sets the "update_at" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetUpdateAt(t time.Time) *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.SetUpdateAt(t)
	return ulusu
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SetNillableUpdateAt(t *time.Time) *UpgradeLnxUpgradeStrategyUpdate {
	if t != nil {
		ulusu.SetUpdateAt(*t)
	}
	return ulusu
}

// ClearUpdateAt clears the value of the "update_at" field.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) ClearUpdateAt() *UpgradeLnxUpgradeStrategyUpdate {
	ulusu.mutation.ClearUpdateAt()
	return ulusu
}

// Mutation returns the UpgradeLnxUpgradeStrategyMutation object of the builder.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) Mutation() *UpgradeLnxUpgradeStrategyMutation {
	return ulusu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ulusu.sqlSave, ulusu.mutation, ulusu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) SaveX(ctx context.Context) int {
	affected, err := ulusu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) Exec(ctx context.Context) error {
	_, err := ulusu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ulusu *UpgradeLnxUpgradeStrategyUpdate) ExecX(ctx context.Context) {
	if err := ulusu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ulusu *UpgradeLnxUpgradeStrategyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(upgradelnxupgradestrategy.Table, upgradelnxupgradestrategy.Columns, sqlgraph.NewFieldSpec(upgradelnxupgradestrategy.FieldID, field.TypeInt))
	if ps := ulusu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ulusu.mutation.CompanyID(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := ulusu.mutation.AddedCompanyID(); ok {
		_spec.AddField(upgradelnxupgradestrategy.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := ulusu.mutation.Enable(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldEnable, field.TypeInt32, value)
	}
	if value, ok := ulusu.mutation.AddedEnable(); ok {
		_spec.AddField(upgradelnxupgradestrategy.FieldEnable, field.TypeInt32, value)
	}
	if value, ok := ulusu.mutation.Name(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldName, field.TypeString, value)
	}
	if value, ok := ulusu.mutation.Description(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldDescription, field.TypeString, value)
	}
	if ulusu.mutation.DescriptionCleared() {
		_spec.ClearField(upgradelnxupgradestrategy.FieldDescription, field.TypeString)
	}
	if value, ok := ulusu.mutation.LnxID(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldLnxID, field.TypeInt, value)
	}
	if value, ok := ulusu.mutation.AddedLnxID(); ok {
		_spec.AddField(upgradelnxupgradestrategy.FieldLnxID, field.TypeInt, value)
	}
	if value, ok := ulusu.mutation.LnxVersionID(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldLnxVersionID, field.TypeInt, value)
	}
	if value, ok := ulusu.mutation.AddedLnxVersionID(); ok {
		_spec.AddField(upgradelnxupgradestrategy.FieldLnxVersionID, field.TypeInt, value)
	}
	if value, ok := ulusu.mutation.BeginDatetime(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldBeginDatetime, field.TypeTime, value)
	}
	if value, ok := ulusu.mutation.EndDatetime(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldEndDatetime, field.TypeTime, value)
	}
	if value, ok := ulusu.mutation.UpgradeType(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldUpgradeType, field.TypeInt32, value)
	}
	if value, ok := ulusu.mutation.AddedUpgradeType(); ok {
		_spec.AddField(upgradelnxupgradestrategy.FieldUpgradeType, field.TypeInt32, value)
	}
	if value, ok := ulusu.mutation.PromptUpgradeContent(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldPromptUpgradeContent, field.TypeString, value)
	}
	if ulusu.mutation.PromptUpgradeContentCleared() {
		_spec.ClearField(upgradelnxupgradestrategy.FieldPromptUpgradeContent, field.TypeString)
	}
	if value, ok := ulusu.mutation.UpgradeDevType(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldUpgradeDevType, field.TypeInt32, value)
	}
	if value, ok := ulusu.mutation.AddedUpgradeDevType(); ok {
		_spec.AddField(upgradelnxupgradestrategy.FieldUpgradeDevType, field.TypeInt32, value)
	}
	if value, ok := ulusu.mutation.UpgradeDevData(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldUpgradeDevData, field.TypeString, value)
	}
	if value, ok := ulusu.mutation.UpgradeVersionType(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldUpgradeVersionType, field.TypeInt32, value)
	}
	if value, ok := ulusu.mutation.AddedUpgradeVersionType(); ok {
		_spec.AddField(upgradelnxupgradestrategy.FieldUpgradeVersionType, field.TypeInt32, value)
	}
	if value, ok := ulusu.mutation.UpgradeVersionData(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldUpgradeVersionData, field.TypeString, value)
	}
	if value, ok := ulusu.mutation.IsGray(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldIsGray, field.TypeInt32, value)
	}
	if value, ok := ulusu.mutation.AddedIsGray(); ok {
		_spec.AddField(upgradelnxupgradestrategy.FieldIsGray, field.TypeInt32, value)
	}
	if value, ok := ulusu.mutation.GrayData(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldGrayData, field.TypeString, value)
	}
	if value, ok := ulusu.mutation.IsFlowLimit(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldIsFlowLimit, field.TypeInt32, value)
	}
	if value, ok := ulusu.mutation.AddedIsFlowLimit(); ok {
		_spec.AddField(upgradelnxupgradestrategy.FieldIsFlowLimit, field.TypeInt32, value)
	}
	if value, ok := ulusu.mutation.FlowLimitData(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldFlowLimitData, field.TypeString, value)
	}
	if value, ok := ulusu.mutation.IsDel(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := ulusu.mutation.AddedIsDel(); ok {
		_spec.AddField(upgradelnxupgradestrategy.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := ulusu.mutation.CreateAt(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldCreateAt, field.TypeTime, value)
	}
	if ulusu.mutation.CreateAtCleared() {
		_spec.ClearField(upgradelnxupgradestrategy.FieldCreateAt, field.TypeTime)
	}
	if value, ok := ulusu.mutation.UpdateAt(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldUpdateAt, field.TypeTime, value)
	}
	if ulusu.mutation.UpdateAtCleared() {
		_spec.ClearField(upgradelnxupgradestrategy.FieldUpdateAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ulusu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upgradelnxupgradestrategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ulusu.mutation.done = true
	return n, nil
}

// UpgradeLnxUpgradeStrategyUpdateOne is the builder for updating a single UpgradeLnxUpgradeStrategy entity.
type UpgradeLnxUpgradeStrategyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpgradeLnxUpgradeStrategyMutation
}

// SetCompanyID sets the "company_id" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetCompanyID(i int) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.ResetCompanyID()
	ulusuo.mutation.SetCompanyID(i)
	return ulusuo
}

// SetNillableCompanyID sets the "company_id" field if the given value is not nil.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetNillableCompanyID(i *int) *UpgradeLnxUpgradeStrategyUpdateOne {
	if i != nil {
		ulusuo.SetCompanyID(*i)
	}
	return ulusuo
}

// AddCompanyID adds i to the "company_id" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) AddCompanyID(i int) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.AddCompanyID(i)
	return ulusuo
}

// SetEnable sets the "enable" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetEnable(i int32) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.ResetEnable()
	ulusuo.mutation.SetEnable(i)
	return ulusuo
}

// SetNillableEnable sets the "enable" field if the given value is not nil.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetNillableEnable(i *int32) *UpgradeLnxUpgradeStrategyUpdateOne {
	if i != nil {
		ulusuo.SetEnable(*i)
	}
	return ulusuo
}

// AddEnable adds i to the "enable" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) AddEnable(i int32) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.AddEnable(i)
	return ulusuo
}

// SetName sets the "name" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetName(s string) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.SetName(s)
	return ulusuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetNillableName(s *string) *UpgradeLnxUpgradeStrategyUpdateOne {
	if s != nil {
		ulusuo.SetName(*s)
	}
	return ulusuo
}

// SetDescription sets the "description" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetDescription(s string) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.SetDescription(s)
	return ulusuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetNillableDescription(s *string) *UpgradeLnxUpgradeStrategyUpdateOne {
	if s != nil {
		ulusuo.SetDescription(*s)
	}
	return ulusuo
}

// ClearDescription clears the value of the "description" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) ClearDescription() *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.ClearDescription()
	return ulusuo
}

// SetLnxID sets the "lnx_id" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetLnxID(i int) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.ResetLnxID()
	ulusuo.mutation.SetLnxID(i)
	return ulusuo
}

// SetNillableLnxID sets the "lnx_id" field if the given value is not nil.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetNillableLnxID(i *int) *UpgradeLnxUpgradeStrategyUpdateOne {
	if i != nil {
		ulusuo.SetLnxID(*i)
	}
	return ulusuo
}

// AddLnxID adds i to the "lnx_id" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) AddLnxID(i int) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.AddLnxID(i)
	return ulusuo
}

// SetLnxVersionID sets the "lnx_version_id" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetLnxVersionID(i int) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.ResetLnxVersionID()
	ulusuo.mutation.SetLnxVersionID(i)
	return ulusuo
}

// SetNillableLnxVersionID sets the "lnx_version_id" field if the given value is not nil.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetNillableLnxVersionID(i *int) *UpgradeLnxUpgradeStrategyUpdateOne {
	if i != nil {
		ulusuo.SetLnxVersionID(*i)
	}
	return ulusuo
}

// AddLnxVersionID adds i to the "lnx_version_id" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) AddLnxVersionID(i int) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.AddLnxVersionID(i)
	return ulusuo
}

// SetBeginDatetime sets the "begin_datetime" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetBeginDatetime(t time.Time) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.SetBeginDatetime(t)
	return ulusuo
}

// SetNillableBeginDatetime sets the "begin_datetime" field if the given value is not nil.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetNillableBeginDatetime(t *time.Time) *UpgradeLnxUpgradeStrategyUpdateOne {
	if t != nil {
		ulusuo.SetBeginDatetime(*t)
	}
	return ulusuo
}

// SetEndDatetime sets the "end_datetime" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetEndDatetime(t time.Time) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.SetEndDatetime(t)
	return ulusuo
}

// SetNillableEndDatetime sets the "end_datetime" field if the given value is not nil.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetNillableEndDatetime(t *time.Time) *UpgradeLnxUpgradeStrategyUpdateOne {
	if t != nil {
		ulusuo.SetEndDatetime(*t)
	}
	return ulusuo
}

// SetUpgradeType sets the "upgrade_type" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetUpgradeType(i int32) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.ResetUpgradeType()
	ulusuo.mutation.SetUpgradeType(i)
	return ulusuo
}

// SetNillableUpgradeType sets the "upgrade_type" field if the given value is not nil.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetNillableUpgradeType(i *int32) *UpgradeLnxUpgradeStrategyUpdateOne {
	if i != nil {
		ulusuo.SetUpgradeType(*i)
	}
	return ulusuo
}

// AddUpgradeType adds i to the "upgrade_type" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) AddUpgradeType(i int32) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.AddUpgradeType(i)
	return ulusuo
}

// SetPromptUpgradeContent sets the "prompt_upgrade_content" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetPromptUpgradeContent(s string) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.SetPromptUpgradeContent(s)
	return ulusuo
}

// SetNillablePromptUpgradeContent sets the "prompt_upgrade_content" field if the given value is not nil.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetNillablePromptUpgradeContent(s *string) *UpgradeLnxUpgradeStrategyUpdateOne {
	if s != nil {
		ulusuo.SetPromptUpgradeContent(*s)
	}
	return ulusuo
}

// ClearPromptUpgradeContent clears the value of the "prompt_upgrade_content" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) ClearPromptUpgradeContent() *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.ClearPromptUpgradeContent()
	return ulusuo
}

// SetUpgradeDevType sets the "upgrade_dev_type" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetUpgradeDevType(i int32) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.ResetUpgradeDevType()
	ulusuo.mutation.SetUpgradeDevType(i)
	return ulusuo
}

// SetNillableUpgradeDevType sets the "upgrade_dev_type" field if the given value is not nil.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetNillableUpgradeDevType(i *int32) *UpgradeLnxUpgradeStrategyUpdateOne {
	if i != nil {
		ulusuo.SetUpgradeDevType(*i)
	}
	return ulusuo
}

// AddUpgradeDevType adds i to the "upgrade_dev_type" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) AddUpgradeDevType(i int32) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.AddUpgradeDevType(i)
	return ulusuo
}

// SetUpgradeDevData sets the "upgrade_dev_data" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetUpgradeDevData(s string) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.SetUpgradeDevData(s)
	return ulusuo
}

// SetNillableUpgradeDevData sets the "upgrade_dev_data" field if the given value is not nil.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetNillableUpgradeDevData(s *string) *UpgradeLnxUpgradeStrategyUpdateOne {
	if s != nil {
		ulusuo.SetUpgradeDevData(*s)
	}
	return ulusuo
}

// SetUpgradeVersionType sets the "upgrade_version_type" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetUpgradeVersionType(i int32) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.ResetUpgradeVersionType()
	ulusuo.mutation.SetUpgradeVersionType(i)
	return ulusuo
}

// SetNillableUpgradeVersionType sets the "upgrade_version_type" field if the given value is not nil.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetNillableUpgradeVersionType(i *int32) *UpgradeLnxUpgradeStrategyUpdateOne {
	if i != nil {
		ulusuo.SetUpgradeVersionType(*i)
	}
	return ulusuo
}

// AddUpgradeVersionType adds i to the "upgrade_version_type" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) AddUpgradeVersionType(i int32) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.AddUpgradeVersionType(i)
	return ulusuo
}

// SetUpgradeVersionData sets the "upgrade_version_data" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetUpgradeVersionData(s string) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.SetUpgradeVersionData(s)
	return ulusuo
}

// SetNillableUpgradeVersionData sets the "upgrade_version_data" field if the given value is not nil.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetNillableUpgradeVersionData(s *string) *UpgradeLnxUpgradeStrategyUpdateOne {
	if s != nil {
		ulusuo.SetUpgradeVersionData(*s)
	}
	return ulusuo
}

// SetIsGray sets the "is_gray" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetIsGray(i int32) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.ResetIsGray()
	ulusuo.mutation.SetIsGray(i)
	return ulusuo
}

// SetNillableIsGray sets the "is_gray" field if the given value is not nil.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetNillableIsGray(i *int32) *UpgradeLnxUpgradeStrategyUpdateOne {
	if i != nil {
		ulusuo.SetIsGray(*i)
	}
	return ulusuo
}

// AddIsGray adds i to the "is_gray" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) AddIsGray(i int32) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.AddIsGray(i)
	return ulusuo
}

// SetGrayData sets the "gray_data" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetGrayData(s string) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.SetGrayData(s)
	return ulusuo
}

// SetNillableGrayData sets the "gray_data" field if the given value is not nil.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetNillableGrayData(s *string) *UpgradeLnxUpgradeStrategyUpdateOne {
	if s != nil {
		ulusuo.SetGrayData(*s)
	}
	return ulusuo
}

// SetIsFlowLimit sets the "is_flow_limit" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetIsFlowLimit(i int32) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.ResetIsFlowLimit()
	ulusuo.mutation.SetIsFlowLimit(i)
	return ulusuo
}

// SetNillableIsFlowLimit sets the "is_flow_limit" field if the given value is not nil.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetNillableIsFlowLimit(i *int32) *UpgradeLnxUpgradeStrategyUpdateOne {
	if i != nil {
		ulusuo.SetIsFlowLimit(*i)
	}
	return ulusuo
}

// AddIsFlowLimit adds i to the "is_flow_limit" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) AddIsFlowLimit(i int32) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.AddIsFlowLimit(i)
	return ulusuo
}

// SetFlowLimitData sets the "flow_limit_data" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetFlowLimitData(s string) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.SetFlowLimitData(s)
	return ulusuo
}

// SetNillableFlowLimitData sets the "flow_limit_data" field if the given value is not nil.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetNillableFlowLimitData(s *string) *UpgradeLnxUpgradeStrategyUpdateOne {
	if s != nil {
		ulusuo.SetFlowLimitData(*s)
	}
	return ulusuo
}

// SetIsDel sets the "is_del" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetIsDel(i int32) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.ResetIsDel()
	ulusuo.mutation.SetIsDel(i)
	return ulusuo
}

// SetNillableIsDel sets the "is_del" field if the given value is not nil.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetNillableIsDel(i *int32) *UpgradeLnxUpgradeStrategyUpdateOne {
	if i != nil {
		ulusuo.SetIsDel(*i)
	}
	return ulusuo
}

// AddIsDel adds i to the "is_del" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) AddIsDel(i int32) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.AddIsDel(i)
	return ulusuo
}

// SetCreateAt sets the "create_at" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetCreateAt(t time.Time) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.SetCreateAt(t)
	return ulusuo
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetNillableCreateAt(t *time.Time) *UpgradeLnxUpgradeStrategyUpdateOne {
	if t != nil {
		ulusuo.SetCreateAt(*t)
	}
	return ulusuo
}

// ClearCreateAt clears the value of the "create_at" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) ClearCreateAt() *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.ClearCreateAt()
	return ulusuo
}

// SetUpdateAt sets the "update_at" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetUpdateAt(t time.Time) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.SetUpdateAt(t)
	return ulusuo
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SetNillableUpdateAt(t *time.Time) *UpgradeLnxUpgradeStrategyUpdateOne {
	if t != nil {
		ulusuo.SetUpdateAt(*t)
	}
	return ulusuo
}

// ClearUpdateAt clears the value of the "update_at" field.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) ClearUpdateAt() *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.ClearUpdateAt()
	return ulusuo
}

// Mutation returns the UpgradeLnxUpgradeStrategyMutation object of the builder.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) Mutation() *UpgradeLnxUpgradeStrategyMutation {
	return ulusuo.mutation
}

// Where appends a list predicates to the UpgradeLnxUpgradeStrategyUpdate builder.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) Where(ps ...predicate.UpgradeLnxUpgradeStrategy) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.mutation.Where(ps...)
	return ulusuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) Select(field string, fields ...string) *UpgradeLnxUpgradeStrategyUpdateOne {
	ulusuo.fields = append([]string{field}, fields...)
	return ulusuo
}

// Save executes the query and returns the updated UpgradeLnxUpgradeStrategy entity.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) Save(ctx context.Context) (*UpgradeLnxUpgradeStrategy, error) {
	return withHooks(ctx, ulusuo.sqlSave, ulusuo.mutation, ulusuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) SaveX(ctx context.Context) *UpgradeLnxUpgradeStrategy {
	node, err := ulusuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) Exec(ctx context.Context) error {
	_, err := ulusuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) ExecX(ctx context.Context) {
	if err := ulusuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ulusuo *UpgradeLnxUpgradeStrategyUpdateOne) sqlSave(ctx context.Context) (_node *UpgradeLnxUpgradeStrategy, err error) {
	_spec := sqlgraph.NewUpdateSpec(upgradelnxupgradestrategy.Table, upgradelnxupgradestrategy.Columns, sqlgraph.NewFieldSpec(upgradelnxupgradestrategy.FieldID, field.TypeInt))
	id, ok := ulusuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpgradeLnxUpgradeStrategy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ulusuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upgradelnxupgradestrategy.FieldID)
		for _, f := range fields {
			if !upgradelnxupgradestrategy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upgradelnxupgradestrategy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ulusuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ulusuo.mutation.CompanyID(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := ulusuo.mutation.AddedCompanyID(); ok {
		_spec.AddField(upgradelnxupgradestrategy.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := ulusuo.mutation.Enable(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldEnable, field.TypeInt32, value)
	}
	if value, ok := ulusuo.mutation.AddedEnable(); ok {
		_spec.AddField(upgradelnxupgradestrategy.FieldEnable, field.TypeInt32, value)
	}
	if value, ok := ulusuo.mutation.Name(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldName, field.TypeString, value)
	}
	if value, ok := ulusuo.mutation.Description(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldDescription, field.TypeString, value)
	}
	if ulusuo.mutation.DescriptionCleared() {
		_spec.ClearField(upgradelnxupgradestrategy.FieldDescription, field.TypeString)
	}
	if value, ok := ulusuo.mutation.LnxID(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldLnxID, field.TypeInt, value)
	}
	if value, ok := ulusuo.mutation.AddedLnxID(); ok {
		_spec.AddField(upgradelnxupgradestrategy.FieldLnxID, field.TypeInt, value)
	}
	if value, ok := ulusuo.mutation.LnxVersionID(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldLnxVersionID, field.TypeInt, value)
	}
	if value, ok := ulusuo.mutation.AddedLnxVersionID(); ok {
		_spec.AddField(upgradelnxupgradestrategy.FieldLnxVersionID, field.TypeInt, value)
	}
	if value, ok := ulusuo.mutation.BeginDatetime(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldBeginDatetime, field.TypeTime, value)
	}
	if value, ok := ulusuo.mutation.EndDatetime(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldEndDatetime, field.TypeTime, value)
	}
	if value, ok := ulusuo.mutation.UpgradeType(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldUpgradeType, field.TypeInt32, value)
	}
	if value, ok := ulusuo.mutation.AddedUpgradeType(); ok {
		_spec.AddField(upgradelnxupgradestrategy.FieldUpgradeType, field.TypeInt32, value)
	}
	if value, ok := ulusuo.mutation.PromptUpgradeContent(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldPromptUpgradeContent, field.TypeString, value)
	}
	if ulusuo.mutation.PromptUpgradeContentCleared() {
		_spec.ClearField(upgradelnxupgradestrategy.FieldPromptUpgradeContent, field.TypeString)
	}
	if value, ok := ulusuo.mutation.UpgradeDevType(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldUpgradeDevType, field.TypeInt32, value)
	}
	if value, ok := ulusuo.mutation.AddedUpgradeDevType(); ok {
		_spec.AddField(upgradelnxupgradestrategy.FieldUpgradeDevType, field.TypeInt32, value)
	}
	if value, ok := ulusuo.mutation.UpgradeDevData(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldUpgradeDevData, field.TypeString, value)
	}
	if value, ok := ulusuo.mutation.UpgradeVersionType(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldUpgradeVersionType, field.TypeInt32, value)
	}
	if value, ok := ulusuo.mutation.AddedUpgradeVersionType(); ok {
		_spec.AddField(upgradelnxupgradestrategy.FieldUpgradeVersionType, field.TypeInt32, value)
	}
	if value, ok := ulusuo.mutation.UpgradeVersionData(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldUpgradeVersionData, field.TypeString, value)
	}
	if value, ok := ulusuo.mutation.IsGray(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldIsGray, field.TypeInt32, value)
	}
	if value, ok := ulusuo.mutation.AddedIsGray(); ok {
		_spec.AddField(upgradelnxupgradestrategy.FieldIsGray, field.TypeInt32, value)
	}
	if value, ok := ulusuo.mutation.GrayData(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldGrayData, field.TypeString, value)
	}
	if value, ok := ulusuo.mutation.IsFlowLimit(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldIsFlowLimit, field.TypeInt32, value)
	}
	if value, ok := ulusuo.mutation.AddedIsFlowLimit(); ok {
		_spec.AddField(upgradelnxupgradestrategy.FieldIsFlowLimit, field.TypeInt32, value)
	}
	if value, ok := ulusuo.mutation.FlowLimitData(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldFlowLimitData, field.TypeString, value)
	}
	if value, ok := ulusuo.mutation.IsDel(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := ulusuo.mutation.AddedIsDel(); ok {
		_spec.AddField(upgradelnxupgradestrategy.FieldIsDel, field.TypeInt32, value)
	}
	if value, ok := ulusuo.mutation.CreateAt(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldCreateAt, field.TypeTime, value)
	}
	if ulusuo.mutation.CreateAtCleared() {
		_spec.ClearField(upgradelnxupgradestrategy.FieldCreateAt, field.TypeTime)
	}
	if value, ok := ulusuo.mutation.UpdateAt(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldUpdateAt, field.TypeTime, value)
	}
	if ulusuo.mutation.UpdateAtCleared() {
		_spec.ClearField(upgradelnxupgradestrategy.FieldUpdateAt, field.TypeTime)
	}
	_node = &UpgradeLnxUpgradeStrategy{config: ulusuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ulusuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upgradelnxupgradestrategy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ulusuo.mutation.done = true
	return _node, nil
}
