// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"upgradelink-admin-upgrade/server/ent/upgrademac"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeMacCreate is the builder for creating a UpgradeMac entity.
type UpgradeMacCreate struct {
	config
	mutation *UpgradeMacMutation
	hooks    []Hook
}

// SetCompanyID sets the "company_id" field.
func (umc *UpgradeMacCreate) SetCompanyID(i int) *UpgradeMacCreate {
	umc.mutation.SetCompanyID(i)
	return umc
}

// SetKey sets the "key" field.
func (umc *UpgradeMacCreate) SetKey(s string) *UpgradeMacCreate {
	umc.mutation.SetKey(s)
	return umc
}

// SetName sets the "name" field.
func (umc *UpgradeMacCreate) SetName(s string) *UpgradeMacCreate {
	umc.mutation.SetName(s)
	return umc
}

// SetPackageName sets the "package_name" field.
func (umc *UpgradeMacCreate) SetPackageName(s string) *UpgradeMacCreate {
	umc.mutation.SetPackageName(s)
	return umc
}

// SetDescription sets the "description" field.
func (umc *UpgradeMacCreate) SetDescription(s string) *UpgradeMacCreate {
	umc.mutation.SetDescription(s)
	return umc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (umc *UpgradeMacCreate) SetNillableDescription(s *string) *UpgradeMacCreate {
	if s != nil {
		umc.SetDescription(*s)
	}
	return umc
}

// SetIsDel sets the "is_del" field.
func (umc *UpgradeMacCreate) SetIsDel(i int32) *UpgradeMacCreate {
	umc.mutation.SetIsDel(i)
	return umc
}

// SetCreateAt sets the "create_at" field.
func (umc *UpgradeMacCreate) SetCreateAt(t time.Time) *UpgradeMacCreate {
	umc.mutation.SetCreateAt(t)
	return umc
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (umc *UpgradeMacCreate) SetNillableCreateAt(t *time.Time) *UpgradeMacCreate {
	if t != nil {
		umc.SetCreateAt(*t)
	}
	return umc
}

// SetUpdateAt sets the "update_at" field.
func (umc *UpgradeMacCreate) SetUpdateAt(t time.Time) *UpgradeMacCreate {
	umc.mutation.SetUpdateAt(t)
	return umc
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (umc *UpgradeMacCreate) SetNillableUpdateAt(t *time.Time) *UpgradeMacCreate {
	if t != nil {
		umc.SetUpdateAt(*t)
	}
	return umc
}

// SetID sets the "id" field.
func (umc *UpgradeMacCreate) SetID(i int) *UpgradeMacCreate {
	umc.mutation.SetID(i)
	return umc
}

// Mutation returns the UpgradeMacMutation object of the builder.
func (umc *UpgradeMacCreate) Mutation() *UpgradeMacMutation {
	return umc.mutation
}

// Save creates the UpgradeMac in the database.
func (umc *UpgradeMacCreate) Save(ctx context.Context) (*UpgradeMac, error) {
	return withHooks(ctx, umc.sqlSave, umc.mutation, umc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (umc *UpgradeMacCreate) SaveX(ctx context.Context) *UpgradeMac {
	v, err := umc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (umc *UpgradeMacCreate) Exec(ctx context.Context) error {
	_, err := umc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (umc *UpgradeMacCreate) ExecX(ctx context.Context) {
	if err := umc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (umc *UpgradeMacCreate) check() error {
	if _, ok := umc.mutation.CompanyID(); !ok {
		return &ValidationError{Name: "company_id", err: errors.New(`ent: missing required field "UpgradeMac.company_id"`)}
	}
	if _, ok := umc.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "UpgradeMac.key"`)}
	}
	if _, ok := umc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "UpgradeMac.name"`)}
	}
	if _, ok := umc.mutation.PackageName(); !ok {
		return &ValidationError{Name: "package_name", err: errors.New(`ent: missing required field "UpgradeMac.package_name"`)}
	}
	if _, ok := umc.mutation.IsDel(); !ok {
		return &ValidationError{Name: "is_del", err: errors.New(`ent: missing required field "UpgradeMac.is_del"`)}
	}
	return nil
}

func (umc *UpgradeMacCreate) sqlSave(ctx context.Context) (*UpgradeMac, error) {
	if err := umc.check(); err != nil {
		return nil, err
	}
	_node, _spec := umc.createSpec()
	if err := sqlgraph.CreateNode(ctx, umc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	umc.mutation.id = &_node.ID
	umc.mutation.done = true
	return _node, nil
}

func (umc *UpgradeMacCreate) createSpec() (*UpgradeMac, *sqlgraph.CreateSpec) {
	var (
		_node = &UpgradeMac{config: umc.config}
		_spec = sqlgraph.NewCreateSpec(upgrademac.Table, sqlgraph.NewFieldSpec(upgrademac.FieldID, field.TypeInt))
	)
	if id, ok := umc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := umc.mutation.CompanyID(); ok {
		_spec.SetField(upgrademac.FieldCompanyID, field.TypeInt, value)
		_node.CompanyID = value
	}
	if value, ok := umc.mutation.Key(); ok {
		_spec.SetField(upgrademac.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := umc.mutation.Name(); ok {
		_spec.SetField(upgrademac.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := umc.mutation.PackageName(); ok {
		_spec.SetField(upgrademac.FieldPackageName, field.TypeString, value)
		_node.PackageName = value
	}
	if value, ok := umc.mutation.Description(); ok {
		_spec.SetField(upgrademac.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := umc.mutation.IsDel(); ok {
		_spec.SetField(upgrademac.FieldIsDel, field.TypeInt32, value)
		_node.IsDel = value
	}
	if value, ok := umc.mutation.CreateAt(); ok {
		_spec.SetField(upgrademac.FieldCreateAt, field.TypeTime, value)
		_node.CreateAt = value
	}
	if value, ok := umc.mutation.UpdateAt(); ok {
		_spec.SetField(upgrademac.FieldUpdateAt, field.TypeTime, value)
		_node.UpdateAt = value
	}
	return _node, _spec
}

// UpgradeMacCreateBulk is the builder for creating many UpgradeMac entities in bulk.
type UpgradeMacCreateBulk struct {
	config
	err      error
	builders []*UpgradeMacCreate
}

// Save creates the UpgradeMac entities in the database.
func (umcb *UpgradeMacCreateBulk) Save(ctx context.Context) ([]*UpgradeMac, error) {
	if umcb.err != nil {
		return nil, umcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(umcb.builders))
	nodes := make([]*UpgradeMac, len(umcb.builders))
	mutators := make([]Mutator, len(umcb.builders))
	for i := range umcb.builders {
		func(i int, root context.Context) {
			builder := umcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpgradeMacMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, umcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, umcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, umcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (umcb *UpgradeMacCreateBulk) SaveX(ctx context.Context) []*UpgradeMac {
	v, err := umcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (umcb *UpgradeMacCreateBulk) Exec(ctx context.Context) error {
	_, err := umcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (umcb *UpgradeMacCreateBulk) ExecX(ctx context.Context) {
	if err := umcb.Exec(ctx); err != nil {
		panic(err)
	}
}
