// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"upgradelink-admin-upgrade/server/ent/upgradelnxupgradestrategy"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeLnxUpgradeStrategyCreate is the builder for creating a UpgradeLnxUpgradeStrategy entity.
type UpgradeLnxUpgradeStrategyCreate struct {
	config
	mutation *UpgradeLnxUpgradeStrategyMutation
	hooks    []Hook
}

// SetCompanyID sets the "company_id" field.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetCompanyID(i int) *UpgradeLnxUpgradeStrategyCreate {
	ulusc.mutation.SetCompanyID(i)
	return ulusc
}

// SetEnable sets the "enable" field.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetEnable(i int32) *UpgradeLnxUpgradeStrategyCreate {
	ulusc.mutation.SetEnable(i)
	return ulusc
}

// SetName sets the "name" field.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetName(s string) *UpgradeLnxUpgradeStrategyCreate {
	ulusc.mutation.SetName(s)
	return ulusc
}

// SetDescription sets the "description" field.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetDescription(s string) *UpgradeLnxUpgradeStrategyCreate {
	ulusc.mutation.SetDescription(s)
	return ulusc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetNillableDescription(s *string) *UpgradeLnxUpgradeStrategyCreate {
	if s != nil {
		ulusc.SetDescription(*s)
	}
	return ulusc
}

// SetLnxID sets the "lnx_id" field.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetLnxID(i int) *UpgradeLnxUpgradeStrategyCreate {
	ulusc.mutation.SetLnxID(i)
	return ulusc
}

// SetLnxVersionID sets the "lnx_version_id" field.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetLnxVersionID(i int) *UpgradeLnxUpgradeStrategyCreate {
	ulusc.mutation.SetLnxVersionID(i)
	return ulusc
}

// SetBeginDatetime sets the "begin_datetime" field.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetBeginDatetime(t time.Time) *UpgradeLnxUpgradeStrategyCreate {
	ulusc.mutation.SetBeginDatetime(t)
	return ulusc
}

// SetEndDatetime sets the "end_datetime" field.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetEndDatetime(t time.Time) *UpgradeLnxUpgradeStrategyCreate {
	ulusc.mutation.SetEndDatetime(t)
	return ulusc
}

// SetUpgradeType sets the "upgrade_type" field.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetUpgradeType(i int32) *UpgradeLnxUpgradeStrategyCreate {
	ulusc.mutation.SetUpgradeType(i)
	return ulusc
}

// SetPromptUpgradeContent sets the "prompt_upgrade_content" field.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetPromptUpgradeContent(s string) *UpgradeLnxUpgradeStrategyCreate {
	ulusc.mutation.SetPromptUpgradeContent(s)
	return ulusc
}

// SetNillablePromptUpgradeContent sets the "prompt_upgrade_content" field if the given value is not nil.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetNillablePromptUpgradeContent(s *string) *UpgradeLnxUpgradeStrategyCreate {
	if s != nil {
		ulusc.SetPromptUpgradeContent(*s)
	}
	return ulusc
}

// SetUpgradeDevType sets the "upgrade_dev_type" field.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetUpgradeDevType(i int32) *UpgradeLnxUpgradeStrategyCreate {
	ulusc.mutation.SetUpgradeDevType(i)
	return ulusc
}

// SetUpgradeDevData sets the "upgrade_dev_data" field.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetUpgradeDevData(s string) *UpgradeLnxUpgradeStrategyCreate {
	ulusc.mutation.SetUpgradeDevData(s)
	return ulusc
}

// SetUpgradeVersionType sets the "upgrade_version_type" field.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetUpgradeVersionType(i int32) *UpgradeLnxUpgradeStrategyCreate {
	ulusc.mutation.SetUpgradeVersionType(i)
	return ulusc
}

// SetUpgradeVersionData sets the "upgrade_version_data" field.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetUpgradeVersionData(s string) *UpgradeLnxUpgradeStrategyCreate {
	ulusc.mutation.SetUpgradeVersionData(s)
	return ulusc
}

// SetIsGray sets the "is_gray" field.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetIsGray(i int32) *UpgradeLnxUpgradeStrategyCreate {
	ulusc.mutation.SetIsGray(i)
	return ulusc
}

// SetGrayData sets the "gray_data" field.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetGrayData(s string) *UpgradeLnxUpgradeStrategyCreate {
	ulusc.mutation.SetGrayData(s)
	return ulusc
}

// SetIsFlowLimit sets the "is_flow_limit" field.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetIsFlowLimit(i int32) *UpgradeLnxUpgradeStrategyCreate {
	ulusc.mutation.SetIsFlowLimit(i)
	return ulusc
}

// SetFlowLimitData sets the "flow_limit_data" field.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetFlowLimitData(s string) *UpgradeLnxUpgradeStrategyCreate {
	ulusc.mutation.SetFlowLimitData(s)
	return ulusc
}

// SetIsDel sets the "is_del" field.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetIsDel(i int32) *UpgradeLnxUpgradeStrategyCreate {
	ulusc.mutation.SetIsDel(i)
	return ulusc
}

// SetCreateAt sets the "create_at" field.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetCreateAt(t time.Time) *UpgradeLnxUpgradeStrategyCreate {
	ulusc.mutation.SetCreateAt(t)
	return ulusc
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetNillableCreateAt(t *time.Time) *UpgradeLnxUpgradeStrategyCreate {
	if t != nil {
		ulusc.SetCreateAt(*t)
	}
	return ulusc
}

// SetUpdateAt sets the "update_at" field.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetUpdateAt(t time.Time) *UpgradeLnxUpgradeStrategyCreate {
	ulusc.mutation.SetUpdateAt(t)
	return ulusc
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetNillableUpdateAt(t *time.Time) *UpgradeLnxUpgradeStrategyCreate {
	if t != nil {
		ulusc.SetUpdateAt(*t)
	}
	return ulusc
}

// SetID sets the "id" field.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SetID(i int) *UpgradeLnxUpgradeStrategyCreate {
	ulusc.mutation.SetID(i)
	return ulusc
}

// Mutation returns the UpgradeLnxUpgradeStrategyMutation object of the builder.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) Mutation() *UpgradeLnxUpgradeStrategyMutation {
	return ulusc.mutation
}

// Save creates the UpgradeLnxUpgradeStrategy in the database.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) Save(ctx context.Context) (*UpgradeLnxUpgradeStrategy, error) {
	return withHooks(ctx, ulusc.sqlSave, ulusc.mutation, ulusc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) SaveX(ctx context.Context) *UpgradeLnxUpgradeStrategy {
	v, err := ulusc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) Exec(ctx context.Context) error {
	_, err := ulusc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) ExecX(ctx context.Context) {
	if err := ulusc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ulusc *UpgradeLnxUpgradeStrategyCreate) check() error {
	if _, ok := ulusc.mutation.CompanyID(); !ok {
		return &ValidationError{Name: "company_id", err: errors.New(`ent: missing required field "UpgradeLnxUpgradeStrategy.company_id"`)}
	}
	if _, ok := ulusc.mutation.Enable(); !ok {
		return &ValidationError{Name: "enable", err: errors.New(`ent: missing required field "UpgradeLnxUpgradeStrategy.enable"`)}
	}
	if _, ok := ulusc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "UpgradeLnxUpgradeStrategy.name"`)}
	}
	if _, ok := ulusc.mutation.LnxID(); !ok {
		return &ValidationError{Name: "lnx_id", err: errors.New(`ent: missing required field "UpgradeLnxUpgradeStrategy.lnx_id"`)}
	}
	if _, ok := ulusc.mutation.LnxVersionID(); !ok {
		return &ValidationError{Name: "lnx_version_id", err: errors.New(`ent: missing required field "UpgradeLnxUpgradeStrategy.lnx_version_id"`)}
	}
	if _, ok := ulusc.mutation.BeginDatetime(); !ok {
		return &ValidationError{Name: "begin_datetime", err: errors.New(`ent: missing required field "UpgradeLnxUpgradeStrategy.begin_datetime"`)}
	}
	if _, ok := ulusc.mutation.EndDatetime(); !ok {
		return &ValidationError{Name: "end_datetime", err: errors.New(`ent: missing required field "UpgradeLnxUpgradeStrategy.end_datetime"`)}
	}
	if _, ok := ulusc.mutation.UpgradeType(); !ok {
		return &ValidationError{Name: "upgrade_type", err: errors.New(`ent: missing required field "UpgradeLnxUpgradeStrategy.upgrade_type"`)}
	}
	if _, ok := ulusc.mutation.UpgradeDevType(); !ok {
		return &ValidationError{Name: "upgrade_dev_type", err: errors.New(`ent: missing required field "UpgradeLnxUpgradeStrategy.upgrade_dev_type"`)}
	}
	if _, ok := ulusc.mutation.UpgradeDevData(); !ok {
		return &ValidationError{Name: "upgrade_dev_data", err: errors.New(`ent: missing required field "UpgradeLnxUpgradeStrategy.upgrade_dev_data"`)}
	}
	if _, ok := ulusc.mutation.UpgradeVersionType(); !ok {
		return &ValidationError{Name: "upgrade_version_type", err: errors.New(`ent: missing required field "UpgradeLnxUpgradeStrategy.upgrade_version_type"`)}
	}
	if _, ok := ulusc.mutation.UpgradeVersionData(); !ok {
		return &ValidationError{Name: "upgrade_version_data", err: errors.New(`ent: missing required field "UpgradeLnxUpgradeStrategy.upgrade_version_data"`)}
	}
	if _, ok := ulusc.mutation.IsGray(); !ok {
		return &ValidationError{Name: "is_gray", err: errors.New(`ent: missing required field "UpgradeLnxUpgradeStrategy.is_gray"`)}
	}
	if _, ok := ulusc.mutation.GrayData(); !ok {
		return &ValidationError{Name: "gray_data", err: errors.New(`ent: missing required field "UpgradeLnxUpgradeStrategy.gray_data"`)}
	}
	if _, ok := ulusc.mutation.IsFlowLimit(); !ok {
		return &ValidationError{Name: "is_flow_limit", err: errors.New(`ent: missing required field "UpgradeLnxUpgradeStrategy.is_flow_limit"`)}
	}
	if _, ok := ulusc.mutation.FlowLimitData(); !ok {
		return &ValidationError{Name: "flow_limit_data", err: errors.New(`ent: missing required field "UpgradeLnxUpgradeStrategy.flow_limit_data"`)}
	}
	if _, ok := ulusc.mutation.IsDel(); !ok {
		return &ValidationError{Name: "is_del", err: errors.New(`ent: missing required field "UpgradeLnxUpgradeStrategy.is_del"`)}
	}
	return nil
}

func (ulusc *UpgradeLnxUpgradeStrategyCreate) sqlSave(ctx context.Context) (*UpgradeLnxUpgradeStrategy, error) {
	if err := ulusc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ulusc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ulusc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	ulusc.mutation.id = &_node.ID
	ulusc.mutation.done = true
	return _node, nil
}

func (ulusc *UpgradeLnxUpgradeStrategyCreate) createSpec() (*UpgradeLnxUpgradeStrategy, *sqlgraph.CreateSpec) {
	var (
		_node = &UpgradeLnxUpgradeStrategy{config: ulusc.config}
		_spec = sqlgraph.NewCreateSpec(upgradelnxupgradestrategy.Table, sqlgraph.NewFieldSpec(upgradelnxupgradestrategy.FieldID, field.TypeInt))
	)
	if id, ok := ulusc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ulusc.mutation.CompanyID(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldCompanyID, field.TypeInt, value)
		_node.CompanyID = value
	}
	if value, ok := ulusc.mutation.Enable(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldEnable, field.TypeInt32, value)
		_node.Enable = value
	}
	if value, ok := ulusc.mutation.Name(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := ulusc.mutation.Description(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := ulusc.mutation.LnxID(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldLnxID, field.TypeInt, value)
		_node.LnxID = value
	}
	if value, ok := ulusc.mutation.LnxVersionID(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldLnxVersionID, field.TypeInt, value)
		_node.LnxVersionID = value
	}
	if value, ok := ulusc.mutation.BeginDatetime(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldBeginDatetime, field.TypeTime, value)
		_node.BeginDatetime = value
	}
	if value, ok := ulusc.mutation.EndDatetime(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldEndDatetime, field.TypeTime, value)
		_node.EndDatetime = value
	}
	if value, ok := ulusc.mutation.UpgradeType(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldUpgradeType, field.TypeInt32, value)
		_node.UpgradeType = value
	}
	if value, ok := ulusc.mutation.PromptUpgradeContent(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldPromptUpgradeContent, field.TypeString, value)
		_node.PromptUpgradeContent = value
	}
	if value, ok := ulusc.mutation.UpgradeDevType(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldUpgradeDevType, field.TypeInt32, value)
		_node.UpgradeDevType = value
	}
	if value, ok := ulusc.mutation.UpgradeDevData(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldUpgradeDevData, field.TypeString, value)
		_node.UpgradeDevData = value
	}
	if value, ok := ulusc.mutation.UpgradeVersionType(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldUpgradeVersionType, field.TypeInt32, value)
		_node.UpgradeVersionType = value
	}
	if value, ok := ulusc.mutation.UpgradeVersionData(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldUpgradeVersionData, field.TypeString, value)
		_node.UpgradeVersionData = value
	}
	if value, ok := ulusc.mutation.IsGray(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldIsGray, field.TypeInt32, value)
		_node.IsGray = value
	}
	if value, ok := ulusc.mutation.GrayData(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldGrayData, field.TypeString, value)
		_node.GrayData = value
	}
	if value, ok := ulusc.mutation.IsFlowLimit(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldIsFlowLimit, field.TypeInt32, value)
		_node.IsFlowLimit = value
	}
	if value, ok := ulusc.mutation.FlowLimitData(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldFlowLimitData, field.TypeString, value)
		_node.FlowLimitData = value
	}
	if value, ok := ulusc.mutation.IsDel(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldIsDel, field.TypeInt32, value)
		_node.IsDel = value
	}
	if value, ok := ulusc.mutation.CreateAt(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldCreateAt, field.TypeTime, value)
		_node.CreateAt = value
	}
	if value, ok := ulusc.mutation.UpdateAt(); ok {
		_spec.SetField(upgradelnxupgradestrategy.FieldUpdateAt, field.TypeTime, value)
		_node.UpdateAt = value
	}
	return _node, _spec
}

// UpgradeLnxUpgradeStrategyCreateBulk is the builder for creating many UpgradeLnxUpgradeStrategy entities in bulk.
type UpgradeLnxUpgradeStrategyCreateBulk struct {
	config
	err      error
	builders []*UpgradeLnxUpgradeStrategyCreate
}

// Save creates the UpgradeLnxUpgradeStrategy entities in the database.
func (uluscb *UpgradeLnxUpgradeStrategyCreateBulk) Save(ctx context.Context) ([]*UpgradeLnxUpgradeStrategy, error) {
	if uluscb.err != nil {
		return nil, uluscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(uluscb.builders))
	nodes := make([]*UpgradeLnxUpgradeStrategy, len(uluscb.builders))
	mutators := make([]Mutator, len(uluscb.builders))
	for i := range uluscb.builders {
		func(i int, root context.Context) {
			builder := uluscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpgradeLnxUpgradeStrategyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uluscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uluscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uluscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uluscb *UpgradeLnxUpgradeStrategyCreateBulk) SaveX(ctx context.Context) []*UpgradeLnxUpgradeStrategy {
	v, err := uluscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uluscb *UpgradeLnxUpgradeStrategyCreateBulk) Exec(ctx context.Context) error {
	_, err := uluscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uluscb *UpgradeLnxUpgradeStrategyCreateBulk) ExecX(ctx context.Context) {
	if err := uluscb.Exec(ctx); err != nil {
		panic(err)
	}
}
