// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"upgradelink-admin-upgrade/server/ent/predicate"
	"upgradelink-admin-upgrade/server/ent/upgradelnxupgradestrategygraystrategy"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeLnxUpgradeStrategyGrayStrategyQuery is the builder for querying UpgradeLnxUpgradeStrategyGrayStrategy entities.
type UpgradeLnxUpgradeStrategyGrayStrategyQuery struct {
	config
	ctx        *QueryContext
	order      []upgradelnxupgradestrategygraystrategy.OrderOption
	inters     []Interceptor
	predicates []predicate.UpgradeLnxUpgradeStrategyGrayStrategy
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UpgradeLnxUpgradeStrategyGrayStrategyQuery builder.
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) Where(ps ...predicate.UpgradeLnxUpgradeStrategyGrayStrategy) *UpgradeLnxUpgradeStrategyGrayStrategyQuery {
	ulusgsq.predicates = append(ulusgsq.predicates, ps...)
	return ulusgsq
}

// Limit the number of records to be returned by this query.
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) Limit(limit int) *UpgradeLnxUpgradeStrategyGrayStrategyQuery {
	ulusgsq.ctx.Limit = &limit
	return ulusgsq
}

// Offset to start from.
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) Offset(offset int) *UpgradeLnxUpgradeStrategyGrayStrategyQuery {
	ulusgsq.ctx.Offset = &offset
	return ulusgsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) Unique(unique bool) *UpgradeLnxUpgradeStrategyGrayStrategyQuery {
	ulusgsq.ctx.Unique = &unique
	return ulusgsq
}

// Order specifies how the records should be ordered.
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) Order(o ...upgradelnxupgradestrategygraystrategy.OrderOption) *UpgradeLnxUpgradeStrategyGrayStrategyQuery {
	ulusgsq.order = append(ulusgsq.order, o...)
	return ulusgsq
}

// First returns the first UpgradeLnxUpgradeStrategyGrayStrategy entity from the query.
// Returns a *NotFoundError when no UpgradeLnxUpgradeStrategyGrayStrategy was found.
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) First(ctx context.Context) (*UpgradeLnxUpgradeStrategyGrayStrategy, error) {
	nodes, err := ulusgsq.Limit(1).All(setContextOp(ctx, ulusgsq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{upgradelnxupgradestrategygraystrategy.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) FirstX(ctx context.Context) *UpgradeLnxUpgradeStrategyGrayStrategy {
	node, err := ulusgsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UpgradeLnxUpgradeStrategyGrayStrategy ID from the query.
// Returns a *NotFoundError when no UpgradeLnxUpgradeStrategyGrayStrategy ID was found.
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ulusgsq.Limit(1).IDs(setContextOp(ctx, ulusgsq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{upgradelnxupgradestrategygraystrategy.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) FirstIDX(ctx context.Context) int {
	id, err := ulusgsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UpgradeLnxUpgradeStrategyGrayStrategy entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UpgradeLnxUpgradeStrategyGrayStrategy entity is found.
// Returns a *NotFoundError when no UpgradeLnxUpgradeStrategyGrayStrategy entities are found.
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) Only(ctx context.Context) (*UpgradeLnxUpgradeStrategyGrayStrategy, error) {
	nodes, err := ulusgsq.Limit(2).All(setContextOp(ctx, ulusgsq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{upgradelnxupgradestrategygraystrategy.Label}
	default:
		return nil, &NotSingularError{upgradelnxupgradestrategygraystrategy.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) OnlyX(ctx context.Context) *UpgradeLnxUpgradeStrategyGrayStrategy {
	node, err := ulusgsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UpgradeLnxUpgradeStrategyGrayStrategy ID in the query.
// Returns a *NotSingularError when more than one UpgradeLnxUpgradeStrategyGrayStrategy ID is found.
// Returns a *NotFoundError when no entities are found.
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ulusgsq.Limit(2).IDs(setContextOp(ctx, ulusgsq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{upgradelnxupgradestrategygraystrategy.Label}
	default:
		err = &NotSingularError{upgradelnxupgradestrategygraystrategy.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) OnlyIDX(ctx context.Context) int {
	id, err := ulusgsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UpgradeLnxUpgradeStrategyGrayStrategies.
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) All(ctx context.Context) ([]*UpgradeLnxUpgradeStrategyGrayStrategy, error) {
	ctx = setContextOp(ctx, ulusgsq.ctx, ent.OpQueryAll)
	if err := ulusgsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UpgradeLnxUpgradeStrategyGrayStrategy, *UpgradeLnxUpgradeStrategyGrayStrategyQuery]()
	return withInterceptors[[]*UpgradeLnxUpgradeStrategyGrayStrategy](ctx, ulusgsq, qr, ulusgsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) AllX(ctx context.Context) []*UpgradeLnxUpgradeStrategyGrayStrategy {
	nodes, err := ulusgsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UpgradeLnxUpgradeStrategyGrayStrategy IDs.
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ulusgsq.ctx.Unique == nil && ulusgsq.path != nil {
		ulusgsq.Unique(true)
	}
	ctx = setContextOp(ctx, ulusgsq.ctx, ent.OpQueryIDs)
	if err = ulusgsq.Select(upgradelnxupgradestrategygraystrategy.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) IDsX(ctx context.Context) []int {
	ids, err := ulusgsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ulusgsq.ctx, ent.OpQueryCount)
	if err := ulusgsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ulusgsq, querierCount[*UpgradeLnxUpgradeStrategyGrayStrategyQuery](), ulusgsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) CountX(ctx context.Context) int {
	count, err := ulusgsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ulusgsq.ctx, ent.OpQueryExist)
	switch _, err := ulusgsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) ExistX(ctx context.Context) bool {
	exist, err := ulusgsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UpgradeLnxUpgradeStrategyGrayStrategyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) Clone() *UpgradeLnxUpgradeStrategyGrayStrategyQuery {
	if ulusgsq == nil {
		return nil
	}
	return &UpgradeLnxUpgradeStrategyGrayStrategyQuery{
		config:     ulusgsq.config,
		ctx:        ulusgsq.ctx.Clone(),
		order:      append([]upgradelnxupgradestrategygraystrategy.OrderOption{}, ulusgsq.order...),
		inters:     append([]Interceptor{}, ulusgsq.inters...),
		predicates: append([]predicate.UpgradeLnxUpgradeStrategyGrayStrategy{}, ulusgsq.predicates...),
		// clone intermediate query.
		sql:  ulusgsq.sql.Clone(),
		path: ulusgsq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Enable int32 `json:"enable,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UpgradeLnxUpgradeStrategyGrayStrategy.Query().
//		GroupBy(upgradelnxupgradestrategygraystrategy.FieldEnable).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) GroupBy(field string, fields ...string) *UpgradeLnxUpgradeStrategyGrayStrategyGroupBy {
	ulusgsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UpgradeLnxUpgradeStrategyGrayStrategyGroupBy{build: ulusgsq}
	grbuild.flds = &ulusgsq.ctx.Fields
	grbuild.label = upgradelnxupgradestrategygraystrategy.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Enable int32 `json:"enable,omitempty"`
//	}
//
//	client.UpgradeLnxUpgradeStrategyGrayStrategy.Query().
//		Select(upgradelnxupgradestrategygraystrategy.FieldEnable).
//		Scan(ctx, &v)
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) Select(fields ...string) *UpgradeLnxUpgradeStrategyGrayStrategySelect {
	ulusgsq.ctx.Fields = append(ulusgsq.ctx.Fields, fields...)
	sbuild := &UpgradeLnxUpgradeStrategyGrayStrategySelect{UpgradeLnxUpgradeStrategyGrayStrategyQuery: ulusgsq}
	sbuild.label = upgradelnxupgradestrategygraystrategy.Label
	sbuild.flds, sbuild.scan = &ulusgsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UpgradeLnxUpgradeStrategyGrayStrategySelect configured with the given aggregations.
func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) Aggregate(fns ...AggregateFunc) *UpgradeLnxUpgradeStrategyGrayStrategySelect {
	return ulusgsq.Select().Aggregate(fns...)
}

func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ulusgsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ulusgsq); err != nil {
				return err
			}
		}
	}
	for _, f := range ulusgsq.ctx.Fields {
		if !upgradelnxupgradestrategygraystrategy.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ulusgsq.path != nil {
		prev, err := ulusgsq.path(ctx)
		if err != nil {
			return err
		}
		ulusgsq.sql = prev
	}
	return nil
}

func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UpgradeLnxUpgradeStrategyGrayStrategy, error) {
	var (
		nodes = []*UpgradeLnxUpgradeStrategyGrayStrategy{}
		_spec = ulusgsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UpgradeLnxUpgradeStrategyGrayStrategy).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UpgradeLnxUpgradeStrategyGrayStrategy{config: ulusgsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ulusgsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ulusgsq.querySpec()
	_spec.Node.Columns = ulusgsq.ctx.Fields
	if len(ulusgsq.ctx.Fields) > 0 {
		_spec.Unique = ulusgsq.ctx.Unique != nil && *ulusgsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ulusgsq.driver, _spec)
}

func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(upgradelnxupgradestrategygraystrategy.Table, upgradelnxupgradestrategygraystrategy.Columns, sqlgraph.NewFieldSpec(upgradelnxupgradestrategygraystrategy.FieldID, field.TypeInt))
	_spec.From = ulusgsq.sql
	if unique := ulusgsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ulusgsq.path != nil {
		_spec.Unique = true
	}
	if fields := ulusgsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upgradelnxupgradestrategygraystrategy.FieldID)
		for i := range fields {
			if fields[i] != upgradelnxupgradestrategygraystrategy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ulusgsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ulusgsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ulusgsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ulusgsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ulusgsq *UpgradeLnxUpgradeStrategyGrayStrategyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ulusgsq.driver.Dialect())
	t1 := builder.Table(upgradelnxupgradestrategygraystrategy.Table)
	columns := ulusgsq.ctx.Fields
	if len(columns) == 0 {
		columns = upgradelnxupgradestrategygraystrategy.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ulusgsq.sql != nil {
		selector = ulusgsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ulusgsq.ctx.Unique != nil && *ulusgsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ulusgsq.predicates {
		p(selector)
	}
	for _, p := range ulusgsq.order {
		p(selector)
	}
	if offset := ulusgsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ulusgsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UpgradeLnxUpgradeStrategyGrayStrategyGroupBy is the group-by builder for UpgradeLnxUpgradeStrategyGrayStrategy entities.
type UpgradeLnxUpgradeStrategyGrayStrategyGroupBy struct {
	selector
	build *UpgradeLnxUpgradeStrategyGrayStrategyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ulusgsgb *UpgradeLnxUpgradeStrategyGrayStrategyGroupBy) Aggregate(fns ...AggregateFunc) *UpgradeLnxUpgradeStrategyGrayStrategyGroupBy {
	ulusgsgb.fns = append(ulusgsgb.fns, fns...)
	return ulusgsgb
}

// Scan applies the selector query and scans the result into the given value.
func (ulusgsgb *UpgradeLnxUpgradeStrategyGrayStrategyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ulusgsgb.build.ctx, ent.OpQueryGroupBy)
	if err := ulusgsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpgradeLnxUpgradeStrategyGrayStrategyQuery, *UpgradeLnxUpgradeStrategyGrayStrategyGroupBy](ctx, ulusgsgb.build, ulusgsgb, ulusgsgb.build.inters, v)
}

func (ulusgsgb *UpgradeLnxUpgradeStrategyGrayStrategyGroupBy) sqlScan(ctx context.Context, root *UpgradeLnxUpgradeStrategyGrayStrategyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ulusgsgb.fns))
	for _, fn := range ulusgsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ulusgsgb.flds)+len(ulusgsgb.fns))
		for _, f := range *ulusgsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ulusgsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ulusgsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UpgradeLnxUpgradeStrategyGrayStrategySelect is the builder for selecting fields of UpgradeLnxUpgradeStrategyGrayStrategy entities.
type UpgradeLnxUpgradeStrategyGrayStrategySelect struct {
	*UpgradeLnxUpgradeStrategyGrayStrategyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ulusgss *UpgradeLnxUpgradeStrategyGrayStrategySelect) Aggregate(fns ...AggregateFunc) *UpgradeLnxUpgradeStrategyGrayStrategySelect {
	ulusgss.fns = append(ulusgss.fns, fns...)
	return ulusgss
}

// Scan applies the selector query and scans the result into the given value.
func (ulusgss *UpgradeLnxUpgradeStrategyGrayStrategySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ulusgss.ctx, ent.OpQuerySelect)
	if err := ulusgss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpgradeLnxUpgradeStrategyGrayStrategyQuery, *UpgradeLnxUpgradeStrategyGrayStrategySelect](ctx, ulusgss.UpgradeLnxUpgradeStrategyGrayStrategyQuery, ulusgss, ulusgss.inters, v)
}

func (ulusgss *UpgradeLnxUpgradeStrategyGrayStrategySelect) sqlScan(ctx context.Context, root *UpgradeLnxUpgradeStrategyGrayStrategyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ulusgss.fns))
	for _, fn := range ulusgss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ulusgss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ulusgss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
