// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"upgradelink-admin-upgrade/server/ent/upgrademacversion"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UpgradeMacVersion is the model entity for the UpgradeMacVersion schema.
type UpgradeMacVersion struct {
	config `json:"-"`
	// ID of the ent.
	// ID
	ID int `json:"id,omitempty"`
	// 公司ID
	CompanyID int `json:"company_id,omitempty"`
	// mac应用ID
	MACID int `json:"mac_id,omitempty"`
	// 云文件id
	CloudFileID string `json:"cloud_file_id,omitempty"`
	// 版本名
	VersionName string `json:"version_name,omitempty"`
	// 版本号
	VersionCode int `json:"version_code,omitempty"`
	// 机器架构:x64、arm64
	Arch string `json:"arch,omitempty"`
	// 描述信息
	Description string `json:"description,omitempty"`
	// 是否删除 0：正常；1：已删除
	IsDel int32 `json:"is_del,omitempty"`
	// 创建时间
	CreateAt time.Time `json:"create_at,omitempty"`
	// 修改时间
	UpdateAt     time.Time `json:"update_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpgradeMacVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upgrademacversion.FieldID, upgrademacversion.FieldCompanyID, upgrademacversion.FieldMACID, upgrademacversion.FieldVersionCode, upgrademacversion.FieldIsDel:
			values[i] = new(sql.NullInt64)
		case upgrademacversion.FieldCloudFileID, upgrademacversion.FieldVersionName, upgrademacversion.FieldArch, upgrademacversion.FieldDescription:
			values[i] = new(sql.NullString)
		case upgrademacversion.FieldCreateAt, upgrademacversion.FieldUpdateAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpgradeMacVersion fields.
func (umv *UpgradeMacVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upgrademacversion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			umv.ID = int(value.Int64)
		case upgrademacversion.FieldCompanyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field company_id", values[i])
			} else if value.Valid {
				umv.CompanyID = int(value.Int64)
			}
		case upgrademacversion.FieldMACID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field mac_id", values[i])
			} else if value.Valid {
				umv.MACID = int(value.Int64)
			}
		case upgrademacversion.FieldCloudFileID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cloud_file_id", values[i])
			} else if value.Valid {
				umv.CloudFileID = value.String
			}
		case upgrademacversion.FieldVersionName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version_name", values[i])
			} else if value.Valid {
				umv.VersionName = value.String
			}
		case upgrademacversion.FieldVersionCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version_code", values[i])
			} else if value.Valid {
				umv.VersionCode = int(value.Int64)
			}
		case upgrademacversion.FieldArch:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field arch", values[i])
			} else if value.Valid {
				umv.Arch = value.String
			}
		case upgrademacversion.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				umv.Description = value.String
			}
		case upgrademacversion.FieldIsDel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field is_del", values[i])
			} else if value.Valid {
				umv.IsDel = int32(value.Int64)
			}
		case upgrademacversion.FieldCreateAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_at", values[i])
			} else if value.Valid {
				umv.CreateAt = value.Time
			}
		case upgrademacversion.FieldUpdateAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_at", values[i])
			} else if value.Valid {
				umv.UpdateAt = value.Time
			}
		default:
			umv.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpgradeMacVersion.
// This includes values selected through modifiers, order, etc.
func (umv *UpgradeMacVersion) Value(name string) (ent.Value, error) {
	return umv.selectValues.Get(name)
}

// Update returns a builder for updating this UpgradeMacVersion.
// Note that you need to call UpgradeMacVersion.Unwrap() before calling this method if this UpgradeMacVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (umv *UpgradeMacVersion) Update() *UpgradeMacVersionUpdateOne {
	return NewUpgradeMacVersionClient(umv.config).UpdateOne(umv)
}

// Unwrap unwraps the UpgradeMacVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (umv *UpgradeMacVersion) Unwrap() *UpgradeMacVersion {
	_tx, ok := umv.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpgradeMacVersion is not a transactional entity")
	}
	umv.config.driver = _tx.drv
	return umv
}

// String implements the fmt.Stringer.
func (umv *UpgradeMacVersion) String() string {
	var builder strings.Builder
	builder.WriteString("UpgradeMacVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", umv.ID))
	builder.WriteString("company_id=")
	builder.WriteString(fmt.Sprintf("%v", umv.CompanyID))
	builder.WriteString(", ")
	builder.WriteString("mac_id=")
	builder.WriteString(fmt.Sprintf("%v", umv.MACID))
	builder.WriteString(", ")
	builder.WriteString("cloud_file_id=")
	builder.WriteString(umv.CloudFileID)
	builder.WriteString(", ")
	builder.WriteString("version_name=")
	builder.WriteString(umv.VersionName)
	builder.WriteString(", ")
	builder.WriteString("version_code=")
	builder.WriteString(fmt.Sprintf("%v", umv.VersionCode))
	builder.WriteString(", ")
	builder.WriteString("arch=")
	builder.WriteString(umv.Arch)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(umv.Description)
	builder.WriteString(", ")
	builder.WriteString("is_del=")
	builder.WriteString(fmt.Sprintf("%v", umv.IsDel))
	builder.WriteString(", ")
	builder.WriteString("create_at=")
	builder.WriteString(umv.CreateAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_at=")
	builder.WriteString(umv.UpdateAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UpgradeMacVersions is a parsable slice of UpgradeMacVersion.
type UpgradeMacVersions []*UpgradeMacVersion
