// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"upgradelink-admin-upgrade/server/ent/predicate"
	"upgradelink-admin-upgrade/server/ent/upgrademacversion"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeMacVersionQuery is the builder for querying UpgradeMacVersion entities.
type UpgradeMacVersionQuery struct {
	config
	ctx        *QueryContext
	order      []upgrademacversion.OrderOption
	inters     []Interceptor
	predicates []predicate.UpgradeMacVersion
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UpgradeMacVersionQuery builder.
func (umvq *UpgradeMacVersionQuery) Where(ps ...predicate.UpgradeMacVersion) *UpgradeMacVersionQuery {
	umvq.predicates = append(umvq.predicates, ps...)
	return umvq
}

// Limit the number of records to be returned by this query.
func (umvq *UpgradeMacVersionQuery) Limit(limit int) *UpgradeMacVersionQuery {
	umvq.ctx.Limit = &limit
	return umvq
}

// Offset to start from.
func (umvq *UpgradeMacVersionQuery) Offset(offset int) *UpgradeMacVersionQuery {
	umvq.ctx.Offset = &offset
	return umvq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (umvq *UpgradeMacVersionQuery) Unique(unique bool) *UpgradeMacVersionQuery {
	umvq.ctx.Unique = &unique
	return umvq
}

// Order specifies how the records should be ordered.
func (umvq *UpgradeMacVersionQuery) Order(o ...upgrademacversion.OrderOption) *UpgradeMacVersionQuery {
	umvq.order = append(umvq.order, o...)
	return umvq
}

// First returns the first UpgradeMacVersion entity from the query.
// Returns a *NotFoundError when no UpgradeMacVersion was found.
func (umvq *UpgradeMacVersionQuery) First(ctx context.Context) (*UpgradeMacVersion, error) {
	nodes, err := umvq.Limit(1).All(setContextOp(ctx, umvq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{upgrademacversion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (umvq *UpgradeMacVersionQuery) FirstX(ctx context.Context) *UpgradeMacVersion {
	node, err := umvq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UpgradeMacVersion ID from the query.
// Returns a *NotFoundError when no UpgradeMacVersion ID was found.
func (umvq *UpgradeMacVersionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = umvq.Limit(1).IDs(setContextOp(ctx, umvq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{upgrademacversion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (umvq *UpgradeMacVersionQuery) FirstIDX(ctx context.Context) int {
	id, err := umvq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UpgradeMacVersion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UpgradeMacVersion entity is found.
// Returns a *NotFoundError when no UpgradeMacVersion entities are found.
func (umvq *UpgradeMacVersionQuery) Only(ctx context.Context) (*UpgradeMacVersion, error) {
	nodes, err := umvq.Limit(2).All(setContextOp(ctx, umvq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{upgrademacversion.Label}
	default:
		return nil, &NotSingularError{upgrademacversion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (umvq *UpgradeMacVersionQuery) OnlyX(ctx context.Context) *UpgradeMacVersion {
	node, err := umvq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UpgradeMacVersion ID in the query.
// Returns a *NotSingularError when more than one UpgradeMacVersion ID is found.
// Returns a *NotFoundError when no entities are found.
func (umvq *UpgradeMacVersionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = umvq.Limit(2).IDs(setContextOp(ctx, umvq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{upgrademacversion.Label}
	default:
		err = &NotSingularError{upgrademacversion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (umvq *UpgradeMacVersionQuery) OnlyIDX(ctx context.Context) int {
	id, err := umvq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UpgradeMacVersions.
func (umvq *UpgradeMacVersionQuery) All(ctx context.Context) ([]*UpgradeMacVersion, error) {
	ctx = setContextOp(ctx, umvq.ctx, ent.OpQueryAll)
	if err := umvq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UpgradeMacVersion, *UpgradeMacVersionQuery]()
	return withInterceptors[[]*UpgradeMacVersion](ctx, umvq, qr, umvq.inters)
}

// AllX is like All, but panics if an error occurs.
func (umvq *UpgradeMacVersionQuery) AllX(ctx context.Context) []*UpgradeMacVersion {
	nodes, err := umvq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UpgradeMacVersion IDs.
func (umvq *UpgradeMacVersionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if umvq.ctx.Unique == nil && umvq.path != nil {
		umvq.Unique(true)
	}
	ctx = setContextOp(ctx, umvq.ctx, ent.OpQueryIDs)
	if err = umvq.Select(upgrademacversion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (umvq *UpgradeMacVersionQuery) IDsX(ctx context.Context) []int {
	ids, err := umvq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (umvq *UpgradeMacVersionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, umvq.ctx, ent.OpQueryCount)
	if err := umvq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, umvq, querierCount[*UpgradeMacVersionQuery](), umvq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (umvq *UpgradeMacVersionQuery) CountX(ctx context.Context) int {
	count, err := umvq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (umvq *UpgradeMacVersionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, umvq.ctx, ent.OpQueryExist)
	switch _, err := umvq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (umvq *UpgradeMacVersionQuery) ExistX(ctx context.Context) bool {
	exist, err := umvq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UpgradeMacVersionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (umvq *UpgradeMacVersionQuery) Clone() *UpgradeMacVersionQuery {
	if umvq == nil {
		return nil
	}
	return &UpgradeMacVersionQuery{
		config:     umvq.config,
		ctx:        umvq.ctx.Clone(),
		order:      append([]upgrademacversion.OrderOption{}, umvq.order...),
		inters:     append([]Interceptor{}, umvq.inters...),
		predicates: append([]predicate.UpgradeMacVersion{}, umvq.predicates...),
		// clone intermediate query.
		sql:  umvq.sql.Clone(),
		path: umvq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CompanyID int `json:"company_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UpgradeMacVersion.Query().
//		GroupBy(upgrademacversion.FieldCompanyID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (umvq *UpgradeMacVersionQuery) GroupBy(field string, fields ...string) *UpgradeMacVersionGroupBy {
	umvq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UpgradeMacVersionGroupBy{build: umvq}
	grbuild.flds = &umvq.ctx.Fields
	grbuild.label = upgrademacversion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CompanyID int `json:"company_id,omitempty"`
//	}
//
//	client.UpgradeMacVersion.Query().
//		Select(upgrademacversion.FieldCompanyID).
//		Scan(ctx, &v)
func (umvq *UpgradeMacVersionQuery) Select(fields ...string) *UpgradeMacVersionSelect {
	umvq.ctx.Fields = append(umvq.ctx.Fields, fields...)
	sbuild := &UpgradeMacVersionSelect{UpgradeMacVersionQuery: umvq}
	sbuild.label = upgrademacversion.Label
	sbuild.flds, sbuild.scan = &umvq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UpgradeMacVersionSelect configured with the given aggregations.
func (umvq *UpgradeMacVersionQuery) Aggregate(fns ...AggregateFunc) *UpgradeMacVersionSelect {
	return umvq.Select().Aggregate(fns...)
}

func (umvq *UpgradeMacVersionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range umvq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, umvq); err != nil {
				return err
			}
		}
	}
	for _, f := range umvq.ctx.Fields {
		if !upgrademacversion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if umvq.path != nil {
		prev, err := umvq.path(ctx)
		if err != nil {
			return err
		}
		umvq.sql = prev
	}
	return nil
}

func (umvq *UpgradeMacVersionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UpgradeMacVersion, error) {
	var (
		nodes = []*UpgradeMacVersion{}
		_spec = umvq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UpgradeMacVersion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UpgradeMacVersion{config: umvq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, umvq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (umvq *UpgradeMacVersionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := umvq.querySpec()
	_spec.Node.Columns = umvq.ctx.Fields
	if len(umvq.ctx.Fields) > 0 {
		_spec.Unique = umvq.ctx.Unique != nil && *umvq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, umvq.driver, _spec)
}

func (umvq *UpgradeMacVersionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(upgrademacversion.Table, upgrademacversion.Columns, sqlgraph.NewFieldSpec(upgrademacversion.FieldID, field.TypeInt))
	_spec.From = umvq.sql
	if unique := umvq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if umvq.path != nil {
		_spec.Unique = true
	}
	if fields := umvq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upgrademacversion.FieldID)
		for i := range fields {
			if fields[i] != upgrademacversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := umvq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := umvq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := umvq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := umvq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (umvq *UpgradeMacVersionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(umvq.driver.Dialect())
	t1 := builder.Table(upgrademacversion.Table)
	columns := umvq.ctx.Fields
	if len(columns) == 0 {
		columns = upgrademacversion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if umvq.sql != nil {
		selector = umvq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if umvq.ctx.Unique != nil && *umvq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range umvq.predicates {
		p(selector)
	}
	for _, p := range umvq.order {
		p(selector)
	}
	if offset := umvq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := umvq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UpgradeMacVersionGroupBy is the group-by builder for UpgradeMacVersion entities.
type UpgradeMacVersionGroupBy struct {
	selector
	build *UpgradeMacVersionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (umvgb *UpgradeMacVersionGroupBy) Aggregate(fns ...AggregateFunc) *UpgradeMacVersionGroupBy {
	umvgb.fns = append(umvgb.fns, fns...)
	return umvgb
}

// Scan applies the selector query and scans the result into the given value.
func (umvgb *UpgradeMacVersionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, umvgb.build.ctx, ent.OpQueryGroupBy)
	if err := umvgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpgradeMacVersionQuery, *UpgradeMacVersionGroupBy](ctx, umvgb.build, umvgb, umvgb.build.inters, v)
}

func (umvgb *UpgradeMacVersionGroupBy) sqlScan(ctx context.Context, root *UpgradeMacVersionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(umvgb.fns))
	for _, fn := range umvgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*umvgb.flds)+len(umvgb.fns))
		for _, f := range *umvgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*umvgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := umvgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UpgradeMacVersionSelect is the builder for selecting fields of UpgradeMacVersion entities.
type UpgradeMacVersionSelect struct {
	*UpgradeMacVersionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (umvs *UpgradeMacVersionSelect) Aggregate(fns ...AggregateFunc) *UpgradeMacVersionSelect {
	umvs.fns = append(umvs.fns, fns...)
	return umvs
}

// Scan applies the selector query and scans the result into the given value.
func (umvs *UpgradeMacVersionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, umvs.ctx, ent.OpQuerySelect)
	if err := umvs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpgradeMacVersionQuery, *UpgradeMacVersionSelect](ctx, umvs.UpgradeMacVersionQuery, umvs, umvs.inters, v)
}

func (umvs *UpgradeMacVersionSelect) sqlScan(ctx context.Context, root *UpgradeMacVersionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(umvs.fns))
	for _, fn := range umvs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*umvs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := umvs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
