// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"upgradelink-admin-upgrade/server/ent/predicate"
	"upgradelink-admin-upgrade/server/ent/upgradelnx"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeLnxDelete is the builder for deleting a UpgradeLnx entity.
type UpgradeLnxDelete struct {
	config
	hooks    []Hook
	mutation *UpgradeLnxMutation
}

// Where appends a list predicates to the UpgradeLnxDelete builder.
func (uld *UpgradeLnxDelete) Where(ps ...predicate.UpgradeLnx) *UpgradeLnxDelete {
	uld.mutation.Where(ps...)
	return uld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uld *UpgradeLnxDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, uld.sqlExec, uld.mutation, uld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (uld *UpgradeLnxDelete) ExecX(ctx context.Context) int {
	n, err := uld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uld *UpgradeLnxDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(upgradelnx.Table, sqlgraph.NewFieldSpec(upgradelnx.FieldID, field.TypeInt))
	if ps := uld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, uld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	uld.mutation.done = true
	return affected, err
}

// UpgradeLnxDeleteOne is the builder for deleting a single UpgradeLnx entity.
type UpgradeLnxDeleteOne struct {
	uld *UpgradeLnxDelete
}

// Where appends a list predicates to the UpgradeLnxDelete builder.
func (uldo *UpgradeLnxDeleteOne) Where(ps ...predicate.UpgradeLnx) *UpgradeLnxDeleteOne {
	uldo.uld.mutation.Where(ps...)
	return uldo
}

// Exec executes the deletion query.
func (uldo *UpgradeLnxDeleteOne) Exec(ctx context.Context) error {
	n, err := uldo.uld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{upgradelnx.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uldo *UpgradeLnxDeleteOne) ExecX(ctx context.Context) {
	if err := uldo.Exec(ctx); err != nil {
		panic(err)
	}
}
