// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"upgradelink-admin-upgrade/server/ent/predicate"
	"upgradelink-admin-upgrade/server/ent/upgrademacupgradestrategyflowlimitstrategy"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeMacUpgradeStrategyFlowLimitStrategyDelete is the builder for deleting a UpgradeMacUpgradeStrategyFlowLimitStrategy entity.
type UpgradeMacUpgradeStrategyFlowLimitStrategyDelete struct {
	config
	hooks    []Hook
	mutation *UpgradeMacUpgradeStrategyFlowLimitStrategyMutation
}

// Where appends a list predicates to the UpgradeMacUpgradeStrategyFlowLimitStrategyDelete builder.
func (umusflsd *UpgradeMacUpgradeStrategyFlowLimitStrategyDelete) Where(ps ...predicate.UpgradeMacUpgradeStrategyFlowLimitStrategy) *UpgradeMacUpgradeStrategyFlowLimitStrategyDelete {
	umusflsd.mutation.Where(ps...)
	return umusflsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (umusflsd *UpgradeMacUpgradeStrategyFlowLimitStrategyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, umusflsd.sqlExec, umusflsd.mutation, umusflsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (umusflsd *UpgradeMacUpgradeStrategyFlowLimitStrategyDelete) ExecX(ctx context.Context) int {
	n, err := umusflsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (umusflsd *UpgradeMacUpgradeStrategyFlowLimitStrategyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(upgrademacupgradestrategyflowlimitstrategy.Table, sqlgraph.NewFieldSpec(upgrademacupgradestrategyflowlimitstrategy.FieldID, field.TypeInt))
	if ps := umusflsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, umusflsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	umusflsd.mutation.done = true
	return affected, err
}

// UpgradeMacUpgradeStrategyFlowLimitStrategyDeleteOne is the builder for deleting a single UpgradeMacUpgradeStrategyFlowLimitStrategy entity.
type UpgradeMacUpgradeStrategyFlowLimitStrategyDeleteOne struct {
	umusflsd *UpgradeMacUpgradeStrategyFlowLimitStrategyDelete
}

// Where appends a list predicates to the UpgradeMacUpgradeStrategyFlowLimitStrategyDelete builder.
func (umusflsdo *UpgradeMacUpgradeStrategyFlowLimitStrategyDeleteOne) Where(ps ...predicate.UpgradeMacUpgradeStrategyFlowLimitStrategy) *UpgradeMacUpgradeStrategyFlowLimitStrategyDeleteOne {
	umusflsdo.umusflsd.mutation.Where(ps...)
	return umusflsdo
}

// Exec executes the deletion query.
func (umusflsdo *UpgradeMacUpgradeStrategyFlowLimitStrategyDeleteOne) Exec(ctx context.Context) error {
	n, err := umusflsdo.umusflsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{upgrademacupgradestrategyflowlimitstrategy.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (umusflsdo *UpgradeMacUpgradeStrategyFlowLimitStrategyDeleteOne) ExecX(ctx context.Context) {
	if err := umusflsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
