// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"upgradelink-admin-upgrade/server/ent/predicate"
	"upgradelink-admin-upgrade/server/ent/upgradelnx"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeLnxQuery is the builder for querying UpgradeLnx entities.
type UpgradeLnxQuery struct {
	config
	ctx        *QueryContext
	order      []upgradelnx.OrderOption
	inters     []Interceptor
	predicates []predicate.UpgradeLnx
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UpgradeLnxQuery builder.
func (ulq *UpgradeLnxQuery) Where(ps ...predicate.UpgradeLnx) *UpgradeLnxQuery {
	ulq.predicates = append(ulq.predicates, ps...)
	return ulq
}

// Limit the number of records to be returned by this query.
func (ulq *UpgradeLnxQuery) Limit(limit int) *UpgradeLnxQuery {
	ulq.ctx.Limit = &limit
	return ulq
}

// Offset to start from.
func (ulq *UpgradeLnxQuery) Offset(offset int) *UpgradeLnxQuery {
	ulq.ctx.Offset = &offset
	return ulq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ulq *UpgradeLnxQuery) Unique(unique bool) *UpgradeLnxQuery {
	ulq.ctx.Unique = &unique
	return ulq
}

// Order specifies how the records should be ordered.
func (ulq *UpgradeLnxQuery) Order(o ...upgradelnx.OrderOption) *UpgradeLnxQuery {
	ulq.order = append(ulq.order, o...)
	return ulq
}

// First returns the first UpgradeLnx entity from the query.
// Returns a *NotFoundError when no UpgradeLnx was found.
func (ulq *UpgradeLnxQuery) First(ctx context.Context) (*UpgradeLnx, error) {
	nodes, err := ulq.Limit(1).All(setContextOp(ctx, ulq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{upgradelnx.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ulq *UpgradeLnxQuery) FirstX(ctx context.Context) *UpgradeLnx {
	node, err := ulq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UpgradeLnx ID from the query.
// Returns a *NotFoundError when no UpgradeLnx ID was found.
func (ulq *UpgradeLnxQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ulq.Limit(1).IDs(setContextOp(ctx, ulq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{upgradelnx.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ulq *UpgradeLnxQuery) FirstIDX(ctx context.Context) int {
	id, err := ulq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UpgradeLnx entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UpgradeLnx entity is found.
// Returns a *NotFoundError when no UpgradeLnx entities are found.
func (ulq *UpgradeLnxQuery) Only(ctx context.Context) (*UpgradeLnx, error) {
	nodes, err := ulq.Limit(2).All(setContextOp(ctx, ulq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{upgradelnx.Label}
	default:
		return nil, &NotSingularError{upgradelnx.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ulq *UpgradeLnxQuery) OnlyX(ctx context.Context) *UpgradeLnx {
	node, err := ulq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UpgradeLnx ID in the query.
// Returns a *NotSingularError when more than one UpgradeLnx ID is found.
// Returns a *NotFoundError when no entities are found.
func (ulq *UpgradeLnxQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ulq.Limit(2).IDs(setContextOp(ctx, ulq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{upgradelnx.Label}
	default:
		err = &NotSingularError{upgradelnx.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ulq *UpgradeLnxQuery) OnlyIDX(ctx context.Context) int {
	id, err := ulq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UpgradeLnxes.
func (ulq *UpgradeLnxQuery) All(ctx context.Context) ([]*UpgradeLnx, error) {
	ctx = setContextOp(ctx, ulq.ctx, ent.OpQueryAll)
	if err := ulq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UpgradeLnx, *UpgradeLnxQuery]()
	return withInterceptors[[]*UpgradeLnx](ctx, ulq, qr, ulq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ulq *UpgradeLnxQuery) AllX(ctx context.Context) []*UpgradeLnx {
	nodes, err := ulq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UpgradeLnx IDs.
func (ulq *UpgradeLnxQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ulq.ctx.Unique == nil && ulq.path != nil {
		ulq.Unique(true)
	}
	ctx = setContextOp(ctx, ulq.ctx, ent.OpQueryIDs)
	if err = ulq.Select(upgradelnx.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ulq *UpgradeLnxQuery) IDsX(ctx context.Context) []int {
	ids, err := ulq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ulq *UpgradeLnxQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ulq.ctx, ent.OpQueryCount)
	if err := ulq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ulq, querierCount[*UpgradeLnxQuery](), ulq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ulq *UpgradeLnxQuery) CountX(ctx context.Context) int {
	count, err := ulq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ulq *UpgradeLnxQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ulq.ctx, ent.OpQueryExist)
	switch _, err := ulq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ulq *UpgradeLnxQuery) ExistX(ctx context.Context) bool {
	exist, err := ulq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UpgradeLnxQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ulq *UpgradeLnxQuery) Clone() *UpgradeLnxQuery {
	if ulq == nil {
		return nil
	}
	return &UpgradeLnxQuery{
		config:     ulq.config,
		ctx:        ulq.ctx.Clone(),
		order:      append([]upgradelnx.OrderOption{}, ulq.order...),
		inters:     append([]Interceptor{}, ulq.inters...),
		predicates: append([]predicate.UpgradeLnx{}, ulq.predicates...),
		// clone intermediate query.
		sql:  ulq.sql.Clone(),
		path: ulq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CompanyID int `json:"company_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UpgradeLnx.Query().
//		GroupBy(upgradelnx.FieldCompanyID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ulq *UpgradeLnxQuery) GroupBy(field string, fields ...string) *UpgradeLnxGroupBy {
	ulq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UpgradeLnxGroupBy{build: ulq}
	grbuild.flds = &ulq.ctx.Fields
	grbuild.label = upgradelnx.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CompanyID int `json:"company_id,omitempty"`
//	}
//
//	client.UpgradeLnx.Query().
//		Select(upgradelnx.FieldCompanyID).
//		Scan(ctx, &v)
func (ulq *UpgradeLnxQuery) Select(fields ...string) *UpgradeLnxSelect {
	ulq.ctx.Fields = append(ulq.ctx.Fields, fields...)
	sbuild := &UpgradeLnxSelect{UpgradeLnxQuery: ulq}
	sbuild.label = upgradelnx.Label
	sbuild.flds, sbuild.scan = &ulq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UpgradeLnxSelect configured with the given aggregations.
func (ulq *UpgradeLnxQuery) Aggregate(fns ...AggregateFunc) *UpgradeLnxSelect {
	return ulq.Select().Aggregate(fns...)
}

func (ulq *UpgradeLnxQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ulq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ulq); err != nil {
				return err
			}
		}
	}
	for _, f := range ulq.ctx.Fields {
		if !upgradelnx.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ulq.path != nil {
		prev, err := ulq.path(ctx)
		if err != nil {
			return err
		}
		ulq.sql = prev
	}
	return nil
}

func (ulq *UpgradeLnxQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UpgradeLnx, error) {
	var (
		nodes = []*UpgradeLnx{}
		_spec = ulq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UpgradeLnx).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UpgradeLnx{config: ulq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ulq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ulq *UpgradeLnxQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ulq.querySpec()
	_spec.Node.Columns = ulq.ctx.Fields
	if len(ulq.ctx.Fields) > 0 {
		_spec.Unique = ulq.ctx.Unique != nil && *ulq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ulq.driver, _spec)
}

func (ulq *UpgradeLnxQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(upgradelnx.Table, upgradelnx.Columns, sqlgraph.NewFieldSpec(upgradelnx.FieldID, field.TypeInt))
	_spec.From = ulq.sql
	if unique := ulq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ulq.path != nil {
		_spec.Unique = true
	}
	if fields := ulq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upgradelnx.FieldID)
		for i := range fields {
			if fields[i] != upgradelnx.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ulq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ulq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ulq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ulq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ulq *UpgradeLnxQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ulq.driver.Dialect())
	t1 := builder.Table(upgradelnx.Table)
	columns := ulq.ctx.Fields
	if len(columns) == 0 {
		columns = upgradelnx.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ulq.sql != nil {
		selector = ulq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ulq.ctx.Unique != nil && *ulq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ulq.predicates {
		p(selector)
	}
	for _, p := range ulq.order {
		p(selector)
	}
	if offset := ulq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ulq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UpgradeLnxGroupBy is the group-by builder for UpgradeLnx entities.
type UpgradeLnxGroupBy struct {
	selector
	build *UpgradeLnxQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ulgb *UpgradeLnxGroupBy) Aggregate(fns ...AggregateFunc) *UpgradeLnxGroupBy {
	ulgb.fns = append(ulgb.fns, fns...)
	return ulgb
}

// Scan applies the selector query and scans the result into the given value.
func (ulgb *UpgradeLnxGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ulgb.build.ctx, ent.OpQueryGroupBy)
	if err := ulgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpgradeLnxQuery, *UpgradeLnxGroupBy](ctx, ulgb.build, ulgb, ulgb.build.inters, v)
}

func (ulgb *UpgradeLnxGroupBy) sqlScan(ctx context.Context, root *UpgradeLnxQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ulgb.fns))
	for _, fn := range ulgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ulgb.flds)+len(ulgb.fns))
		for _, f := range *ulgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ulgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ulgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UpgradeLnxSelect is the builder for selecting fields of UpgradeLnx entities.
type UpgradeLnxSelect struct {
	*UpgradeLnxQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uls *UpgradeLnxSelect) Aggregate(fns ...AggregateFunc) *UpgradeLnxSelect {
	uls.fns = append(uls.fns, fns...)
	return uls
}

// Scan applies the selector query and scans the result into the given value.
func (uls *UpgradeLnxSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uls.ctx, ent.OpQuerySelect)
	if err := uls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpgradeLnxQuery, *UpgradeLnxSelect](ctx, uls.UpgradeLnxQuery, uls, uls.inters, v)
}

func (uls *UpgradeLnxSelect) sqlScan(ctx context.Context, root *UpgradeLnxQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(uls.fns))
	for _, fn := range uls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*uls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
