// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"upgradelink-admin-upgrade/server/ent/predicate"
	"upgradelink-admin-upgrade/server/ent/upgrademacupgradestrategy"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeMacUpgradeStrategyQuery is the builder for querying UpgradeMacUpgradeStrategy entities.
type UpgradeMacUpgradeStrategyQuery struct {
	config
	ctx        *QueryContext
	order      []upgrademacupgradestrategy.OrderOption
	inters     []Interceptor
	predicates []predicate.UpgradeMacUpgradeStrategy
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UpgradeMacUpgradeStrategyQuery builder.
func (umusq *UpgradeMacUpgradeStrategyQuery) Where(ps ...predicate.UpgradeMacUpgradeStrategy) *UpgradeMacUpgradeStrategyQuery {
	umusq.predicates = append(umusq.predicates, ps...)
	return umusq
}

// Limit the number of records to be returned by this query.
func (umusq *UpgradeMacUpgradeStrategyQuery) Limit(limit int) *UpgradeMacUpgradeStrategyQuery {
	umusq.ctx.Limit = &limit
	return umusq
}

// Offset to start from.
func (umusq *UpgradeMacUpgradeStrategyQuery) Offset(offset int) *UpgradeMacUpgradeStrategyQuery {
	umusq.ctx.Offset = &offset
	return umusq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (umusq *UpgradeMacUpgradeStrategyQuery) Unique(unique bool) *UpgradeMacUpgradeStrategyQuery {
	umusq.ctx.Unique = &unique
	return umusq
}

// Order specifies how the records should be ordered.
func (umusq *UpgradeMacUpgradeStrategyQuery) Order(o ...upgrademacupgradestrategy.OrderOption) *UpgradeMacUpgradeStrategyQuery {
	umusq.order = append(umusq.order, o...)
	return umusq
}

// First returns the first UpgradeMacUpgradeStrategy entity from the query.
// Returns a *NotFoundError when no UpgradeMacUpgradeStrategy was found.
func (umusq *UpgradeMacUpgradeStrategyQuery) First(ctx context.Context) (*UpgradeMacUpgradeStrategy, error) {
	nodes, err := umusq.Limit(1).All(setContextOp(ctx, umusq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{upgrademacupgradestrategy.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (umusq *UpgradeMacUpgradeStrategyQuery) FirstX(ctx context.Context) *UpgradeMacUpgradeStrategy {
	node, err := umusq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UpgradeMacUpgradeStrategy ID from the query.
// Returns a *NotFoundError when no UpgradeMacUpgradeStrategy ID was found.
func (umusq *UpgradeMacUpgradeStrategyQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = umusq.Limit(1).IDs(setContextOp(ctx, umusq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{upgrademacupgradestrategy.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (umusq *UpgradeMacUpgradeStrategyQuery) FirstIDX(ctx context.Context) int {
	id, err := umusq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UpgradeMacUpgradeStrategy entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UpgradeMacUpgradeStrategy entity is found.
// Returns a *NotFoundError when no UpgradeMacUpgradeStrategy entities are found.
func (umusq *UpgradeMacUpgradeStrategyQuery) Only(ctx context.Context) (*UpgradeMacUpgradeStrategy, error) {
	nodes, err := umusq.Limit(2).All(setContextOp(ctx, umusq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{upgrademacupgradestrategy.Label}
	default:
		return nil, &NotSingularError{upgrademacupgradestrategy.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (umusq *UpgradeMacUpgradeStrategyQuery) OnlyX(ctx context.Context) *UpgradeMacUpgradeStrategy {
	node, err := umusq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UpgradeMacUpgradeStrategy ID in the query.
// Returns a *NotSingularError when more than one UpgradeMacUpgradeStrategy ID is found.
// Returns a *NotFoundError when no entities are found.
func (umusq *UpgradeMacUpgradeStrategyQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = umusq.Limit(2).IDs(setContextOp(ctx, umusq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{upgrademacupgradestrategy.Label}
	default:
		err = &NotSingularError{upgrademacupgradestrategy.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (umusq *UpgradeMacUpgradeStrategyQuery) OnlyIDX(ctx context.Context) int {
	id, err := umusq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UpgradeMacUpgradeStrategies.
func (umusq *UpgradeMacUpgradeStrategyQuery) All(ctx context.Context) ([]*UpgradeMacUpgradeStrategy, error) {
	ctx = setContextOp(ctx, umusq.ctx, ent.OpQueryAll)
	if err := umusq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UpgradeMacUpgradeStrategy, *UpgradeMacUpgradeStrategyQuery]()
	return withInterceptors[[]*UpgradeMacUpgradeStrategy](ctx, umusq, qr, umusq.inters)
}

// AllX is like All, but panics if an error occurs.
func (umusq *UpgradeMacUpgradeStrategyQuery) AllX(ctx context.Context) []*UpgradeMacUpgradeStrategy {
	nodes, err := umusq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UpgradeMacUpgradeStrategy IDs.
func (umusq *UpgradeMacUpgradeStrategyQuery) IDs(ctx context.Context) (ids []int, err error) {
	if umusq.ctx.Unique == nil && umusq.path != nil {
		umusq.Unique(true)
	}
	ctx = setContextOp(ctx, umusq.ctx, ent.OpQueryIDs)
	if err = umusq.Select(upgrademacupgradestrategy.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (umusq *UpgradeMacUpgradeStrategyQuery) IDsX(ctx context.Context) []int {
	ids, err := umusq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (umusq *UpgradeMacUpgradeStrategyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, umusq.ctx, ent.OpQueryCount)
	if err := umusq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, umusq, querierCount[*UpgradeMacUpgradeStrategyQuery](), umusq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (umusq *UpgradeMacUpgradeStrategyQuery) CountX(ctx context.Context) int {
	count, err := umusq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (umusq *UpgradeMacUpgradeStrategyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, umusq.ctx, ent.OpQueryExist)
	switch _, err := umusq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (umusq *UpgradeMacUpgradeStrategyQuery) ExistX(ctx context.Context) bool {
	exist, err := umusq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UpgradeMacUpgradeStrategyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (umusq *UpgradeMacUpgradeStrategyQuery) Clone() *UpgradeMacUpgradeStrategyQuery {
	if umusq == nil {
		return nil
	}
	return &UpgradeMacUpgradeStrategyQuery{
		config:     umusq.config,
		ctx:        umusq.ctx.Clone(),
		order:      append([]upgrademacupgradestrategy.OrderOption{}, umusq.order...),
		inters:     append([]Interceptor{}, umusq.inters...),
		predicates: append([]predicate.UpgradeMacUpgradeStrategy{}, umusq.predicates...),
		// clone intermediate query.
		sql:  umusq.sql.Clone(),
		path: umusq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CompanyID int `json:"company_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UpgradeMacUpgradeStrategy.Query().
//		GroupBy(upgrademacupgradestrategy.FieldCompanyID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (umusq *UpgradeMacUpgradeStrategyQuery) GroupBy(field string, fields ...string) *UpgradeMacUpgradeStrategyGroupBy {
	umusq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UpgradeMacUpgradeStrategyGroupBy{build: umusq}
	grbuild.flds = &umusq.ctx.Fields
	grbuild.label = upgrademacupgradestrategy.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CompanyID int `json:"company_id,omitempty"`
//	}
//
//	client.UpgradeMacUpgradeStrategy.Query().
//		Select(upgrademacupgradestrategy.FieldCompanyID).
//		Scan(ctx, &v)
func (umusq *UpgradeMacUpgradeStrategyQuery) Select(fields ...string) *UpgradeMacUpgradeStrategySelect {
	umusq.ctx.Fields = append(umusq.ctx.Fields, fields...)
	sbuild := &UpgradeMacUpgradeStrategySelect{UpgradeMacUpgradeStrategyQuery: umusq}
	sbuild.label = upgrademacupgradestrategy.Label
	sbuild.flds, sbuild.scan = &umusq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UpgradeMacUpgradeStrategySelect configured with the given aggregations.
func (umusq *UpgradeMacUpgradeStrategyQuery) Aggregate(fns ...AggregateFunc) *UpgradeMacUpgradeStrategySelect {
	return umusq.Select().Aggregate(fns...)
}

func (umusq *UpgradeMacUpgradeStrategyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range umusq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, umusq); err != nil {
				return err
			}
		}
	}
	for _, f := range umusq.ctx.Fields {
		if !upgrademacupgradestrategy.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if umusq.path != nil {
		prev, err := umusq.path(ctx)
		if err != nil {
			return err
		}
		umusq.sql = prev
	}
	return nil
}

func (umusq *UpgradeMacUpgradeStrategyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UpgradeMacUpgradeStrategy, error) {
	var (
		nodes = []*UpgradeMacUpgradeStrategy{}
		_spec = umusq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UpgradeMacUpgradeStrategy).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UpgradeMacUpgradeStrategy{config: umusq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, umusq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (umusq *UpgradeMacUpgradeStrategyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := umusq.querySpec()
	_spec.Node.Columns = umusq.ctx.Fields
	if len(umusq.ctx.Fields) > 0 {
		_spec.Unique = umusq.ctx.Unique != nil && *umusq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, umusq.driver, _spec)
}

func (umusq *UpgradeMacUpgradeStrategyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(upgrademacupgradestrategy.Table, upgrademacupgradestrategy.Columns, sqlgraph.NewFieldSpec(upgrademacupgradestrategy.FieldID, field.TypeInt))
	_spec.From = umusq.sql
	if unique := umusq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if umusq.path != nil {
		_spec.Unique = true
	}
	if fields := umusq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upgrademacupgradestrategy.FieldID)
		for i := range fields {
			if fields[i] != upgrademacupgradestrategy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := umusq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := umusq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := umusq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := umusq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (umusq *UpgradeMacUpgradeStrategyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(umusq.driver.Dialect())
	t1 := builder.Table(upgrademacupgradestrategy.Table)
	columns := umusq.ctx.Fields
	if len(columns) == 0 {
		columns = upgrademacupgradestrategy.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if umusq.sql != nil {
		selector = umusq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if umusq.ctx.Unique != nil && *umusq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range umusq.predicates {
		p(selector)
	}
	for _, p := range umusq.order {
		p(selector)
	}
	if offset := umusq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := umusq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UpgradeMacUpgradeStrategyGroupBy is the group-by builder for UpgradeMacUpgradeStrategy entities.
type UpgradeMacUpgradeStrategyGroupBy struct {
	selector
	build *UpgradeMacUpgradeStrategyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (umusgb *UpgradeMacUpgradeStrategyGroupBy) Aggregate(fns ...AggregateFunc) *UpgradeMacUpgradeStrategyGroupBy {
	umusgb.fns = append(umusgb.fns, fns...)
	return umusgb
}

// Scan applies the selector query and scans the result into the given value.
func (umusgb *UpgradeMacUpgradeStrategyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, umusgb.build.ctx, ent.OpQueryGroupBy)
	if err := umusgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpgradeMacUpgradeStrategyQuery, *UpgradeMacUpgradeStrategyGroupBy](ctx, umusgb.build, umusgb, umusgb.build.inters, v)
}

func (umusgb *UpgradeMacUpgradeStrategyGroupBy) sqlScan(ctx context.Context, root *UpgradeMacUpgradeStrategyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(umusgb.fns))
	for _, fn := range umusgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*umusgb.flds)+len(umusgb.fns))
		for _, f := range *umusgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*umusgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := umusgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UpgradeMacUpgradeStrategySelect is the builder for selecting fields of UpgradeMacUpgradeStrategy entities.
type UpgradeMacUpgradeStrategySelect struct {
	*UpgradeMacUpgradeStrategyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (umuss *UpgradeMacUpgradeStrategySelect) Aggregate(fns ...AggregateFunc) *UpgradeMacUpgradeStrategySelect {
	umuss.fns = append(umuss.fns, fns...)
	return umuss
}

// Scan applies the selector query and scans the result into the given value.
func (umuss *UpgradeMacUpgradeStrategySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, umuss.ctx, ent.OpQuerySelect)
	if err := umuss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpgradeMacUpgradeStrategyQuery, *UpgradeMacUpgradeStrategySelect](ctx, umuss.UpgradeMacUpgradeStrategyQuery, umuss, umuss.inters, v)
}

func (umuss *UpgradeMacUpgradeStrategySelect) sqlScan(ctx context.Context, root *UpgradeMacUpgradeStrategyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(umuss.fns))
	for _, fn := range umuss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*umuss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := umuss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
