// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"upgradelink-admin-upgrade/server/ent/predicate"
	"upgradelink-admin-upgrade/server/ent/upgradewinupgradestrategy"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UpgradeWinUpgradeStrategyDelete is the builder for deleting a UpgradeWinUpgradeStrategy entity.
type UpgradeWinUpgradeStrategyDelete struct {
	config
	hooks    []Hook
	mutation *UpgradeWinUpgradeStrategyMutation
}

// Where appends a list predicates to the UpgradeWinUpgradeStrategyDelete builder.
func (uwusd *UpgradeWinUpgradeStrategyDelete) Where(ps ...predicate.UpgradeWinUpgradeStrategy) *UpgradeWinUpgradeStrategyDelete {
	uwusd.mutation.Where(ps...)
	return uwusd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uwusd *UpgradeWinUpgradeStrategyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, uwusd.sqlExec, uwusd.mutation, uwusd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (uwusd *UpgradeWinUpgradeStrategyDelete) ExecX(ctx context.Context) int {
	n, err := uwusd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uwusd *UpgradeWinUpgradeStrategyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(upgradewinupgradestrategy.Table, sqlgraph.NewFieldSpec(upgradewinupgradestrategy.FieldID, field.TypeInt))
	if ps := uwusd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, uwusd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	uwusd.mutation.done = true
	return affected, err
}

// UpgradeWinUpgradeStrategyDeleteOne is the builder for deleting a single UpgradeWinUpgradeStrategy entity.
type UpgradeWinUpgradeStrategyDeleteOne struct {
	uwusd *UpgradeWinUpgradeStrategyDelete
}

// Where appends a list predicates to the UpgradeWinUpgradeStrategyDelete builder.
func (uwusdo *UpgradeWinUpgradeStrategyDeleteOne) Where(ps ...predicate.UpgradeWinUpgradeStrategy) *UpgradeWinUpgradeStrategyDeleteOne {
	uwusdo.uwusd.mutation.Where(ps...)
	return uwusdo
}

// Exec executes the deletion query.
func (uwusdo *UpgradeWinUpgradeStrategyDeleteOne) Exec(ctx context.Context) error {
	n, err := uwusdo.uwusd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{upgradewinupgradestrategy.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uwusdo *UpgradeWinUpgradeStrategyDeleteOne) ExecX(ctx context.Context) {
	if err := uwusdo.Exec(ctx); err != nil {
		panic(err)
	}
}
