// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"
	"time"

	hello "upgradelink-admin-task/server/task/internal/handler/hello"
	"upgradelink-admin-task/server/task/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: hello.HelloHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/hello"),
		rest.WithTimeout(30000*time.Millisecond),
	)
}
